import test from'node:test';import assert from'node:assert/strict';import{createAnalyticsDelivery}from'../src/analytics-delivery.js';
const event=(n=1)=>({uuid:`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`,event:'jett_command_result',timestamp:'2026-09-08T00:00:00.000Z',properties:{distinct_id:'00000000-0000-4000-8000-000000000099',status:'failed',actual:'error'}});
function fixture(extra={}){const values=new Map(),timers=new Map();let timer=0,clock=1000;const storage={getItem:k=>values.get(k),setItem:(k,v)=>values.set(k,v)};const options={storage,fetch:async()=>({ok:true,status:200}),endpoint:'https://analytics.example/batch/',token:'phc_test',now:()=>clock,schedule:fn=>{timers.set(++timer,fn);return timer;},cancel:id=>timers.delete(id),...extra};return{options,values,timers,advance:n=>clock+=n,create:()=>createAnalyticsDelivery(options)};}
test('unconfigured default-enabled durable queue retains immutable sanitized UUID events across reload',async()=>{const f=fixture({endpoint:undefined}),a=f.create(),input=event();input.properties.rawText='private transcript';await a.enqueue([input]);input.properties.status='saved';assert.equal(a.getState().status,'unconfigured');assert.equal(a.getState().pending,1);a.dispose();const b=f.create();assert.equal(b.getState().pending,1);assert.ok(![...f.values.values()].join('').includes('private'));assert.ok([...f.values.values()].join('').includes('failed'));await b.flush();assert.equal(b.getState().pending,1);b.dispose();});
test('HTTP failure retains outbox, retry identity unchanged and success acknowledges without reenqueuing duplicates',async()=>{let attempts=0;const requests=[];const f=fixture({fetch:async(url,opts)=>{requests.push({url,...opts});return {ok:++attempts>1,status:attempts>1?200:503};}}),a=f.create();await a.enqueue([event()]);await a.flush();assert.equal(a.getState().pending,1);assert.equal(a.getState().nextRetryAt,2000);f.advance(1000);await a.flush();assert.equal(a.getState().pending,0);assert.equal(JSON.parse(requests[0].body).batch[0].uuid,JSON.parse(requests[1].body).batch[0].uuid);assert.equal(JSON.parse(requests[1].body).api_key,'phc_test');assert.equal(requests[1].credentials,'omit');assert.equal((await a.enqueue([event()])).duplicate,1);a.dispose();const b=f.create();assert.equal((await b.enqueue([event()])).duplicate,1);b.dispose();});
test('opt-out aborts active request, clears durable data, survives reload and late success cannot revive',async()=>{let resolve,signal;const f=fixture({fetch:async(_url,opts)=>{signal=opts.signal;return await new Promise(r=>resolve=r);}}),a=f.create();await a.enqueue([event()]);const pending=a.flush();while(!signal)await Promise.resolve();await a.setEnabled(false);assert.equal(signal.aborted,true);assert.equal(a.getState().pending,0);resolve({ok:true,status:200});await pending;assert.equal(a.getState().enabled,false);assert.equal(f.timers.size,0);assert.equal((await a.enqueue([event(2)])).accepted,0);a.dispose();const b=f.create();assert.equal(b.getState().enabled,false);assert.equal(b.getState().pending,0);b.dispose();});
test('quota failure rejects acceptance and refuses transmission',async()=>{let calls=0;const f=fixture({storage:{getItem:()=>null,setItem:()=>{throw Error('quota');}},fetch:async()=>{calls++;return{ok:true};}}),a=f.create();assert.equal((await a.enqueue([event()])).accepted,0);await a.flush();assert.equal(calls,0);assert.equal(a.getState().pending,0);assert.equal(a.getState().storageAvailable,false);a.dispose();});
test('bounded queue rejects new overflow without evicting old events and invalid/private config never sends',async()=>{const f=fixture({token:'phx_personal'}),a=f.create();const queued=await a.enqueue(Array.from({length:1001},(_,i)=>event(i+1)));assert.equal(queued.accepted,1000);assert.equal(queued.rejected,1);assert.equal(a.getState().configured,false);assert.equal(a.getState().pending,1000);assert.equal((await a.enqueue([{...event(1002),uuid:'invalid'}])).rejected,1);a.dispose();});
test('dispose fences late response and keeps pending data for next instance',async()=>{let resolve;const f=fixture({fetch:()=>new Promise(r=>resolve=r)}),a=f.create();await a.enqueue([event()]);const pending=a.flush();while(!resolve)await Promise.resolve();a.dispose();resolve({ok:true});await pending;const b=f.create();assert.equal(b.getState().pending,1);b.dispose();});
test('hung request times out, preserves stable queued event and schedules bounded retry',async()=>{let signal;const f=fixture({fetch:(_url,opts)=>{signal=opts.signal;return new Promise(()=>{});}}),a=f.create();await a.enqueue([event()]);const pending=a.flush();while(!signal)await Promise.resolve();const callback=[...f.timers.values()][0];callback();await pending;assert.equal(signal.aborted,true);assert.equal(a.getState().pending,1);assert.equal(a.getState().attempt,1);assert.equal(a.getState().lastError,'network-error');a.dispose();});
test('two concurrent producers refresh under shared lock and cannot overwrite pending events',async()=>{const f=fixture({endpoint:undefined}),a=f.create(),b=f.create();await Promise.all([a.enqueue([event(1)]),b.enqueue([event(2)])]);a.dispose();b.dispose();const c=f.create();assert.equal(c.getState().pending,2);c.dispose();});
test('cross-tab optout storage event aborts pending request and queued writes cannot revive disabled queue',async()=>{const events=new EventTarget(),f=fixture({eventTarget:events,fetch:()=>new Promise(()=>{})}),a=f.create(),b=f.create();await a.enqueue([event()]);const pending=a.flush();while(!a.getState().sending)await Promise.resolve();await b.setEnabled(false);const change=new Event('storage');change.key='jett.analytics-delivery.v1.enabled';events.dispatchEvent(change);await pending;assert.equal(a.getState().enabled,false);assert.equal((await a.enqueue([event(2)])).accepted,0);assert.equal(a.getState().pending,0);a.dispose();b.dispose();});
test('outbox load and sender independently strip private text in enum metadata',async()=>{let body;const f=fixture({fetch:async(_url,opts)=>{body=opts.body;return{ok:true};}}),a=f.create(),input=event();Object.assign(input.properties,{status:'private passage',intent:'private passage',reason:'private passage',command_id:'private passage',blockIndex:-1,confidence:2});await a.enqueue([input]);await a.flush();assert.ok(!body.includes('private passage'));assert.equal(JSON.parse(body).batch[0].properties.blockIndex,undefined);a.dispose();});
test('ack merge under injected Web Locks preserves events enqueued by another tab during request',async()=>{const jobs=new Map(),locks={request(name,fn){const promise=(jobs.get(name)??Promise.resolve()).catch(()=>{}).then(fn);jobs.set(name,promise);return promise;}};let resolve;const f=fixture({locks,fetch:()=>new Promise(r=>resolve=r)}),a=f.create(),b=f.create();await a.enqueue([event(1)]);const pending=a.flush();while(!resolve)await Promise.resolve();await b.enqueue([event(2)]);resolve({ok:true});await pending;assert.equal(a.getState().coordination,'cross-tab');a.dispose();b.dispose();const c=f.create();assert.equal(c.getState().pending,1);assert.equal((await c.enqueue([event(1)])).duplicate,1);c.dispose();});
test('pre-request optout releases sending state even when request never began',async()=>{let calls=0;const f=fixture({fetch:async()=>{calls++;return{ok:true};}}),a=f.create();await a.enqueue([event()]);a.subscribe(state=>{if(state.sending)f.options.storage.setItem('jett.analytics-delivery.v1.enabled','false');});await a.flush();assert.equal(calls,0);assert.equal(a.getState().sending,false);assert.equal(a.getState().enabled,false);a.dispose();});
test('successful optout does not mask another tabs later enable',async()=>{const events=new EventTarget(),f=fixture({eventTarget:events,endpoint:undefined}),a=f.create(),b=f.create();await a.setEnabled(false);await b.setEnabled(true);const change=new Event('storage');change.key='jett.analytics-delivery.v1.enabled';events.dispatchEvent(change);assert.equal(a.getState().enabled,true);assert.equal((await a.enqueue([event()])).accepted,1);a.dispose();b.dispose();});
test('automatic flush rechecks shared backoff after another tab failed',async()=>{let calls=0;const f=fixture({fetch:async()=>{calls++;return{ok:false,status:503};}}),a=f.create(),b=f.create();await a.enqueue([event()]);await a.flush();await b.flush({automatic:true});assert.equal(calls,1);assert.equal(b.getState().nextRetryAt,2000);a.dispose();b.dispose();});
test('overlapping disable and enable still purges all data queued before optout',async()=>{const f=fixture({endpoint:undefined}),a=f.create();await a.enqueue([event()]);await Promise.all([a.setEnabled(false),a.setEnabled(true)]);assert.equal(a.getState().enabled,true);assert.equal(a.getState().pending,0);assert.equal((await a.enqueue([event()])).duplicate,1);a.dispose();const b=f.create();assert.equal(b.getState().pending,0);assert.equal(b.getState().enabled,true);b.dispose();});
