import test from 'node:test';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import path from 'node:path';
import {mkdtemp,readFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import puppeteer from 'puppeteer-core';
import {root} from './validate.mjs';

test('actual command journal distinguishes saved action, reading and failed persistence and retains private feedback locally',{timeout:90000},async t=>{
 const server=spawn(process.execPath,[path.join(root,'node_modules/vite/bin/vite.js'),'--host','127.0.0.1','--port','4987','--strictPort'],{cwd:root,stdio:'ignore'});t.after(()=>server.kill('SIGTERM'));
 const url='http://127.0.0.1:4987/';
 for(let i=0;i<100;i++){try{if((await fetch(url)).ok)break;}catch{}if(i===99)throw Error('Vite unavailable');await new Promise(r=>setTimeout(r,100));}
 const browser=await puppeteer.launch({executablePath:process.env.CHROME_PATH??'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});t.after(()=>browser.close());
 const page=await browser.newPage();await page.setViewport({width:1100,height:850});
 const downloads=await mkdtemp(path.join(tmpdir(),'jett-command-export-'));t.after(()=>rm(downloads,{recursive:true,force:true}));
 const cdp=await page.createCDPSession();await cdp.send('Browser.setDownloadBehavior',{behavior:'allow',downloadPath:downloads});
 await page.evaluateOnNewDocument(()=>{localStorage.setItem('jt.welcomed','1');localStorage.setItem('jt.mic','off');});
 await page.goto(url);await page.waitForFunction(()=>window.__jtApp?.booted);
 await page.click('#home-sample');await page.waitForSelector('#doc p[data-block="0"]');await page.locator('#doc p[data-block="0"]').click();
 await page.evaluate(async()=>{window.__jtApp.commandJournal.clear();await window.__jtApp.voiceSegment('highlight this');});
 let rows=await page.evaluate(()=>window.__jtApp.commandJournal.list());
 assert.equal(rows[0].source,'sim');assert.equal(rows.length,1);assert.ok(rows[0].events.some(e=>e.stage==='result'&&e.status==='saved'&&e.actual==='durable-entry'));
 const durable=await page.evaluate(async()=>{const {getRecords}=await import('/src/db.js');return getRecords(window.__jtApp.currentDoc().id);});
 assert.ok(durable.some(e=>e.act==='highlight'));
 await page.evaluate(()=>window.__jtApp.voiceSegment('unrelated purple spaceship'));
 rows=await page.evaluate(()=>window.__jtApp.commandJournal.list());assert.equal(rows.length,2);assert.ok(!rows[1].events.some(e=>e.status==='saved'));
 const before=await page.evaluate(()=>window.__jtApp.entries().length);
 await page.evaluate(()=>window.__jtApp.voiceSegment('Highlight a lead charge'));
 assert.equal(await page.evaluate(()=>window.__jtApp.entries().length),before,'wrong recognized words must not highlight the previous passage');
 assert.ok((await page.evaluate(()=>window.__jtApp.commandJournal.list())).at(-1).events.some(e=>e.stage==='target'&&e.status==='missing'));
 await page.evaluate(()=>window.__jtApp.voiceSegment('Highlight a late charge'));
 const exact=await page.evaluate(()=>window.__jtApp.entries().at(-1));assert.equal(exact.anchor.quotedText,'a late charge');
 await page.evaluate(()=>window.__jtApp.showView('settings'));await page.click('#command-journal-raw');
 await page.evaluate(()=>window.__jtApp.voiceSegment('private diagnostic words'));
 await page.waitForFunction(()=>document.querySelector('#command-journal-list').textContent.includes('private diagnostic words'));
 await page.click('#command-journal-list li:first-child button:last-child');
 await page.select('#command-journal-list li:first-child select','highlight');
 await page.setViewport({width:375,height:812});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'journal fits narrow screen');
 await page.screenshot({path:path.join(root,'../runtime/live-voice-diagnosis/command-journal-narrow.png'),fullPage:true});
 await page.setViewport({width:1100,height:850});
 let exported=await page.evaluate(()=>window.__jtApp.commandJournal.export());assert.ok(exported.some(e=>e.properties.feedback_rating==='missed'));assert.ok(!JSON.stringify(exported).includes('private diagnostic words'));
 await page.click('#command-journal-export');
 let downloaded;
 for(let i=0;i<100;i++){try{downloaded=JSON.parse(await readFile(path.join(downloads,'jett-command-events.json'),'utf8'));break;}catch{}await new Promise(r=>setTimeout(r,50));}
 assert.deepEqual(downloaded,exported,'visible export downloads exact sanitized event array');
 // Induce a real IndexedDB write failure after parsing, through the actual act engine.
 await page.evaluate(()=>{window.__realTransaction=IDBDatabase.prototype.transaction;IDBDatabase.prototype.transaction=function(names,mode,...rest){if(mode==='readwrite')throw new DOMException('fixture failure','QuotaExceededError');return window.__realTransaction.call(this,names,mode,...rest);};});
 await page.evaluate(()=>window.__jtApp.perform('highlight',0));
 rows=await page.evaluate(()=>window.__jtApp.commandJournal.list());assert.equal(rows.at(-1).events.at(-1).status,'failed');assert.ok(!rows.at(-1).events.some(e=>e.status==='saved'));
 await page.evaluate(()=>{IDBDatabase.prototype.transaction=window.__realTransaction;});
 const beforeAsk=await page.evaluate(()=>window.__jtApp.commandJournal.list().length);
 await page.evaluate(()=>window.__jtApp.voiceSegment('highlight the'));
 assert.equal(await page.evaluate(()=>window.__jtApp.ask()?.kind),'target');
 await page.evaluate(()=>window.__jtApp.resolveAsk(0));
 rows=await page.evaluate(()=>window.__jtApp.commandJournal.list());assert.equal(rows.length,beforeAsk+1,'target confirmation retains original trace');assert.ok(rows.at(-1).events.some(e=>e.status==='saved'));
 await page.evaluate(()=>window.__jtApp.voiceSegment('show my acts'));
 assert.equal((await page.evaluate(()=>window.__jtApp.commandJournal.list())).at(-1).events.at(-1).actual,'history');
 await page.evaluate(async()=>{await window.__jtApp.voiceSegment('math mode');await window.__jtApp.voiceSegment('two plus two');});
 const beforeKeep=await page.evaluate(()=>window.__jtApp.commandJournal.list().length);
 await page.evaluate(()=>window.__jtApp.voiceSegment('keep that'));
 rows=await page.evaluate(()=>window.__jtApp.commandJournal.list());assert.equal(rows.length,beforeKeep+1);assert.equal(rows.at(-1).source,'sim');assert.ok(rows.at(-1).events.some(e=>e.status==='saved'));
 await page.evaluate(()=>window.__jtApp.voiceSegment('exit math mode'));
 await page.evaluate(()=>window.__jtApp.showView('settings'));
 await page.click('#command-journal-raw');assert.ok(!JSON.stringify(await page.evaluate(()=>window.__jtApp.commandJournal.list())).includes('private diagnostic words'));
 await page.reload();await page.waitForFunction(()=>window.__jtApp?.booted);assert.ok((await page.evaluate(()=>window.__jtApp.commandJournal.list())).length>=4);
 await page.evaluate(()=>window.__jtApp.showView('settings'));await page.click('#command-journal-clear');assert.deepEqual(await page.evaluate(()=>window.__jtApp.commandJournal.list()),[]);
 assert.equal(await page.evaluate(()=>window.__jtApp.micAudioHeld()),false);
});
