import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,writeFile,readFile,rm,mkdir} from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {spawn} from 'node:child_process';
import puppeteer from 'puppeteer-core';
import {root} from './validate.mjs';
import {makeEpubFixture} from './epub-fixture.mjs';

test('EPUB own reader preserves semantic chapters, navigation, typography and saved passages',{timeout:90000},async t=>{
 const dir=await mkdtemp(path.join(os.tmpdir(),'jett-epub-'));t.after(()=>rm(dir,{recursive:true,force:true}));
 const bytes=await makeEpubFixture({entries:{'Book/chapters/one.xhtml':'<html xmlns="http://www.w3.org/1999/xhtml"><head><link rel="stylesheet" href="../styles/book.css"/></head><body><h1 id="opening">The orchard</h1><p>Read <em>very carefully</em>, नमस्ते दुनिया.</p><img src="../images/dot.png" alt="A dot"/>'+Array.from({length:30},(_,i)=>`<p>Orchard passage ${i}: reading slowly through the trees brings the distant river into view.</p>`).join('')+'</body></html>','Book/styles/book.css':'body{font-size:12pt;color:#202020}p{font-size:12pt}em{font-style:italic}'}});const file=path.join(dir,'orchard.epub');await writeFile(file,bytes);
 const port=process.env.JETT_EPUB_TEST_PORT||'5103';
 const server=spawn(process.execPath,[path.join(root,'node_modules/vite/bin/vite.js'),'--host','127.0.0.1','--port',port,'--strictPort'],{cwd:root,stdio:'ignore'});t.after(()=>server.kill());
 const url=`http://127.0.0.1:${port}`;for(let i=0;i<100;i++){try{if((await fetch(url)).ok)break;}catch{}await new Promise(r=>setTimeout(r,100));}
 const browser=await puppeteer.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});t.after(()=>browser.close());
 const page=await browser.newPage();await page.setViewport({width:1280,height:900});await page.evaluateOnNewDocument(()=>{localStorage.setItem('jt.welcomed','1');localStorage.setItem('jt.mic','off');});
 const errors=[];page.on('pageerror',error=>errors.push(error.message));
 await page.goto(url);await page.waitForFunction(()=>window.__jtApp?.booted);
 await(await page.$('#home-file-input')).uploadFile(file);
 await page.waitForFunction(()=>document.querySelectorAll('.epub-chapter').length===2&&document.body.dataset.view==='read');
 t.diagnostic('Imported semantic book');
 assert.equal(await page.$eval('.epub-book em',node=>node.textContent),'very carefully');
 assert.equal(await page.$eval('.epub-book img',node=>node.src.startsWith('blob:')),true);
 const identity=await page.evaluate(()=>{const doc=window.__jtApp.currentDoc();return {id:doc.id,source:Array.from(doc.sourceBytes),blocks:doc.blocks};});assert.deepEqual(identity.source,Array.from(bytes));
 const downloads=path.join(dir,'downloads');await mkdir(downloads);const cdp=await page.createCDPSession();await cdp.send('Page.setDownloadBehavior',{behavior:'allow',downloadPath:downloads});await page.locator('#reader-document-menu summary').click();await page.locator('#download-original').click();let downloaded;for(let i=0;i<100;i++){try{downloaded=await readFile(path.join(downloads,'orchard.epub'));break;}catch{await new Promise(r=>setTimeout(r,50));}}assert.deepEqual(Array.from(downloaded??[]),Array.from(bytes),'actual original download matches EPUB archive byte for byte');await page.locator('#reader-document-menu summary').click();
 await page.locator('[data-workspace="annotate"]').click();
 await page.evaluate(()=>{const em=document.querySelector('.epub-book em'),range=document.createRange();range.setStart(em.firstChild,5);range.setEnd(em.nextSibling,em.nextSibling.textContent.length);getSelection().removeAllRanges();getSelection().addRange(range);document.dispatchEvent(new Event('selectionchange'));});
 await page.waitForFunction(()=>!document.querySelector('[data-annotation=highlight]').disabled);await page.locator('[data-annotation=highlight]').click();await page.waitForFunction(()=>document.querySelector('.annotation-selection').textContent.startsWith('Saved on this device'),{timeout:5000}).catch(async error=>{throw new Error(error.message+' status='+await page.$eval('.annotation-selection',node=>node.textContent)+' entries='+JSON.stringify(await page.evaluate(()=>window.__jtApp.entries())));});
 await page.locator('[data-workspace="read"]').click();
 const originalSize=await page.$eval('.epub-book p',node=>parseFloat(getComputedStyle(node).fontSize));await page.evaluate(()=>[...document.querySelectorAll('.epub-tools summary')].find(n=>n.textContent==='Text').click());await page.select('[aria-label="Book text size"]','30');await page.select('[aria-label="Book typeface"]','sans');
 assert.equal(await page.$eval('.epub-book',node=>getComputedStyle(node).fontSize),'30px');assert.ok(await page.$$eval('.epub-book em',nodes=>nodes.every(node=>Math.abs(parseFloat(getComputedStyle(node).fontSize)-Number(node.dataset.epubFontBase)*30/22)<.05)),'annotation-cloned emphasis scales too');assert.ok(await page.$eval('.epub-book p',node=>parseFloat(getComputedStyle(node).fontSize))>originalSize*1.3,'actual fixed-size publisher paragraph grows');
 await page.evaluate(()=>{const target=[...document.querySelectorAll('.epub-book p')].find(n=>n.textContent.startsWith('Orchard passage 20:'));scrollBy({top:target.getBoundingClientRect().top-document.getElementById('reader-chrome').getBoundingClientRect().bottom-12,behavior:'instant'});});
 const deepBefore=await page.evaluate(()=>[...document.querySelectorAll('.epub-book p')].find(n=>n.textContent.startsWith('Orchard passage 20:')).getBoundingClientRect().top);
 await page.select('[aria-label="Book text size"]','26');
 const deepAfter=await page.evaluate(()=>[...document.querySelectorAll('.epub-book p')].find(n=>n.textContent.startsWith('Orchard passage 20:')).getBoundingClientRect().top);
 assert.ok(Math.abs(deepBefore-deepAfter)<2,'deep visible passage survives typography change');
 await page.select('[aria-label="Book text size"]','30');
 t.diagnostic('Typography set');await page.evaluate(()=>{[...document.querySelectorAll('.epub-tools summary')].find(n=>n.textContent==='Text').click();[...document.querySelectorAll('.epub-tools summary')].find(n=>n.textContent==='Contents').click();});await page.evaluate(()=>[...document.querySelectorAll('.epub-contents button')].find(node=>node.textContent==='Footnote').click());
 await page.waitForFunction(()=>window.__jtApp.readerSession().activeId);
 assert.equal(await page.$eval('.epub-return',node=>node.disabled),false);
 await page.evaluate(()=>[...document.querySelectorAll('.epub-tools summary')].find(n=>n.textContent==='Find').click());await page.locator('.epub-tools input[type=search]').fill('beside the river');await page.locator('.epub-find').click();
 assert.match(await page.$eval('.epub-tools [role=status]',node=>node.textContent),/1 of 1/);
 await page.evaluate(()=>[...document.querySelectorAll('.epub-tools summary')].find(n=>n.textContent==='Find').click());t.diagnostic('Navigation verified');await page.locator('[data-workspace="annotate"]').click();t.diagnostic('Annotate opened');
 await page.evaluate(()=>{const block=[...document.querySelectorAll('.epub-book [data-block]')].find(node=>node.textContent.includes('Keep reading beside'));const range=document.createRange();range.selectNodeContents(block);getSelection().removeAllRanges();getSelection().addRange(range);document.dispatchEvent(new Event('selectionchange'));});
 await page.waitForFunction(()=>!document.querySelector('[data-annotation=highlight]').disabled);
 await page.locator('[data-annotation=highlight]').click();await page.waitForFunction(()=>document.querySelector('.annotation-selection').textContent.startsWith('Saved on this device'),{timeout:10000}).catch(async error=>{throw new Error(error.message+' status='+await page.$eval('.annotation-selection',node=>node.textContent)+' errors='+errors.join(';'));});
 t.diagnostic('Annotation saved');
 const backup=await page.evaluate(async()=>{await window.__jtApp.position.flush();const db=await import('/src/db.js'),backup=await import('/src/library-backup.js');return backup.encodeLibraryBackup(await db.readLibrarySnapshot());});
 const context=await browser.createBrowserContext();const restored=await context.newPage();await restored.goto(url);await restored.waitForFunction(()=>window.__jtApp?.booted);
 await restored.evaluate(async backup=>{const db=await import('/src/db.js'),codec=await import('/src/library-backup.js');await db.restoreLibrarySnapshot(await codec.decodeLibraryBackup(backup));},backup);
 await restored.reload();await restored.waitForFunction(()=>window.__jtApp?.booted);await restored.evaluate(async id=>{const db=await import('/src/db.js');await window.__jtApp.openDocument(await db.getDoc(id));window.__jtApp.showView('read');},identity.id);
 assert.deepEqual(await restored.evaluate(()=>Array.from(window.__jtApp.currentDoc().sourceBytes)),identity.source);
 assert.ok(await restored.evaluate(()=>window.__jtApp.entries().some(entry=>entry.act==='highlight'||entry.verbId==='highlight')),'restored annotation remains in the operation store');
 await context.close();await page.reload();await page.waitForFunction(()=>document.querySelectorAll('.epub-chapter').length===2&&window.__jtApp?.booted);await page.waitForFunction(()=>[...document.querySelectorAll('.epub-book [data-block]')].find(n=>n.getBoundingClientRect().bottom>document.getElementById('reader-chrome').getBoundingClientRect().bottom+12)?.textContent==='Keep reading beside the river.',{timeout:3000});
 assert.equal(await page.$eval('[aria-label="Book text size"]',node=>node.value),'30');
 assert.equal(await page.$eval('[aria-label="Book typeface"]',node=>node.value),'sans');
 assert.equal(await page.evaluate(()=>window.__jtApp.currentDoc().id),identity.id);
 assert.equal(await page.$eval('#pdf-annotation-preview',node=>node.hidden),true);
 if(process.env.JETT_EPUB_EVIDENCE_DIR){await mkdir(process.env.JETT_EPUB_EVIDENCE_DIR,{recursive:true});await page.screenshot({path:path.join(process.env.JETT_EPUB_EVIDENCE_DIR,'desktop.png')});}
 await page.setViewport({width:390,height:844});await page.locator('[data-workspace="read"]').click();
 await page.waitForFunction(()=>[...document.querySelectorAll('.epub-book [data-block]')].find(n=>n.getBoundingClientRect().bottom>document.getElementById('reader-chrome').getBoundingClientRect().bottom+12)?.textContent==='Keep reading beside the river.',{timeout:3000});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);
 if(process.env.JETT_EPUB_EVIDENCE_DIR)await page.screenshot({path:path.join(process.env.JETT_EPUB_EVIDENCE_DIR,'phone.png')});
 assert.deepEqual(errors,[]);
});
