import test from 'node:test';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';import {JSDOM} from 'jsdom';import {ingestEpub} from '../src/epub-ingest.js';import {openEpubPackage} from '../src/epub-package.js';import {prepareEpubChapter} from '../src/epub-content.js';import {encodeLibraryBackup,decodeLibraryBackup} from '../src/library-backup.js';import {makeEpubFixture} from './epub-fixture.mjs';
function environment(){const dom=new JSDOM('<!doctype html><body></body>'),created=[],revoked=[];dom.window.URL.createObjectURL=blob=>{const url=`blob:fixture-${created.length}`;created.push({url,blob});return url;};dom.window.URL.revokeObjectURL=url=>revoked.push(url);globalThis.DOMParser=dom.window.DOMParser;return {dom,document:dom.window.document,created,revoked};}
for(const version of [2,3])test(`EPUB${version} ingest keeps exact source and stable all-spine semantic blocks`,async()=>{
 const env=environment();try{
 const bytes=await makeEpubFixture({version}),before=bytes.slice(),result=await ingestEpub(bytes,{name:'orchard.epub',document:env.document});assert.deepEqual(bytes,before);assert.deepEqual(result.sourceBytes,before);assert.notEqual(result.sourceBytes,bytes);assert.equal(result.sourceMime,'application/epub+zip');assert.equal(result.provenance.sourceKind,'epub');assert.equal(result.provenance.name,'orchard.epub');assert.equal(result.provenance.title,'Orchard पुस्तक');assert.equal(result.provenance.byteSize,bytes.length);assert.equal(result.provenance.contentDigest,'sha256:'+createHash('sha256').update(bytes).digest('hex'));
 assert.deepEqual(result.blocks.map(b=>b.text),['The orchard','Read carefully, नमस्ते दुनिया.','A footnote','The river','Keep reading beside the river.','Footnote text. Back']);assert.deepEqual(result.blocks.map(b=>b.index),[0,1,2,3,4,5]);assert.equal(new Set(result.blocks.map(b=>b.locator)).size,result.blocks.length);assert.ok(result.blocks.slice(0,3).every(b=>b.locator.startsWith('epub:Book/chapters/one.xhtml#')));assert.ok(result.blocks.slice(3).every(b=>b.locator.startsWith('epub:Book/chapters/two.xhtml#')));assert.deepEqual(env.revoked,env.created.map(c=>c.url),'all temporary import resources released');
 const book=await openEpubPackage(result.sourceBytes),live=[];for(let index=0;index<book.spine.length;index++){const chapter=prepareEpubChapter(book,index,{document:env.document,scopeId:`epub-rerender-${index}`});try{live.push(...chapter.blocks.map(({text,kind,locator,element})=>{assert.equal(element.textContent,text,'rendered target text equals persisted anchor text');return {text,kind,locator};}));}finally{chapter.dispose();}}
 assert.deepEqual(live,result.blocks.map(({index,...rest})=>rest),'DOM scope IDs do not alter source locators');
 const second=await ingestEpub(bytes,{name:'renamed.epub',document:env.document});assert.deepEqual(second.blocks,result.blocks);bytes[0]^=1;assert.deepEqual(result.sourceBytes,before,'returned custody remains independent of caller bytes');
 }finally{env.dom.window.close();}
});
test('EPUB original download bytes and backup decode retain source, provenance and block identities',async()=>{
 const env=environment();try{const bytes=await makeEpubFixture(),result=await ingestEpub(bytes,{name:'orchard.epub',document:env.document});const document={id:'epub-custody',title:result.provenance.title,text:result.blocks.map(b=>b.text).join('\n\n'),blocks:result.blocks,provenance:result.provenance,warnings:result.warnings,sourceBytes:result.sourceBytes,sourceMime:result.sourceMime,createdAt:new Date().toISOString(),revision:1};
 const encoded=await encodeLibraryBackup({docs:[document],records:[],positions:[]}),restored=(await decodeLibraryBackup(encoded)).docs[0];assert.deepEqual(restored.sourceBytes,bytes);assert.deepEqual(restored.blocks,result.blocks);assert.deepEqual(restored.provenance,result.provenance);assert.equal(restored.sourceMime,'application/epub+zip');
 // Same immutable byte/MIME payload as the original-download link; browser click
 // and delivery are covered by the integrated reader journey, not this unit test.
 const original=new Blob([restored.sourceBytes],{type:restored.sourceMime});assert.equal(original.type,'application/epub+zip');assert.deepEqual(new Uint8Array(await original.arrayBuffer()),bytes);const reopened=await ingestEpub(restored.sourceBytes,{name:restored.provenance.name,document:env.document});assert.deepEqual(reopened.blocks,result.blocks);
 }finally{env.dom.window.close();}
});
test('fixed layout refuses explicitly and leaves exact input unchanged',async()=>{const env=environment();try{const bytes=await makeEpubFixture({layout:'pre-paginated'}),copy=bytes.slice();await assert.rejects(ingestEpub(bytes,{name:'fixed.epub',document:env.document}),/Fixed-layout EPUB reading is not available yet/);assert.deepEqual(bytes,copy);assert.equal(env.created.length,0);}finally{env.dom.window.close();}});
