import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,writeFile,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import path from 'node:path';import {spawn} from 'node:child_process';import puppeteer from 'puppeteer-core';import {root} from './validate.mjs';import {makeEpubFixture} from './epub-fixture.mjs';
test('held second EPUB resize frame cannot overwrite newer passage, workspace or typography',{timeout:60000},async t=>{
 const directory=await mkdtemp(path.join(tmpdir(),'jett-epub-resize-'));t.after(()=>rm(directory,{recursive:true,force:true}));const file=path.join(directory,'race.epub');await writeFile(file,await makeEpubFixture({entries:{'Book/chapters/one.xhtml':'<html xmlns="http://www.w3.org/1999/xhtml"><head><title>Race</title></head><body><h1 id="opening">The orchard</h1>'+Array.from({length:40},(_,i)=>`<p>Orchard passage ${i}: Walk slowly through the trees, keeping this exact reading passage while the book reflows.</p>`).join('')+'</body></html>'}}));
 const server=spawn(process.execPath,[path.join(root,'node_modules/vite/bin/vite.js'),'--host','127.0.0.1','--port','5105','--strictPort'],{cwd:root,stdio:'ignore'});t.after(()=>server.kill());const url='http://127.0.0.1:5105';for(let i=0;i<100;i++){try{if((await fetch(url)).ok)break;}catch{}await new Promise(r=>setTimeout(r,100));}
 const main=await(await fetch(url+'/src/main.js')).text(),anchor='epubResizeFrame=requestAnimationFrame(()=>{const held=epubResizeView;epubResizeView=null;';assert.equal(main.split(anchor).length-1,1);const instrumented=main.replace(anchor,'epubResizeFrame=requestAnimationFrame(async()=>{const held=epubResizeView;epubResizeView=null;if(window.__epubResizeGate)await window.__epubResizeGate();');
 const browser=await puppeteer.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});t.after(()=>browser.close());const page=await browser.newPage();await page.setViewport({width:1280,height:900});await page.setRequestInterception(true);page.on('request',r=>r.url()===url+'/src/main.js'?r.respond({status:200,contentType:'text/javascript',body:instrumented}):r.continue());await page.evaluateOnNewDocument(()=>{localStorage.setItem('jt.welcomed','1');localStorage.setItem('jt.mic','off');});await page.goto(url);await page.waitForFunction(()=>window.__jtApp?.booted);await(await page.$('#home-file-input')).uploadFile(file);await page.waitForFunction(()=>document.querySelector('.epub-book'));const target=await page.evaluate(()=>window.__jtApp.currentDoc().blocks.findIndex(b=>b.text.startsWith('Orchard passage 18:')));assert.ok(target>1);
 async function hold(width){await page.evaluate(()=>{window.__epubResizeHeld=false;window.__epubResizeGate=()=>{window.__epubResizeGate=null;window.__epubResizeHeld=true;return new Promise(resolve=>window.__releaseEpubResize=resolve);};});await page.setViewport({width,height:900});await page.waitForFunction(()=>window.__epubResizeHeld);}
 async function release(){await page.evaluate(async()=>{window.__releaseEpubResize();await new Promise(requestAnimationFrame);await new Promise(requestAnimationFrame);});}
 async function view(){return page.evaluate(()=>JSON.parse(localStorage.getItem('jett.reader-session.v1')).views[window.__jtApp.currentDoc().id]);}
 t.diagnostic('Imported');await hold(768);t.diagnostic('Held768');await page.locator('.epub-tools summary::-p-text(Find)').click();await page.locator('.epub-tools input[type="search"]').fill('Orchard passage 18:');t.diagnostic('Filled search');await page.locator('.epub-find').click();t.diagnostic('Clicked find');await page.waitForFunction(index=>window.__jtApp.currentBlock()===index,{},target);await page.waitForFunction(index=>JSON.parse(localStorage.getItem('jett.reader-session.v1')).views[window.__jtApp.currentDoc().id].blockIndex===index,{},target);const before=await page.evaluate(()=>scrollY);await release();assert.equal(await page.evaluate(()=>window.__jtApp.currentBlock()),target);assert.equal((await view()).blockIndex,target);assert.ok(Math.abs(await page.evaluate(()=>scrollY)-before)<1,'stale resize must not scroll back over a newer Find destination');
 t.diagnostic('Find survived');await hold(390);t.diagnostic('Held390');await page.locator('[data-workspace="annotate"]').click();t.diagnostic('Annotate clicked');await page.waitForFunction(()=>document.body.dataset.readerWorkspace==='annotate');await page.locator('.epub-tools summary::-p-text(Text)').click();await page.select('.epub-tools [aria-label="Book text size"]','30');await page.select('.epub-tools [aria-label="Book typeface"]','sans');const newer=await view();assert.equal(newer.workspace,'annotate');assert.equal(newer.epub.size,30);assert.equal(newer.epub.font,'sans');await release();const final=await view();assert.equal(final.workspace,'annotate');assert.equal(final.epub.size,30);assert.equal(final.epub.font,'sans');assert.equal(await page.evaluate(()=>document.body.dataset.readerWorkspace),'annotate');
});
