import test from 'node:test';import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';import {readFile,mkdir,writeFile} from 'node:fs/promises';import path from 'node:path';
import puppeteer from 'puppeteer-core';import {getDocument} from 'pdfjs-dist/legacy/build/pdf.mjs';
import {root} from './validate.mjs';import {selectPdfQuote} from './pdf-selection-helpers.mjs';
test('Organize includes saved work, guards failed answers and preserves it through rotate/save/reload',{timeout:90000},async t=>{
 const server=spawn(process.execPath,[path.join(root,'node_modules/vite/bin/vite.js'),'--host','127.0.0.1','--port','5084','--strictPort'],{cwd:root,stdio:'ignore'});t.after(()=>server.kill());const url='http://127.0.0.1:5084';
 for(let i=0;i<100;i++){try{if((await fetch(url)).ok)break;}catch{}await new Promise(r=>setTimeout(r,100));}
 const browser=await puppeteer.launch({executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});t.after(()=>browser.close());const page=await browser.newPage();await page.setViewport({width:1280,height:1000});
 await page.setRequestInterception(true);page.on('request',r=>new URL(r.url()).pathname==='/src/pdf-combined.js'&&!new URL(r.url()).search?r.respond({status:200,contentType:'text/javascript',body:`import {exportCombinedPdf as actual} from '/src/pdf-combined.js?actual=1';export async function exportCombinedPdf(args){if(window.holdComposition){window.holdComposition=false;await new Promise(r=>window.releaseComposition=r);}return actual(args);}`}):r.continue());
 await page.evaluateOnNewDocument(()=>{localStorage.setItem('jt.welcomed','1');localStorage.setItem('jt.mic','off');});await page.goto(url);await page.waitForFunction(()=>window.__jtApp?.booted);
 const fixture=path.join(root,'test/fixtures/jett-fillable.pdf');await(await page.$('#home-file-input')).uploadFile(fixture);await page.waitForFunction(()=>!!window.__jtApp.currentDoc()?.id&&document.querySelector('#reader-tabs [aria-selected="true"]')?.dataset.documentId===window.__jtApp.currentDoc().id);
 const sourceId=await page.evaluate(()=>window.__jtApp.currentDoc().id);
 await page.locator('[data-workspace="fill"]').click();await page.waitForSelector('[data-field-name="full_name"]');
 await page.evaluate(()=>{window.originalPut=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(value,...rest){if(this.name==='docs'&&value.formDraft)throw new DOMException('Injected form save failure','QuotaExceededError');return originalPut.call(this,value,...rest);};});
 await page.locator('[data-field-name="full_name"]').fill('Taylor Saved Work');await page.waitForFunction(()=>!document.getElementById('pdf-form-retry').hidden);
 await page.locator('[data-workspace="organize"]').click();await page.locator('#reader-organize-pages').click();await page.waitForFunction(()=>document.getElementById('reader-persistence-status').textContent.includes('Answers could not be saved'));
 assert.equal(await page.$eval('#pdf-review-dialog',n=>n.open),false);
 await page.evaluate(()=>{IDBObjectStore.prototype.put=originalPut;});await page.locator('[data-workspace="fill"]').click();await page.locator('#pdf-form-retry').click();await page.waitForFunction(()=>!document.getElementById('pdf-form-preview').disabled);
 await page.locator('[data-workspace="annotate"]').click();await selectPdfQuote(page,'Contact and delivery',0,1);await page.locator('[data-annotation="highlight"]').click();await page.waitForFunction(()=>window.__jtApp.entries().some(e=>e.act==='highlight'));
 await selectPdfQuote(page,'Contact and delivery',0,1);await page.locator('[data-annotation="note"]').click();await page.locator('#annotation-note-text').fill('Keep this note with the answers.');await page.locator('.annotation-note button[type="submit"]').click();await page.waitForFunction(()=>window.__jtApp.entries().some(e=>e.act==='note'));
 await page.locator('[data-workspace="organize"]').click();await page.evaluate(()=>{window.holdComposition=true;});await page.locator('#reader-organize-pages').click();await page.waitForFunction(()=>!!window.releaseComposition);await page.keyboard.press('Escape');await page.evaluate(()=>releaseComposition());
 await page.locator('#reader-organize-pages').click();await page.waitForFunction(()=>document.getElementById('pdf-review-title').textContent==='Review saved-work copy'&&!document.getElementById('pdf-review-save').disabled);
 await page.locator('[aria-label="Rotate page 1 right"]').click();await page.waitForFunction(()=>document.getElementById('pdf-review-title').textContent==='Review rotated saved-work copy'&&!document.getElementById('pdf-review-save').disabled);
 await page.locator('#pdf-review-save').click();await page.waitForFunction(()=>window.__jtApp.currentDoc()?.id.startsWith('review_'));const resultId=await page.evaluate(()=>window.__jtApp.currentDoc().id);
 await page.reload();await page.waitForFunction(()=>window.__jtApp?.booted);
 const result=await page.evaluate(async({sourceId,resultId})=>{const {getDoc}=await import('/src/db.js');const source=await getDoc(sourceId),result=await getDoc(resultId);return {original:Array.from(new Uint8Array(source.sourceBytes)),bytes:Array.from(new Uint8Array(result.sourceBytes)),origin:result.provenance.derivedFrom};},{sourceId,resultId});assert.deepEqual(result.original,Array.from(await readFile(fixture)));assert.equal(result.origin.documentId,sourceId);
 const task=getDocument({data:new Uint8Array(result.bytes)});const pdf=await task.promise;try{const fields=await pdf.getFieldObjects();assert.equal(fields.full_name[0].value,'Taylor Saved Work');const p=await pdf.getPage(1);assert.equal(p.rotate,90);const annotations=await p.getAnnotations();assert.equal(annotations.filter(a=>a.subtype==='Highlight').length,1);assert.equal(annotations.find(a=>a.subtype==='Text').contentsObj.str,'Keep this note with the answers.');}finally{await task.destroy();}
 if(process.env.JETT_ORGANIZE_WORK_EVIDENCE_DIR){const dir=process.env.JETT_ORGANIZE_WORK_EVIDENCE_DIR;await mkdir(dir,{recursive:true});await writeFile(path.join(dir,'organized.pdf'),new Uint8Array(result.bytes));await writeFile(path.join(dir,'readback.json'),JSON.stringify({result:'PASS',rotation:90,field:'Taylor Saved Work',highlightCount:1,note:'Keep this note with the answers.',originalUnchanged:true,origin:result.origin},null,2));}
});
