import * as mupdf from 'mupdf';
import test from 'node:test';import assert from 'node:assert/strict';import {spawn} from 'node:child_process';import {readFile} from 'node:fs/promises';import path from 'node:path';import puppeteer from 'puppeteer-core';import {getDocument} from 'pdfjs-dist/legacy/build/pdf.mjs';import {root} from './validate.mjs';

test('actual Bento engine adapter previews, edits, verifies and rejects stale or unsupported requests',{timeout:90000},async t=>{
 const server=spawn(process.execPath,[path.join(root,'node_modules/vite/bin/vite.js'),'--host','127.0.0.1','--port','5096','--strictPort'],{cwd:root,stdio:'ignore'});t.after(()=>server.kill());const url='http://127.0.0.1:5096';for(let i=0;i<100;i++){try{if((await fetch(url)).ok)break;}catch{}await new Promise(r=>setTimeout(r,100));}
 const browser=await puppeteer.launch({executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});t.after(()=>browser.close());const page=await browser.newPage();await page.goto(url);const input=Array.from(await readFile(path.join(root,'test/fixtures/jett-range.pdf')));
 const result=await page.evaluate(async input=>{
  const {inspectEditablePage,editPdfParagraph}=await import('/src/pdf-text-editor.js'),source=new Uint8Array(input);const {PdfEngine}=await import('/vendor/bento-editcore/core.js'),create=PdfEngine.create,engines=[];PdfEngine.create=async function(){const e=await create.call(this);engines.push(e);return e;};const inspected=await inspectEditablePage(source,0),paragraph=inspected.paragraphs.find(p=>p.runs.map(r=>r.text).join('').includes('Start at the orchard gate'));
  if(!paragraph)throw new Error('Fixture paragraph missing');const originalText=paragraph.runs.map(r=>r.text).join('');
  const output=await editPdfParagraph(source,{pageIndex:0,paragraphId:paragraph.id,originalBox:paragraph.box,originalRotation:paragraph.rotation??0,originalText,text:originalText.replace('Start','Meet')});
  const requests=[{originalText:'stale text',text:'Different text'},{originalText,text:originalText.replace('Start','Meet'),originalBox:{...paragraph.box,x:paragraph.box.x+5}},{originalText,text:originalText.replace('Start','Meet'),originalRotation:90},{originalText,text:originalText+' 😀'},{originalText,text:''}];const refusals=[];
  for(const request of requests){try{await editPdfParagraph(source,{pageIndex:0,paragraphId:paragraph.id,originalBox:paragraph.box,originalRotation:paragraph.rotation??0,...request});refusals.push('accepted');}catch(error){refusals.push(error.code||error.message);}}
  const generate=PdfEngine.prototype.generateContent;PdfEngine.prototype.generateContent=()=>false;
  try{await editPdfParagraph(source,{pageIndex:0,paragraphId:paragraph.id,originalBox:paragraph.box,originalRotation:paragraph.rotation??0,originalText,text:originalText.replace('Start','Meet')});refusals.push('accepted');}catch(error){refusals.push(error.code||error.message);}finally{PdfEngine.prototype.generateContent=generate;}
  const retry=await editPdfParagraph(source,{pageIndex:0,paragraphId:paragraph.id,originalBox:paragraph.box,originalRotation:paragraph.rotation??0,originalText,text:originalText.replace('Start','Meet')});
  const longer=await editPdfParagraph(source,{pageIndex:0,paragraphId:paragraph.id,originalBox:paragraph.box,originalRotation:paragraph.rotation??0,originalText,text:'Meet near the orchard gate.'});PdfEngine.create=create;const cleaned=engines.map(e=>[e.page,e.session,e.doc,e._docBuf,e._providerPtr].every(handle=>!handle));return {longer:Array.from(longer.bytes),longerText:longer.after.text,cleaned,bytes:Array.from(output.bytes),retry:Array.from(retry.bytes),original:Array.from(source),before:output.before,after:output.after,refusals,pageBounds:inspected.pageBounds,transform:inspected.transform};
 },input);
 assert.ok(result.cleaned.length>=6&&result.cleaned.every(Boolean),'all fresh engines release native handles and callback after success and refusals');assert.deepEqual(result.original,input);assert.match(result.after.text,/Meet at the orchard gate/);assert.deepEqual(result.refusals,['EDIT_PARAGRAPH_STALE','EDIT_PARAGRAPH_STALE','EDIT_PARAGRAPH_STALE','EDIT_GLYPH_UNSUPPORTED','EDIT_TEXT_INVALID','EDIT_GENERATE_FAILED']);assert.equal(result.transform.length,6);assert.equal(result.pageBounds.length,4);
 assert.equal(result.longerText,'Meet near the orchard gate.');const lengthTask=getDocument({data:new Uint8Array(result.longer)});try{const pdf=await lengthTask.promise,content=await(await pdf.getPage(1)).getTextContent();assert.match(content.items.map(i=>i.str+(i.hasEOL?' ':'')).join(''),/Meet near the orchard gate/);}finally{await lengthTask.destroy();}
 const mixedDoc=new mupdf.PDFDocument(),regular=new mupdf.Font('Helvetica'),bold=new mupdf.Font('Helvetica-Bold');let mixedBytes;
 try{const normalRef=mixedDoc.addSimpleFont(regular),boldRef=mixedDoc.addSimpleFont(bold);const mixedPage=mixedDoc.addPage([0,0,600,800],0,{Font:{F1:normalRef,F2:boldRef}},'BT /F1 16 Tf 60 700 Td (Alpha ) Tj /F2 16 Tf (bold) Tj /F1 16 Tf ( omega.) Tj ET');mixedDoc.insertPage(-1,mixedPage);mixedPage.destroy();normalRef.destroy();boldRef.destroy();const buffer=mixedDoc.saveToBuffer();mixedBytes=Array.from(buffer.asUint8Array());buffer.destroy();}finally{regular.destroy();bold.destroy();mixedDoc.destroy();}
 const mixed=await page.evaluate(async input=>{const {inspectEditablePage,editPdfParagraph}=await import('/src/pdf-text-editor.js'),bytes=new Uint8Array(input),before=await inspectEditablePage(bytes,0),p=before.paragraphs.find(p=>p.runs.some(r=>r.bold)&&p.runs.some(r=>!r.bold));if(!p)throw new Error('Fixture did not produce mixed runs');const originalText=p.runs.map(r=>r.text).join(''),edited=await editPdfParagraph(bytes,{pageIndex:0,paragraphId:p.id,originalBox:p.box,originalRotation:p.rotation??0,originalText,text:originalText.replace('bold','fold')}),after=await inspectEditablePage(edited.bytes,0);const multi=await editPdfParagraph(bytes,{pageIndex:0,paragraphId:p.id,originalBox:p.box,originalRotation:p.rotation??0,originalText,text:originalText.replace('Alpha','alpha').replace('omega','Omega')}),multiModel=await inspectEditablePage(multi.bytes,0);return {before:p.runs,after:after.paragraphs.flatMap(p=>p.runs),multi:multiModel.paragraphs.flatMap(p=>p.runs)};},mixedBytes);
 const assertStyle=(runs,phrase,bold)=>{const chars=runs.flatMap(run=>Array.from(run.text,char=>({char,bold:run.bold}))),joined=chars.map(c=>c.char).join(''),index=joined.indexOf(phrase);assert.ok(index>=0,`readback contains ${phrase}: ${joined}`);assert.ok(chars.slice(index,index+phrase.length).every(c=>c.bold===bold),`${phrase} preserves ${bold?'bold':'regular'} across run fragments`);};
 assertStyle(mixed.multi,'bold',true);assertStyle(mixed.multi,'alpha',false);assertStyle(mixed.multi,'Omega',false);
 assertStyle(mixed.after,'fold',true);assertStyle(mixed.after,'omega',false);assertStyle(mixed.after,'Alpha',false);
 const restricted=new mupdf.PDFDocument(new Uint8Array(input)),trailer=restricted.getTrailer(),catalog=trailer.get('Root');catalog.put('StructTreeRoot',{});const restrictedBuffer=restricted.saveToBuffer(),restrictedBytes=Array.from(restrictedBuffer.asUint8Array());restrictedBuffer.destroy();catalog.destroy();trailer.destroy();restricted.destroy();
 const restrictedCodes=await page.evaluate(async input=>{const api=await import('/src/pdf-text-editor.js'),source=new Uint8Array(input),codes=[];for(const action of [()=>api.inspectEditablePage(source,0),()=>api.editPdfParagraph(source,{pageIndex:0,paragraphId:2,originalText:'old',text:'new'})]){try{await action();codes.push('accepted');}catch(e){codes.push(e.code);}}return codes;},restrictedBytes);assert.deepEqual(restrictedCodes,['EDIT_DOCUMENT_RESTRICTED','EDIT_DOCUMENT_RESTRICTED']);
 for(const bytes of [result.bytes,result.retry]){const task=getDocument({data:new Uint8Array(bytes)});try{const pdf=await task.promise,content=await(await pdf.getPage(1)).getTextContent(),text=content.items.map(i=>i.str+(i.hasEOL?' ':'')).join('').replace(/\s+/g,' ');assert.match(text,/Meet at the orchard gate/);assert.doesNotMatch(text,/Start at the orchard gate/);assert.equal(pdf.numPages,3);}finally{await task.destroy();}}
});
