import test from 'node:test';import assert from 'node:assert/strict';import {spawn} from 'node:child_process';import path from 'node:path';import puppeteer from 'puppeteer-core';import {getDocument} from 'pdfjs-dist/legacy/build/pdf.mjs';import {root} from './validate.mjs';import {selectPdfQuote} from './pdf-selection-helpers.mjs';
test('Edit recovers persistence, cancels stale reviews and preserves outside marks while refusing intersections',{timeout:120000},async t=>{
 const server=spawn(process.execPath,[path.join(root,'node_modules/vite/bin/vite.js'),'--host','127.0.0.1','--port','5099','--strictPort'],{cwd:root,stdio:'ignore'});t.after(()=>server.kill());const url='http://127.0.0.1:5099';for(let i=0;i<100;i++){try{if((await fetch(url)).ok)break;}catch{}await new Promise(r=>setTimeout(r,100));}
 const browser=await puppeteer.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});t.after(()=>browser.close());const page=await browser.newPage();await page.setViewport({width:1280,height:1000});await page.evaluateOnNewDocument(()=>{localStorage.setItem('jt.welcomed','1');localStorage.setItem('jt.mic','off');});await page.goto(url);await page.waitForFunction(()=>window.__jtApp?.booted);await(await page.$('#home-file-input')).uploadFile(path.join(root,'test/fixtures/jett-range.pdf'));await page.waitForFunction(()=>document.querySelectorAll('.pdf-page').length===3);const sourceId=await page.evaluate(()=>window.__jtApp.currentDoc().id);
 await page.locator('[data-workspace="annotate"]').click();await selectPdfQuote(page,'Before the range begins',0,1);await page.locator('[data-annotation="highlight"]').click();await page.waitForFunction(()=>window.__jtApp.entries().some(e=>e.act==='highlight'));
 await page.locator('[data-workspace="edit"]').click();await page.locator('#pdf-edit-load').click();await page.waitForFunction(()=>document.querySelector('#pdf-edit-paragraph').options.length>1);const value=await page.$eval('#pdf-edit-paragraph',n=>[...n.options].find(o=>o.textContent.includes('Start at the orchard gate')).value);await page.select('#pdf-edit-paragraph',value);
 await page.evaluate(()=>{window.editPut=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(...args){if(this.name==='docs'&&args[0]?.textEditDraft)throw new DOMException('Injected draft write failure','QuotaExceededError');return window.editPut.apply(this,args);};});await page.locator('#pdf-edit-text').fill('Meet at the orchard gate.');await page.waitForFunction(()=>document.getElementById('pdf-edit-status').textContent.includes('could not be saved'));assert.equal(await page.$eval('#pdf-edit-review',n=>n.disabled),true);assert.equal(await page.evaluate(async id=>(await(await import('/src/db.js')).getDoc(id)).textEditDraft??null,sourceId),null);
 await page.locator('[data-workspace="read"]').click();assert.equal(await page.evaluate(()=>document.body.dataset.readerWorkspace),'edit');await page.evaluate(()=>{IDBObjectStore.prototype.put=window.editPut;});await page.locator('#pdf-edit-retry').click();await page.waitForFunction(()=>document.getElementById('pdf-edit-status').textContent.startsWith('Draft saved'));
 async function holdReview(){await page.evaluate(async()=>{const {PdfEngine}=await import('/vendor/bento-editcore/core.js');const original=PdfEngine.create;window.editHeld=false;window.editFinished=false;PdfEngine.create=async function(){PdfEngine.create=original;window.editHeld=true;await new Promise(resolve=>window.releaseEdit=resolve);const engine=await original.call(this),close=engine.close;engine.close=function(){try{return close.call(this);}finally{window.editFinished=true;}};return engine;};});await page.locator('#pdf-edit-review').click();await page.waitForFunction(()=>window.editHeld);}
 await holdReview();await page.locator('[data-workspace="read"]').click();await page.evaluate(()=>window.releaseEdit());await page.waitForFunction(()=>window.editFinished);await page.locator('[data-workspace="edit"]').click();await page.waitForFunction(()=>!document.getElementById('pdf-edit-review').disabled);assert.equal(await page.$eval('#pdf-review-dialog',n=>n.open),false);assert.equal(await page.$eval('#pdf-edit-text',n=>n.value),'Meet at the orchard gate.');
 await page.locator('#pdf-edit-review').click();await page.waitForFunction(()=>document.getElementById('pdf-review-dialog').open&&!document.getElementById('pdf-review-save').disabled,{timeout:30000}).catch(async e=>{throw new Error(e.message+' '+await page.$eval('#pdf-edit-status',n=>n.textContent));});await page.locator('#pdf-review-save').click();await page.waitForFunction(()=>!document.getElementById('pdf-review-dialog').open);const copy=await page.evaluate(async sourceId=>{const docs=await(await import('/src/db.js')).getDocs(),d=docs.find(d=>d.provenance?.derivedFrom?.documentId===sourceId);return {id:d.id,bytes:Array.from(d.sourceBytes)};},sourceId);
 const pdfTask=getDocument({data:new Uint8Array(copy.bytes)});try{const pdf=await pdfTask.promise,annotations=await(await pdf.getPage(1)).getAnnotations();assert.equal(annotations.filter(a=>a.subtype==='Highlight').length,1);assert.ok(annotations.find(a=>a.subtype==='Highlight').quadPoints.length);}finally{await pdfTask.destroy();}
 await page.locator(`[role="tab"][data-document-id="${sourceId}"]`).click();await page.locator('[data-workspace="edit"]').click();await holdReview();await page.locator(`[role="tab"][data-document-id="${copy.id}"]`).click();await page.evaluate(()=>window.releaseEdit());await page.waitForFunction(()=>window.editFinished);await page.waitForFunction(id=>window.__jtApp.currentDoc().id===id,{},copy.id);assert.equal(await page.$eval('#pdf-review-dialog',n=>n.open),false);
 await page.locator(`[role="tab"][data-document-id="${sourceId}"]`).click();await page.locator('[data-workspace="annotate"]').click();await selectPdfQuote(page,'Start at the orchard gate',0,1);await page.locator('[data-annotation="underline"]').click();await page.waitForFunction(()=>window.__jtApp.entries().some(e=>e.act==='underline'));await page.locator('[data-workspace="edit"]').click();await page.locator('#pdf-edit-review').click();await page.waitForFunction(()=>document.getElementById('pdf-edit-status').textContent.includes('could not be created'),{timeout:30000});assert.equal(await page.$eval('#pdf-review-dialog',n=>n.open),false);assert.equal(await page.$eval('#pdf-edit-text',n=>n.value),'Meet at the orchard gate.');assert.match(await page.$eval('#pdf-edit-status',n=>n.textContent),/touches a saved mark or note/);
});
