import test from'node:test';import assert from'node:assert/strict';import{readFileSync}from'node:fs';import * as m from'mupdf';import{getDocument}from'pdfjs-dist/legacy/build/pdf.mjs';import{extractPdfPages,inspectPdfExtraction}from'../src/pdf-extract.js';
const plain=new Uint8Array(readFileSync(new URL('./fixtures/jett-annotations.pdf',import.meta.url))),forms=new Uint8Array(readFileSync(new URL('./fixtures/jett-fillable.pdf',import.meta.url)));
function edit(bytes,fn,options={}){const doc=new m.PDFDocument(bytes.slice());doc.disableJS();try{fn(doc);const buffer=doc.saveToBuffer(options);try{return new Uint8Array(buffer.asUint8Array());}finally{buffer.destroy();}}finally{doc.destroy();}}
async function read(bytes){const task=getDocument({data:bytes.slice(),standardFontDataUrl:new URL('../node_modules/pdfjs-dist/standard_fonts/',import.meta.url).pathname});try{const pdf=await task.promise,result=[];for(let i=1;i<=pdf.numPages;i++){const page=await pdf.getPage(i);result.push({text:(await page.getTextContent()).items.map(v=>v.str??'').join('|'),view:page.view,rotate:page.rotate,annotations:(await page.getAnnotations()).map(v=>({type:v.subtype,rect:v.rect,contents:v.contentsObj?.str}))});}return result;}finally{await task.destroy();}}
test('native extraction preserves selected rotated and blank pages in requested order, removing omitted content',async()=>{const source=plain.slice(),before=await read(plain);assert.deepEqual(await inspectPdfExtraction(plain),{allowed:true,reason:null});const output=await extractPdfPages(plain,[2,0]);assert.deepEqual(await read(output),[before[2],before[0]]);assert.deepEqual(plain,source);assert.ok(!(await read(output)).some(p=>p.text.includes('The orchard is ready.')));assert.deepEqual(await read(await extractPdfPages(plain,[1])),[before[1]]);});
test('saved simple native notes/highlights survive on selected pages',async()=>{const marked=edit(plain,doc=>{const page=doc.loadPage(1),note=page.createAnnotation('Text'),highlight=page.createAnnotation('Highlight');try{note.setContents('Extracted नमस्ते');note.setName('extract-note');note.setRect([20,20,40,40]);highlight.setQuadPoints([[48,90,160,90,48,108,160,108]]);highlight.setName('extract-highlight');page.update();}finally{note.destroy();highlight.destroy();page.destroy();}});assert.deepEqual(await inspectPdfExtraction(marked),{allowed:true,reason:null});const before=await read(marked),output=await extractPdfPages(marked,[1]);assert.deepEqual(await read(output),[before[1]]);});
test('empty/duplicate/out-of-bounds/sparse/fractional selections fail without modifying original',async()=>{for(const selected of[[],[1,1],[3],[-1],[1.2],new Array(2),null])await assert.rejects(extractPdfPages(plain,selected),/EXTRACT_INVALID_SELECTION/);await assert.rejects(extractPdfPages(new Array(2),[0]),/EXTRACT_INVALID_BYTES/);});
test('forms, navigation, page actions and links are refused during preflight',async()=>{assert.equal((await inspectPdfExtraction(forms)).allowed,false);for(const kind of['Outlines','Names','StructTreeRoot','PageLabels','action','link']){const bytes=edit(plain,doc=>{const trailer=doc.getTrailer(),root=trailer.get('Root'),page=doc.loadPage(0),object=page.getObject();try{if(kind==='action')object.put('AA',{});else if(kind==='link'){const name=doc.newName('Link');try{object.put('Annots',[{Subtype:name,Rect:[0,0,10,10]}]);}finally{name.destroy();}}else root.put(kind,{});}finally{object.destroy();page.destroy();root.destroy();trailer.destroy();}});assert.equal((await inspectPdfExtraction(bytes)).allowed,false);await assert.rejects(extractPdfPages(bytes,[0]),/EXTRACT_STRUCTURE_UNSUPPORTED/);}});
test('protected documents and assembly denial refuse extraction',async()=>{const encrypted=edit(plain,()=>{},{encrypt:'aes-256','owner-password':'owner','user-password':''});assert.equal((await inspectPdfExtraction(encrypted)).reason,'EXTRACT_DOCUMENT_RESTRICTED');const permission=m.PDFDocument.prototype.hasPermission;m.PDFDocument.prototype.hasPermission=()=>false;try{assert.equal((await inspectPdfExtraction(plain)).reason,'EXTRACT_PERMISSION_DENIED');await assert.rejects(extractPdfPages(plain,[0]),/EXTRACT_PERMISSION_DENIED/);}finally{m.PDFDocument.prototype.hasPermission=permission;}});
test('unchanged serialized source is rejected as extraction output',async()=>{const save=m.PDFDocument.prototype.saveToBuffer;m.PDFDocument.prototype.saveToBuffer=()=>new m.Buffer(plain);try{await assert.rejects(extractPdfPages(plain,[2,0]),/EXTRACT_CONTENT_CHANGED/);}finally{m.PDFDocument.prototype.saveToBuffer=save;}});
test('selected Text/Popup parent links and annotation page ownership survive object renumbering',async()=>{
 const bytes=edit(plain,doc=>{const page=doc.loadPage(1),object=page.getObject(),text=doc.addObject({}),popup=doc.addObject({}),textName=doc.newName('Text'),popupName=doc.newName('Popup'),contents=doc.newString('Parent note');try{text.put('Subtype',textName);text.put('Rect',[20,20,40,40]);text.put('Contents',contents);text.put('Popup',popup);text.put('P',object);popup.put('Subtype',popupName);popup.put('Rect',[50,50,220,150]);popup.put('Parent',text);popup.put('P',object);object.put('Annots',[text,popup]);}finally{for(const value of[contents,popupName,textName,popup,text,object,page])value.destroy();}});
 assert.equal((await inspectPdfExtraction(bytes)).allowed,true);const output=await extractPdfPages(bytes,[1]),doc=new m.PDFDocument(output);try{const page=doc.loadPage(0),object=page.getObject(),annots=object.get('Annots'),note=annots.get(0),popup=annots.get(1),notePage=note.get('P'),popupPage=popup.get('P'),parent=popup.get('Parent'),child=note.get('Popup');try{assert.equal(notePage.asIndirect(),object.asIndirect());assert.equal(popupPage.asIndirect(),object.asIndirect());assert.equal(parent.asIndirect(),note.asIndirect());assert.equal(child.asIndirect(),popup.asIndirect());}finally{for(const v of[child,parent,popupPage,notePage,popup,note,annots,object,page])v.destroy();}}finally{doc.destroy();}
 assert.deepEqual(await read(output),[(await read(bytes))[1]]);
});
