import test from 'node:test';import assert from 'node:assert/strict';import {spawn} from 'node:child_process';import {mkdtemp,writeFile,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import path from 'node:path';import * as m from 'mupdf';import puppeteer from 'puppeteer-core';import {root} from './validate.mjs';
for(const rotation of [0,90,180,270,45])test(`real cropped UserUnit PDF at rotation ${rotation} targets rendered ink and saves exact edits`,{timeout:60000},async t=>{
 const directory=await mkdtemp(path.join(tmpdir(),'jett-transform-'));t.after(()=>rm(directory,{recursive:true,force:true}));const file=path.join(directory,'transformed.pdf'),doc=new m.PDFDocument(),font=new m.Font('Helvetica'),ref=doc.addSimpleFont(font);let object,buffer;
 try{object=doc.addPage([0,0,400,500],rotation===45?0:rotation,{Font:{F1:ref}},rotation===45?'BT /F1 16 Tf 0.70710678 0.70710678 -0.70710678 0.70710678 70 180 Tm (Crop rotation unit proof.) Tj ET 1 0 0 rg 75 280 4 4 re f':'BT /F1 16 Tf 70 330 Td (Crop rotation unit proof.) Tj ET');doc.insertPage(-1,object);object.put('CropBox',[30,40,370,470]);object.put('UserUnit',2);buffer=doc.saveToBuffer();await writeFile(file,buffer.asUint8Array());}finally{buffer?.destroy();object?.destroy();ref.destroy();font.destroy();doc.destroy();}
 const server=spawn(process.execPath,[path.join(root,'node_modules/vite/bin/vite.js'),'--host','127.0.0.1','--port','5102','--strictPort'],{cwd:root,stdio:'ignore'});t.after(()=>server.kill());const url='http://127.0.0.1:5102';for(let i=0;i<100;i++){try{if((await fetch(url)).ok)break;}catch{}await new Promise(r=>setTimeout(r,100));}
 const browser=await puppeteer.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});t.after(()=>browser.close());const page=await browser.newPage();await page.setViewport({width:1280,height:1000});await page.evaluateOnNewDocument(()=>{localStorage.setItem('jt.welcomed','1');localStorage.setItem('jt.mic','off');});await page.goto(url);await page.waitForFunction(()=>window.__jtApp?.booted);await(await page.$('#home-file-input')).uploadFile(file);await page.waitForFunction(()=>document.body.dataset.view==='read'&&document.querySelector('.pdf-canvas'));
 await page.locator('[data-workspace="edit"]').click();await page.locator('#pdf-edit-load').click();await page.waitForFunction(()=>document.querySelector('.pdf-edit-target')||!document.querySelector('#pdf-edit-load').disabled,{timeout:30000});const status=await page.$eval('#pdf-edit-status',n=>n.textContent);assert.ok(await page.$('.pdf-edit-target'),status+' '+JSON.stringify(await page.evaluate(async()=>{const {inspectEditablePage}=await import('/src/pdf-text-editor.js');return inspectEditablePage(new Uint8Array(window.__jtApp.currentDoc().sourceBytes),0);})));
 const hit=await page.evaluate(()=>{const button=document.querySelector('.pdf-edit-target'),b=button.getBoundingClientRect(),spans=[...document.querySelectorAll('.pdf-text-layer [data-pdf-char-start]')].filter(n=>n.textContent.trim());return {label:button.getAttribute('aria-label'),target:{left:b.left,top:b.top,right:b.right,bottom:b.bottom},text:spans.map(n=>{const r=n.getBoundingClientRect();return {text:n.textContent,x:(r.left+r.right)/2,y:(r.top+r.bottom)/2};})};});const ink=await page.$eval('.pdf-canvas',canvas=>{const {width,height}=canvas,data=canvas.getContext('2d').getImageData(0,0,width,height).data;let left=width,top=height,right=0,bottom=0;for(let y=0;y<height;y++)for(let x=0;x<width;x++){const i=(y*width+x)*4;if(data[i]<100&&data[i+1]<100&&data[i+2]<100){left=Math.min(left,x);right=Math.max(right,x);top=Math.min(top,y);bottom=Math.max(bottom,y);}}const r=canvas.getBoundingClientRect();return {x:r.left+(left+right)/2*r.width/width,y:r.top+(top+bottom)/2*r.height/height};});assert.ok(hit.text.length,JSON.stringify(hit));for(const point of [ink])assert.ok(point.x>=hit.target.left-1&&point.x<=hit.target.right+1&&point.y>=hit.target.top-1&&point.y<=hit.target.bottom+1,JSON.stringify({hit,point}));
 await page.locator('.pdf-edit-target').click();assert.equal(await page.$eval('#pdf-edit-text',n=>n.value),'Crop rotation unit proof.');assert.equal(await page.$eval('.pdf-edit-target',n=>n.getAttribute('aria-pressed')),'true');
 await page.locator('#pdf-edit-text').fill('Crop rotation unit test.');await page.waitForFunction(()=>document.getElementById('pdf-edit-status').textContent.startsWith('Draft saved'));await page.locator('#pdf-edit-review').click();await page.waitForFunction(()=>document.getElementById('pdf-review-dialog').open||document.getElementById('pdf-edit-status').textContent.includes('could not be created'),{timeout:30000});assert.equal(await page.$eval('#pdf-review-dialog',n=>n.open),true,await page.$eval('#pdf-edit-status',n=>n.textContent));await page.waitForFunction(()=>!document.getElementById('pdf-review-save').disabled);await page.locator('#pdf-review-save').click();await page.waitForFunction(()=>!document.getElementById('pdf-review-dialog').open);assert.match(await page.evaluate(()=>window.__jtApp.currentDoc().text),/Crop rotation unit test/);
});
