import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync}from'node:fs';import * as mupdf from'mupdf';import {getDocument}from'pdfjs-dist/legacy/build/pdf.mjs';
import {reorderPdfPages}from'../src/pdf-reorder.js';import {fillPdfForm,inspectPdfForm}from'../src/pdf-forms.js';
const plain=new Uint8Array(readFileSync(new URL('./fixtures/jett-annotations.pdf',import.meta.url))),forms=new Uint8Array(readFileSync(new URL('./fixtures/jett-fillable.pdf',import.meta.url)));
function edit(bytes,fn,options={}){const doc=new mupdf.PDFDocument(bytes.slice());doc.disableJS();try{fn(doc);const buffer=doc.saveToBuffer(options);try{return new Uint8Array(buffer.asUint8Array());}finally{buffer.destroy();}}finally{doc.destroy();}}
async function read(bytes){const task=getDocument({data:bytes.slice(),standardFontDataUrl:new URL('../node_modules/pdfjs-dist/standard_fonts/',import.meta.url).pathname});try{const pdf=await task.promise,pages=[];for(let i=1;i<=pdf.numPages;i++){const page=await pdf.getPage(i),text=await page.getTextContent(),annotations=await page.getAnnotations();pages.push({text:text.items.filter(i=>'str'in i).map(i=>i.str).join('|'),view:page.view,rotate:page.rotate,annotations:annotations.map(a=>({subtype:a.subtype,contents:a.contentsObj?.str??'',rect:a.rect,fieldName:a.fieldName,fieldValue:a.fieldValue}))});}return {pages,fields:await pdf.getFieldObjects()};}finally{await task.destroy();}}
test('complete permutation preserves physical page content and rotated geometry with independent PDF.js readback',async()=>{
 const original=plain.slice(),before=await read(plain),order=[2,0,1];const output=await reorderPdfPages(plain,order),after=await read(output);
 assert.deepEqual(plain,original);assert.deepEqual(after.pages,order.map(i=>before.pages[i]));assert.deepEqual(await reorderPdfPages(plain,[0,1,2]),plain);
});
test('filled forms and existing annotations remain on their original pages after reorder',async()=>{
 const schema=await inspectPdfForm(forms),key=schema.fields.find(f=>f.name==='full_name').key;const filled=await fillPdfForm(forms,{[key]:'Reordered reader'});
 const marked=edit(filled,doc=>{const page=doc.loadPage(0),note=page.createAnnotation('Text');try{note.setName('reorder-note');note.setContents('Unicode नमस्ते\nOriginal page one');note.setRect([20,20,40,40]);page.update();}finally{note.destroy();page.destroy();}});
 const original=marked.slice(),before=await read(marked);const output=await reorderPdfPages(marked,[1,0]),after=await read(output);
 assert.deepEqual(marked,original);assert.deepEqual(after.pages,[before.pages[1],before.pages[0]]);assert.equal(after.fields.full_name[0].value,'Reordered reader');
 assert.equal((await inspectPdfForm(output)).fields.find(f=>f.name==='full_name').value,'Reordered reader');
});
test('missing, duplicate, fractional, sparse and out-of-bounds page orders fail before mutation',async()=>{
 for(const order of [[],[0,1],[0,1,1],[0,1,3],[0,1,-1],[0,1,2.5],new Array(3),null])await assert.rejects(reorderPdfPages(plain,order),/REORDER_INVALID_ORDER/);
 await assert.rejects(reorderPdfPages(new Array(3),[0]),/REORDER_INVALID_BYTES/);
});
test('protected, encrypted, dynamic and unverified advanced structures fail closed',async()=>{
 for(const key of ['Perms','XFA','CO','PageLabels','Outlines','Names','StructTreeRoot','Dests','OpenAction']){
 const modified=edit(forms,doc=>{const trailer=doc.getTrailer(),root=trailer.get('Root'),form=root.get('AcroForm');try{if(key==='XFA')form.put(key,'dynamic');else if(key==='CO')form.put(key,[1]);else root.put(key,{});}finally{form.destroy();root.destroy();trailer.destroy();}});
 await assert.rejects(reorderPdfPages(modified,[1,0]),/REORDER_(DOCUMENT_RESTRICTED|ADVANCED_STRUCTURE_UNSUPPORTED)/);
 }
 const encrypted=edit(forms,()=>{},{encrypt:'aes-256','owner-password':'owner','user-password':''});await assert.rejects(reorderPdfPages(encrypted,[1,0]),/REORDER_DOCUMENT_RESTRICTED/);
});
test('reopened unchanged or corrupted output cannot masquerade as a successful reorder',async()=>{
 const save=mupdf.PDFDocument.prototype.saveToBuffer;mupdf.PDFDocument.prototype.saveToBuffer=function(){return new mupdf.Buffer(plain);};
 try{await assert.rejects(reorderPdfPages(plain,[2,0,1]),/REORDER_CONTENT_CHANGED/);}finally{mupdf.PDFDocument.prototype.saveToBuffer=save;}
});

test('assembly denial and populated signature fields reject reordering',async()=>{
 const permission=mupdf.PDFDocument.prototype.hasPermission;mupdf.PDFDocument.prototype.hasPermission=function(name){return name!=='assemble';};
 try{await assert.rejects(reorderPdfPages(plain,[2,0,1]),/REORDER_PERMISSION_DENIED/);}finally{mupdf.PDFDocument.prototype.hasPermission=permission;}
 const signed=edit(forms,doc=>{const trailer=doc.getTrailer(),root=trailer.get('Root'),form=root.get('AcroForm'),fields=form.get('Fields'),sig=doc.newDictionary(),name=doc.newName('Sig');try{sig.put('FT',name);sig.put('V',{ByteRange:[0,10,20,30]});fields.push(sig);}finally{for(const object of [name,sig,fields,form,root,trailer])object.destroy();}});
 await assert.rejects(reorderPdfPages(signed,[1,0]),/REORDER_DOCUMENT_RESTRICTED/);
});

async function outlineRead(bytes){const task=getDocument({data:bytes.slice(),standardFontDataUrl:new URL('../node_modules/pdfjs-dist/standard_fonts/',import.meta.url).pathname});try{const pdf=await task.promise;async function walk(nodes){return Promise.all((nodes??[]).map(async node=>{let target=null;if(node.dest){const index=typeof node.dest[0]==='number'?node.dest[0]:await pdf.getPageIndex(node.dest[0]);const page=await pdf.getPage(index+1);target={index,text:(await page.getTextContent()).items.filter(i=>'str'in i).map(i=>i.str).join('|'),tail:node.dest.slice(1)};}return {title:node.title,bold:node.bold,italic:node.italic,color:Array.from(node.color),count:node.count,target,items:await walk(node.items)};}));}return await walk(await pdf.getOutline());}finally{await task.destroy();}}
function outlined(){return edit(plain,doc=>{const held=[],keep=v=>(held.push(v),v),trailer=doc.getTrailer(),root=trailer.get('Root'),page=doc.loadPage(2);try{const outlines=keep(doc.addObject({Count:2})),first=keep(doc.addObject({Count:-1,F:3,C:[0.2,0.4,0.6]})),child=keep(doc.addObject({})),second=keep(doc.addObject({}));first.put('Title',keep(doc.newString('नमस्ते — nested')));child.put('Title',keep(doc.newString('Child ☀')));second.put('Title',keep(doc.newString('Numeric destination')));first.put('Parent',outlines);child.put('Parent',first);second.put('Parent',outlines);first.put('First',child);first.put('Last',child);first.put('Next',second);second.put('Prev',first);outlines.put('First',first);outlines.put('Last',second);const pageObj=keep(page.getObject()),xyz=keep(doc.newName('XYZ')),fitH=keep(doc.newName('FitH'));first.put('Dest',[pageObj,xyz,10,420,1.25]);child.put('A',{S:keep(doc.newName('GoTo')),D:[1,fitH,650]});second.put('Dest',[2,xyz,null,490,null]);root.put('Outlines',outlines);}finally{held.reverse().forEach(v=>v.destroy());page.destroy();root.destroy();trailer.destroy();}});}
test('nested collapsed Unicode bookmarks preserve styles and direct/numeric destination content and coordinates',async()=>{
 const {inspectPdfReorder}=await import('../src/pdf-reorder.js');const input=outlined(),copy=input.slice(),before=await outlineRead(input),order=[2,0,1];
 assert.deepEqual(await inspectPdfReorder(input),{allowed:true,reason:null});const output=await reorderPdfPages(input,order),after=await outlineRead(output);assert.deepEqual(input,copy);
 const remap=nodes=>nodes.map(node=>({...node,target:node.target&&{...node.target,index:order.indexOf(node.target.index)},items:remap(node.items)}));assert.deepEqual(after,remap(before));assert.equal(after[0].title,'नमस्ते — nested');assert.equal(after[0].count,-1);assert.equal(after[0].items[0].target.index,2);assert.equal(after[1].target.index,0);
});
test('unsupported destinations/actions and malformed outline cycles are unavailable before mutation',async()=>{
 const {inspectPdfReorder}=await import('../src/pdf-reorder.js');for(const mode of ['named','external','cycle','bad-parent','bad-mode','bad-count']){const input=edit(outlined(),doc=>{const trailer=doc.getTrailer(),root=trailer.get('Root'),tree=root.get('Outlines'),first=tree.get('First');try{if(mode==='named'){const name=doc.newString('chapter');try{first.put('Dest',name);}finally{name.destroy();}}if(mode==='external'){first.delete('Dest');const name=doc.newName('URI');try{first.put('A',{S:name,URI:'https://example.com'});}finally{name.destroy();}}if(mode==='bad-count')first.put('Count',-200);if(mode==='cycle')first.put('Next',first);if(mode==='bad-parent')first.put('Parent',first);if(mode==='bad-mode'){const name=doc.newName('XYZ');try{first.put('Dest',[0,name,10]);}finally{name.destroy();}}}finally{first.destroy();tree.destroy();root.destroy();trailer.destroy();}});assert.deepEqual(await inspectPdfReorder(input),{allowed:false,reason:'REORDER_ADVANCED_STRUCTURE_UNSUPPORTED'});await assert.rejects(reorderPdfPages(input,[2,0,1]),/REORDER_ADVANCED_STRUCTURE_UNSUPPORTED/);}
});
test('serialized bookmark loss fails semantic readback even when reordered pages survive',async()=>{
 const input=outlined(),save=mupdf.PDFDocument.prototype.saveToBuffer;
 mupdf.PDFDocument.prototype.saveToBuffer=function(...args){const buffer=save.apply(this,args);let doc;try{doc=new mupdf.PDFDocument(new Uint8Array(buffer.asUint8Array()));doc.disableJS();const trailer=doc.getTrailer(),root=trailer.get('Root');try{root.delete('Outlines');return save.call(doc);}finally{root.destroy();trailer.destroy();}}finally{doc?.destroy();buffer.destroy();}};
 try{await assert.rejects(reorderPdfPages(input,[2,0,1]),/REORDER_CONTENT_CHANGED/);}finally{mupdf.PDFDocument.prototype.saveToBuffer=save;}
});
test('outline title byte limits reject oversized titles and aggregate expansion before reorder',async()=>{
 const {inspectPdfReorder}=await import('../src/pdf-reorder.js');for(const aggregate of[false,true]){const input=edit(outlined(),doc=>{const trailer=doc.getTrailer(),root=trailer.get('Root'),tree=root.get('Outlines'),first=tree.get('First'),held=[];try{if(!aggregate){const title=doc.newByteString(new Uint8Array(65537).fill(65));try{first.put('Title',title);}finally{title.destroy();}}else{first.delete('First');first.delete('Last');first.delete('Count');first.delete('Next');const title=doc.newByteString(new Uint8Array(65536).fill(65));held.push(title);let previous=first;first.put('Title',title);for(let i=1;i<17;i++){const node=doc.addObject({});held.push(node);node.put('Title',title);node.put('Parent',tree);node.put('Prev',previous);previous.put('Next',node);previous=node;}tree.put('Last',previous);tree.put('Count',17);}}finally{held.reverse().forEach(v=>v.destroy());first.destroy();tree.destroy();root.destroy();trailer.destroy();}});assert.equal((await inspectPdfReorder(input)).allowed,false);await assert.rejects(reorderPdfPages(input,[2,0,1]),/REORDER_ADVANCED_STRUCTURE_UNSUPPORTED/);}
});
test('numeric link and page-action targets fail preflight while direct page-reference links preserve target content',async()=>{
 const {inspectPdfReorder}=await import('../src/pdf-reorder.js');for(const mode of['Dest','GoTo','page-action','direct']){const input=edit(plain,doc=>{const page=doc.loadPage(1),object=page.getObject(),targetPage=doc.loadPage(2),targetObject=targetPage.getObject(),fit=doc.newName('Fit'),go=doc.newName('GoTo'),link=doc.addObject({Subtype:doc.newName('Link'),Rect:[40,40,120,60]});try{if(mode==='page-action')object.put('AA',{O:{S:go,D:[2,fit]}});else{if(mode==='GoTo')link.put('A',{S:go,D:[2,fit]});else link.put('Dest',[mode==='direct'?targetObject:2,fit]);object.put('Annots',[link]);}}finally{for(const value of[link,go,fit,targetObject,targetPage,object,page])value.destroy();}});
 if(mode!=='direct'){assert.equal((await inspectPdfReorder(input)).allowed,false);await assert.rejects(reorderPdfPages(input,[2,0,1]),/REORDER_ADVANCED_STRUCTURE_UNSUPPORTED/);}else{assert.equal((await inspectPdfReorder(input)).allowed,true);const output=await reorderPdfPages(input,[2,0,1]),task=getDocument({data:output});try{const pdf=await task.promise,annotations=await(await pdf.getPage(3)).getAnnotations();assert.equal(annotations.length,1);const target=await pdf.getPageIndex(annotations[0].dest[0]);assert.equal(target,0);const text=await(await pdf.getPage(target+1)).getTextContent();assert.match(text.items.map(i=>i.str).join(' '),/Rotated orchard passage/);}finally{await task.destroy();}}
 }
});
