import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import * as mupdf from 'mupdf';
import {exportFreehandPdf} from '../src/pdf-freehand.js';
const bytes=new Uint8Array(readFileSync(new URL('./fixtures/jett-annotations.pdf',import.meta.url)));
function inspect(raw){const doc=new mupdf.PDFDocument(raw);try{return Array.from({length:doc.countPages()},(_,i)=>{const p=doc.loadPage(i);try{const st=p.toStructuredText();let text;try{text=st.asText();}finally{st.destroy();}return {bounds:p.getBounds(),text,annotations:p.getAnnotations().map(a=>{try{return {type:a.getType(),contents:a.getContents(),ink:a.getType()==='Ink'?a.getInkList():null,rect:a.getBounds(),flags:a.getFlags()};}finally{a.destroy();}})};}finally{p.destroy();}});}finally{doc.destroy();}}
const edits={ink:[{pageIndex:0,points:[[60,100],[75,110],[90,95]],width:2,color:[0.1,0.2,0.3]}],text:[{pageIndex:1,x:60,y:100,text:'Reviewed (draft) \\ signed by hand',fontSize:12}]};
test('adds printable Ink and FreeText across pages, preserves original text and input',async()=>{const original=bytes.slice(),before=inspect(bytes),out=await exportFreehandPdf(bytes,edits),after=inspect(out);assert.ok(out instanceof Uint8Array);assert.deepEqual(bytes,original);assert.equal(after.length,before.length);for(let i=0;i<before.length;i++){assert.equal(after[i].text,before[i].text);assert.deepEqual(after[i].bounds,before[i].bounds);}assert.deepEqual(after[0].annotations[0].ink,[edits.ink[0].points]);assert.equal(after[0].annotations[0].type,'Ink');assert.equal(after[1].annotations[0].type,'FreeText');assert.equal(after[1].annotations[0].contents,edits.text[0].text);assert.ok(after[0].annotations[0].flags&mupdf.PDFAnnotation.IS_PRINT);assert.equal(inspect(bytes)[0].annotations.length,0);});
test('rejects empty, malformed and out of bounds edits',async()=>{for(const input of [{},{ink:[]}, {ink:[{pageIndex:-1,points:[[1,2],[3,4]]}]},{ink:[{pageIndex:99,points:[[1,2],[3,4]]}]},{ink:[{pageIndex:0,points:[[NaN,2],[3,4]]}]},{ink:[{pageIndex:0,points:[[1,2]]}]},{ink:[{pageIndex:0,points:[[1,2],[99999,4]]}]},{ink:[{...edits.ink[0],width:-1}]},{ink:[{...edits.ink[0],color:[2,0,0]}]},{text:[{pageIndex:0,x:5,y:5,text:''}]},{text:[{pageIndex:0,x:5,y:5,text:'Hi',fontSize:Infinity}]}])await assert.rejects(exportFreehandPdf(bytes,input),/FREEHAND_/);await assert.rejects(exportFreehandPdf(new Uint8Array(),edits),/SOURCE/);});
test('supports rotated pages and rejects text that cannot fit',async()=>{const bounds=inspect(bytes)[2].bounds;const out=await exportFreehandPdf(bytes,{ink:[{pageIndex:2,points:[[bounds[0]+30,bounds[1]+30],[bounds[0]+50,bounds[1]+50]]}],text:[{pageIndex:2,x:bounds[0]+30,y:bounds[1]+70,text:'Page three'}]});assert.equal(inspect(out)[2].annotations.length,2);await assert.rejects(exportFreehandPdf(bytes,{text:[{pageIndex:0,x:611,y:791,text:'Does not fit'}]}),/FREEHAND_/);});
test('detects missing serialized output instead of reporting success',async()=>{const save=mupdf.PDFDocument.prototype.saveToBuffer;mupdf.PDFDocument.prototype.saveToBuffer=function(){return new mupdf.Buffer(bytes);};try{await assert.rejects(exportFreehandPdf(bytes,edits),/READBACK/);}finally{mupdf.PDFDocument.prototype.saveToBuffer=save;}});
test('independent PDF.js reader sees original text, printable geometry and escaped text contents',async()=>{const {getDocument}=await import('pdfjs-dist/legacy/build/pdf.mjs');const out=await exportFreehandPdf(bytes,edits);const task=getDocument({data:out.slice(),isEvalSupported:false,useSystemFonts:true});const pdf=await task.promise;try{assert.equal(pdf.numPages,inspect(bytes).length);const first=await pdf.getPage(1),second=await pdf.getPage(2);const ink=(await first.getAnnotations())[0],text=(await second.getAnnotations())[0];assert.equal(ink.subtype,'Ink');assert.equal(ink.inkLists.length,1);assert.equal(ink.inkLists[0].length,6);assert.equal(text.subtype,'FreeText');assert.equal(text.contentsObj.str,edits.text[0].text);assert.ok((await second.getTextContent()).items.some(item=>item.str.includes('orchard')));}finally{await task.destroy();}});
test('retains existing annotations when adding later strokes',async()=>{const first=await exportFreehandPdf(bytes,edits);const next=await exportFreehandPdf(first,{ink:[{pageIndex:0,points:[[60,200],[90,210]]}]});assert.equal(inspect(next)[0].annotations.length,2);assert.equal(inspect(next)[1].annotations[0].contents,edits.text[0].text);});
test('encrypted, certificate-signed and permission denied sources fail closed',async()=>{for(const signed of [false,true]){const pdf=new mupdf.PDFDocument(bytes);let input;try{if(signed){const root=pdf.getTrailer(),form=pdf.newDictionary(),sig=pdf.newDictionary(),value=pdf.newDictionary();try{sig.put('FT',pdf.newName('Sig'));value.put('ByteRange',[0,10,20,30]);sig.put('V',value);form.put('Fields',[sig]);root.get('Root').put('AcroForm',form);}finally{value.destroy();sig.destroy();form.destroy();root.destroy();}}const buffer=pdf.saveToBuffer(signed?{}:{encrypt:'aes-256','owner-password':'test-owner','user-password':''});try{input=new Uint8Array(buffer.asUint8Array());}finally{buffer.destroy();}}finally{pdf.destroy();}const before=input.slice();await assert.rejects(exportFreehandPdf(input,edits),/DOCUMENT_RESTRICTED/);assert.deepEqual(input,before);}const permission=mupdf.PDFDocument.prototype.hasPermission;mupdf.PDFDocument.prototype.hasPermission=function(kind){return kind==='annotate'?false:permission.call(this,kind);};try{await assert.rejects(exportFreehandPdf(bytes,edits),/PERMISSION_DENIED/);}finally{mupdf.PDFDocument.prototype.hasPermission=permission;}});
test('FreeText has a readable saved appearance, including multiline content',async()=>{const value='First line\nSecond line';const output=await exportFreehandPdf(bytes,{text:[{pageIndex:1,x:60,y:250,text:value,fontSize:16}]});const doc=new mupdf.PDFDocument(output),page=doc.loadPage(1),annotations=page.getAnnotations();try{const display=annotations[0].toDisplayList();try{const structured=display.toStructuredText();try{assert.match(structured.asText(),/First line\s+Second line/);}finally{structured.destroy();}}finally{display.destroy();}}finally{annotations.forEach(a=>a.destroy());page.destroy();doc.destroy();}});
