import {mkdir}from'node:fs/promises';import test from 'node:test';import assert from 'node:assert/strict';import {spawn}from'node:child_process';import path from'node:path';import puppeteer from'puppeteer-core';import {root}from'./validate.mjs';import {openReaderView} from './reader-navigation.mjs';
test('direct PDF paragraph targets follow fitted pages and preserve the chosen draft through zoom and responsive layout',{timeout:90000},async t=>{
 const server=spawn(process.execPath,[path.join(root,'node_modules/vite/bin/vite.js'),'--host','127.0.0.1','--port','5101','--strictPort'],{cwd:root,stdio:'ignore'});t.after(()=>server.kill());const url='http://127.0.0.1:5101';for(let i=0;i<100;i++){try{if((await fetch(url)).ok)break;}catch{}await new Promise(r=>setTimeout(r,100));}
 const browser=await puppeteer.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});t.after(()=>browser.close());const page=await browser.newPage();await page.setViewport({width:1280,height:1000});await page.evaluateOnNewDocument(()=>{localStorage.setItem('jt.welcomed','1');localStorage.setItem('jt.mic','off');});const main=await(await fetch(url+'/src/main.js')).text(),anchor='source.blocks = blocks;\n    await engine.load(state.doc.id);';assert.equal(main.split(anchor).length-1,1);await page.setRequestInterception(true);page.on('request',r=>r.url()===url+'/src/main.js'?r.respond({status:200,contentType:'text/javascript',body:main.replace(anchor,'source.blocks = blocks;\n    if(window.__editFitGate)await window.__editFitGate();\n    await engine.load(state.doc.id);')}):r.continue());await page.goto(url);await page.waitForFunction(()=>window.__jtApp?.booted);await(await page.$('#home-file-input')).uploadFile(path.join(root,'test/fixtures/jett-range.pdf'));await page.waitForFunction(()=>document.querySelectorAll('.pdf-page').length===3&&document.body.dataset.view==='read');
 await page.locator('[data-workspace="edit"]').click();await page.locator('#pdf-edit-load').click();await page.waitForFunction(()=>document.querySelectorAll('.pdf-edit-target').length===3,{timeout:30000});
 const target='.pdf-edit-target[aria-label*="Start at the orchard gate"]';
 const rects=await page.evaluate(()=>{const p=document.querySelector('.pdf-page').getBoundingClientRect(),editor=document.getElementById('reader-workspace-panel').getBoundingClientRect();return {pageRight:p.right,editorLeft:editor.left,pageTop:p.top,editorTop:editor.top};});assert.ok(rects.pageRight<=rects.editorLeft,'editor sits beside the page');assert.ok(Math.abs(rects.pageTop-rects.editorTop)<30);
 await page.locator(target).click();assert.equal(await page.evaluate(()=>document.activeElement.id),'pdf-edit-text');assert.match(await page.$eval('#pdf-edit-text',n=>n.value),/Start at the orchard gate/);assert.equal(await page.$eval(target,n=>n.getAttribute('aria-pressed')),'true');await page.locator('#pdf-edit-text').fill('Meet at the orchard gate.');await page.waitForFunction(()=>document.getElementById('pdf-edit-status').textContent.startsWith('Draft saved'));
 if(process.env.JETT_TARGET_EVIDENCE_DIR){await mkdir(process.env.JETT_TARGET_EVIDENCE_DIR,{recursive:true});await page.screenshot({path:path.join(process.env.JETT_TARGET_EVIDENCE_DIR,'desktop.png')});}
 await page.locator('#pdf-zoom-out').click();await page.waitForFunction(()=>document.querySelector('.pdf-edit-target[aria-pressed="true"]')&&!document.getElementById('pdf-zoom-out').disabled);assert.equal(await page.$eval('#pdf-edit-text',n=>n.value),'Meet at the orchard gate.');
 await page.setViewport({width:390,height:844});await new Promise(r=>setTimeout(r,600));assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 const mobile=await page.evaluate(()=>{const p=document.getElementById('reader-workspace-panel').getBoundingClientRect();return {top:p.top,bottom:p.bottom,chrome:document.getElementById('reader-chrome').getBoundingClientRect().bottom};});assert.ok(mobile.top-mobile.chrome>200,'bottom editor retains visible document space');assert.ok(mobile.bottom<=844);await openReaderView(page,'#pdf-fit-width');await page.locator('#pdf-fit-width').click();await page.waitForFunction(()=>!document.getElementById('pdf-fit-width').disabled);await page.keyboard.press('Escape');if(process.env.JETT_TARGET_EVIDENCE_DIR)await page.screenshot({path:path.join(process.env.JETT_TARGET_EVIDENCE_DIR,'phone.png')});
 await page.locator('#pdf-edit-review').click();await page.waitForFunction(()=>document.getElementById('pdf-review-dialog').open&&!document.getElementById('pdf-review-save').disabled,{timeout:30000});await page.locator('#pdf-review-close').click();
 await page.reload();await page.waitForFunction(()=>window.__jtApp?.booted&&document.querySelector('.pdf-edit-target[aria-pressed="true"]'),{timeout:30000});assert.equal(await page.$eval('#pdf-edit-text',n=>n.value),'Meet at the orchard gate.');
 await page.locator('#pdf-edit-discard').click();await page.waitForFunction(()=>document.getElementById('pdf-edit-status').textContent==='Draft discarded.');await page.locator('[data-workspace="read"]').click();await page.waitForFunction(()=>!document.querySelector('.pdf-edit-target'));assert.equal(await page.$eval('#reader-workspace-panel',n=>n.hidden),true);
 await page.setViewport({width:1280,height:1000});await new Promise(r=>setTimeout(r,400));await openReaderView(page,'#pdf-fit-width');await page.locator('#pdf-fit-width').click();await page.waitForFunction(()=>!document.getElementById('pdf-fit-width').disabled);
 await page.$eval('.pdf-page[data-page="2"]',n=>scrollBy({top:n.getBoundingClientRect().top+n.getBoundingClientRect().height*.25-document.getElementById('reader-chrome').getBoundingClientRect().bottom-12,behavior:'instant'}));
 await page.waitForFunction(()=>{const s=window.__jtApp.readerSession(),v=s.views[s.activeId];return v.pageNumber===2&&Math.abs(v.pageOffset-.25)<.003;});
 const departure=await page.evaluate(()=>{const s=window.__jtApp.readerSession();return s.views[s.activeId];});
 await page.evaluate(()=>{window.__editFitGate=()=>{delete window.__editFitGate;return new Promise(r=>window.__releaseEditFit=r);};});await page.locator('[data-workspace="edit"]').click();await page.waitForFunction(()=>typeof window.__releaseEditFit==='function');await page.setViewport({width:390,height:844});await page.evaluate(()=>window.__releaseEditFit());
 await page.waitForFunction(()=>{const s=window.__jtApp.readerSession(),v=s.views[s.activeId];return v.workspace==='edit'&&v.pageNumber===2&&Math.abs(v.pageOffset-.25)<.003&&document.querySelector('.pdf-page').getBoundingClientRect().width<=innerWidth;},{timeout:30000});
 const arrived=await page.evaluate(()=>{const s=window.__jtApp.readerSession();return s.views[s.activeId];});assert.deepEqual(arrived.returnPlace,departure.returnPlace,'layout does not create a Return point');
 await page.locator('[data-workspace="read"]').click();await page.setViewport({width:1280,height:1000});await new Promise(r=>setTimeout(r,400));await openReaderView(page,'#pdf-fit-width');await page.locator('#pdf-fit-width').click();
 await page.evaluate(()=>{delete window.__releaseEditFit;window.__editFitGate=async()=>{delete window.__editFitGate;await new Promise(r=>window.__releaseEditFit=r);window.__editFitReleased=true;};});await page.locator('[data-workspace="edit"]').click();await page.waitForFunction(()=>typeof window.__releaseEditFit==='function');await page.evaluate(()=>window.__jtApp.showView('home'));await page.evaluate(()=>window.__releaseEditFit());await page.waitForFunction(()=>window.__editFitReleased&&!document.getElementById('pdf-zoom-out').disabled);assert.equal(await page.evaluate(()=>document.body.dataset.view),'home');assert.equal(await page.$$('.pdf-edit-target').then(n=>n.length),0,'abandoned fit does not reopen page targets');


});
