import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import puppeteer from 'puppeteer-core';import {paragraphTargetRect} from '../src/pdf-edit-targets.js';
const p={id:7,editable:true,box:{x:20,top:80,w:40,h:10},runs:[{text:'Choose this text'}]};
test('paragraph targets apply crop, rotation and UserUnit transforms',()=>{
 assert.deepEqual(paragraphTargetRect(p,{pageBounds:[0,0,100,100],transform:[1,0,0,-1,0,100]}),{left:20,top:20,width:40,height:10});
 assert.deepEqual(paragraphTargetRect(p,{pageBounds:[0,0,80,80],transform:[1,0,0,-1,-10,90]}),{left:12.5,top:12.5,width:50,height:12.5});
 assert.deepEqual(paragraphTargetRect(p,{pageBounds:[0,0,100,100],transform:[0,1,1,0,0,0]}),{left:70,top:20,width:10,height:40});
 assert.deepEqual(paragraphTargetRect(p,{pageBounds:[0,0,200,200],transform:[2,0,0,-2,0,200]}),{left:20,top:20,width:40,height:10});
 assert.equal(paragraphTargetRect(p,{pageBounds:[0,0,10,10],transform:[1,0,0,1,0,0]}),null);
});
test('targets use actual paragraph identity, accessible exact hitboxes, no layout shift and canvas lifetime',{timeout:30000},async t=>{
 const browser=await puppeteer.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});t.after(()=>browser.close());const page=await browser.newPage();await page.setContent('<main id="doc"><div class="pdf-page" data-page="1" style="position:relative;width:500px;height:500px"><canvas class="pdf-canvas"></canvas></div></main>');await page.addStyleTag({content:await readFile(new URL('../src/pdf-edit-targets.css',import.meta.url),'utf8')});
 const source=await readFile(new URL('../src/pdf-edit-targets.js',import.meta.url),'utf8');await page.evaluate(async({source,p})=>{const {initPdfEditTargets}=await import(URL.createObjectURL(new Blob([source],{type:'text/javascript'})));window.model={paragraphs:[p,{...p,id:8,editable:false},{...p,id:9,runs:[{text:''}]}],pageBounds:[0,0,100,100],transform:[1,0,0,-1,0,100]};window.targets=initPdfEditTargets({root:document.querySelector('#doc'),onChoose:item=>{window.chosenSame=item===window.model.paragraphs[0];}});window.targets.show({pageIndex:0,model:window.model,selectedId:7});},{source,p});
 assert.equal(await page.$$('.pdf-edit-target').then(a=>a.length),1);const geometry=await page.$eval('.pdf-edit-target',n=>{const r=n.getBoundingClientRect(),parent=n.closest('.pdf-page').getBoundingClientRect();return {width:r.width,height:r.height,left:r.left-parent.left,top:r.top-parent.top,pressed:n.getAttribute('aria-pressed'),label:n.getAttribute('aria-label'),pageHeight:parent.height};});assert.deepEqual(geometry,{width:200,height:50,left:100,top:100,pressed:'true',label:'Edit paragraph: Choose this text',pageHeight:500});await page.locator('.pdf-edit-target').click();assert.equal(await page.evaluate(()=>window.chosenSame),true);
 await page.evaluate(()=>{window.chosenSame=false;window.targets.show({pageIndex:0,model:window.model,disabled:true});});assert.equal(await page.$eval('.pdf-edit-target',n=>n.disabled),true);await page.evaluate(()=>window.targets.show({pageIndex:0,model:window.model}));await page.focus('.pdf-edit-target');assert.equal(await page.evaluate(()=>{const button=document.activeElement;window.targets.show({pageIndex:0,model:window.model,selectedId:7});return button===document.activeElement&&button===document.querySelector('.pdf-edit-target');}),true,'same model refresh retains target and focus');await page.keyboard.press('Enter');assert.equal(await page.evaluate(()=>window.chosenSame),true);
 const polygonHit=await page.evaluate(()=>{const p=window.model.paragraphs[0];window.targets.show({pageIndex:0,model:{...window.model,paragraphs:[{...p,nativeBox:{x:10,top:90,w:80,h:80},nativeQuad:[50,90,90,50,50,10,10,50]}]}});const button=document.querySelector('.pdf-edit-target'),r=button.getBoundingClientRect();return {center:document.elementFromPoint(r.left+r.width/2,r.top+r.height/2)===button,corner:document.elementFromPoint(r.left+2,r.top+2)===button,svg:!!button.querySelector('polygon')};});assert.deepEqual(polygonHit,{center:true,corner:false,svg:true},'diagonal target clips empty AABB corners while retaining actual hit area');
 await page.evaluate(()=>document.querySelector('.pdf-canvas').replaceWith(Object.assign(document.createElement('canvas'),{className:'pdf-canvas'})));await page.waitForFunction(()=>!document.querySelector('.pdf-edit-targets'));await page.evaluate(()=>{window.targets.show({pageIndex:0,model:window.model});window.targets.dispose();});assert.equal(await page.$('.pdf-edit-targets'),null);
});
