import test from 'node:test';import assert from 'node:assert/strict';import{readFileSync}from'node:fs';import * as mupdf from'mupdf';import * as pdfjs from'pdfjs-dist/legacy/build/pdf.mjs';import{createMuPdfProvider,createPdfJsMigrationAdapter}from'../src/pdf-engine.js';import{readPdfJsContents}from'../src/pdf-contents-data.js';
function fixture(){const d=new mupdf.PDFDocument(new Uint8Array(readFileSync(new URL('./fixtures/jett-annotations.pdf',import.meta.url)))),held=[],keep=v=>(held.push(v),v),trailer=d.getTrailer(),root=trailer.get('Root'),p=d.loadPage(2);try{const tree=keep(d.addObject({Count:5})),nodes=Array.from({length:5},()=>keep(d.addObject({}))),child=keep(d.addObject({})),fit=keep(d.newName('Fit')),page=keep(p.getObject());const titles=['Chapter नमस्ते','Named destination','External','Remote','Script'];nodes.forEach((n,i)=>{n.put('Title',keep(d.newString(titles[i])));n.put('Parent',tree);if(i)n.put('Prev',nodes[i-1]);if(i<4)n.put('Next',nodes[i+1]);});tree.put('First',nodes[0]);tree.put('Last',nodes[4]);nodes[0].put('Count',-1);nodes[0].put('Dest',[page,fit]);nodes[0].put('First',child);nodes[0].put('Last',child);child.put('Parent',nodes[0]);child.put('Title',keep(d.newString('<b>Child</b>')));child.put('Dest',[1,fit]);nodes[1].put('Dest',keep(d.newString('chapter नमस्ते # 1')));root.put('Names',{Dests:{Names:[keep(d.newString('chapter नमस्ते # 1')),[page,fit]]}});nodes[2].put('A',{S:keep(d.newName('URI')),URI:keep(d.newString('https://example.com/#page=1'))});nodes[3].put('A',{S:keep(d.newName('GoToR')),F:keep(d.newString('other.pdf')),D:[0,fit]});nodes[4].put('A',{S:keep(d.newName('JavaScript')),JS:keep(d.newString('app.alert("bad")'))});root.put('Outlines',tree);const b=d.saveToBuffer();try{return new Uint8Array(b.asUint8Array());}finally{b.destroy();}}finally{held.reverse().forEach(v=>v.destroy());p.destroy();root.destroy();trailer.destroy();d.destroy();}}
test('actual adapters resolve nested and named local bookmarks, retaining external labels without navigation',async()=>{
 const source=fixture(),before=source.slice(),results=[];
 for(const provider of[createMuPdfProvider(mupdf),createPdfJsMigrationAdapter(pdfjs)]){const opened=await provider.open(source);try{const data=await opened.readContents();results.push(data);assert.deepEqual(data.map(v=>v.pageNumber),[3,3,null,null,null]);assert.equal(data[0].children[0].pageNumber,2);assert.equal(data[0].children[0].title,'<b>Child</b>');assert.equal(data[0].open,false);}finally{await opened.loadingTask.destroy();}await assert.rejects(opened.readContents(),/PDF_DOCUMENT_CLOSED/);}
 assert.deepEqual(results[0].map(v=>({title:v.title,pageNumber:v.pageNumber,children:v.children.map(c=>({title:c.title,pageNumber:c.pageNumber}))})),results[1].map(v=>({title:v.title,pageNumber:v.pageNumber,children:v.children.map(c=>({title:c.title,pageNumber:c.pageNumber}))})));assert.deepEqual(results[0],results[1]);assert.deepEqual(source,before);
});
test('normalization rejects cycles and bounds, with invalid destinations nonnavigable',async()=>{
 const noOp=()=>{};const doc={numPages:3,getOutline:async()=>[{title:'Bad',dest:[99,{name:'Fit'}],items:[]}]};assert.equal((await readPdfJsContents(doc,noOp))[0].pageNumber,null);
 doc.getOutline=async()=>[{title:'x'.repeat(4097),items:[]}];await assert.rejects(readPdfJsContents(doc,noOp),/PDF_CONTENTS_LIMIT/);
 const item={title:'loop'};item.items=[item];doc.getOutline=async()=>[item];await assert.rejects(readPdfJsContents(doc,noOp),/PDF_CONTENTS_INVALID/);
});
test('PDF.js adapter keeps document identity and refuses completion after destruction during destination resolution',async()=>{
 let finish;const document={numPages:3,getOutline:async()=>[{title:'Waiting',dest:'chapter'}],getDestination:()=>new Promise(r=>finish=r)};const task={promise:Promise.resolve(document),destroy:async()=>{}};const opened=await createPdfJsMigrationAdapter({getDocument:()=>task}).open(new Uint8Array());assert.equal(opened.document,document);const pending=opened.readContents();while(!finish)await Promise.resolve();await opened.loadingTask.destroy();finish([0,{name:'Fit'}]);await assert.rejects(pending,/PDF_DOCUMENT_CLOSED/);
});
test('native URI fragment actions cannot acquire local navigation authority and malformed direct destinations stay inert',async()=>{
 const d=new mupdf.PDFDocument(fixture()),trailer=d.getTrailer(),root=trailer.get('Root'),tree=root.get('Outlines'),first=tree.get('First'),second=first.get('Next'),external=second.get('Next'),name=d.newName('URI'),uri=d.newString('#page=1'),xyz=d.newName('XYZ');let bytes;
 try{external.put('A',{S:name,URI:uri});first.put('Dest',[0,xyz,12]);const buffer=d.saveToBuffer();try{bytes=new Uint8Array(buffer.asUint8Array());}finally{buffer.destroy();}}finally{for(const value of[xyz,uri,name,external,second,first,tree,root,trailer,d])value.destroy();}
 for(const provider of[createMuPdfProvider(mupdf),createPdfJsMigrationAdapter(pdfjs)]){const opened=await provider.open(bytes);try{const data=await opened.readContents();assert.equal(data[0].pageNumber,null);assert.equal(data[2].pageNumber,null);}finally{await opened.loadingTask.destroy();}}
});
test('native title byte bound applies before decoding and raw node authority does not depend on native outline conversion',async()=>{
 const original=mupdf.PDFDocument.prototype.loadOutline;let openedProof;
 mupdf.PDFDocument.prototype.loadOutline=function(){throw new Error('Must not infer authority from converted output');};
 try{openedProof=await createMuPdfProvider(mupdf).open(fixture());assert.deepEqual((await openedProof.readContents()).map(v=>v.pageNumber),[3,3,null,null,null]);}finally{await openedProof?.loadingTask.destroy();mupdf.PDFDocument.prototype.loadOutline=original;}
 const doc=new mupdf.PDFDocument(fixture()),trailer=doc.getTrailer(),root=trailer.get('Root'),tree=root.get('Outlines'),first=tree.get('First'),title=doc.newByteString(new Uint8Array(16385).fill(65));let bytes;try{first.put('Title',title);const b=doc.saveToBuffer();try{bytes=new Uint8Array(b.asUint8Array());}finally{b.destroy();}}finally{for(const item of[title,first,tree,root,trailer,doc])item.destroy();}
 const decode=mupdf.PDFObject.prototype.asString;let largeDecoded=false;mupdf.PDFObject.prototype.asString=function(){if(this.isString()&&this.asByteString().byteLength>16384)largeDecoded=true;return decode.call(this);};let opened;try{opened=await createMuPdfProvider(mupdf).open(bytes);await assert.rejects(opened.readContents(),/PDF_CONTENTS_LIMIT/);assert.equal(largeDecoded,false);}finally{await opened?.loadingTask.destroy();mupdf.PDFObject.prototype.asString=decode;}
});
test('same-title local and external siblings retain their own raw destination authority',async()=>{
 const doc=new mupdf.PDFDocument(fixture()),trailer=doc.getTrailer(),root=trailer.get('Root'),tree=root.get('Outlines'),first=tree.get('First'),second=first.get('Next'),external=second.get('Next'),title=doc.newString('Same title');let bytes;try{first.put('Title',title);external.put('Title',title);const b=doc.saveToBuffer();try{bytes=new Uint8Array(b.asUint8Array());}finally{b.destroy();}}finally{for(const item of[title,external,second,first,tree,root,trailer,doc])item.destroy();}
 for(const provider of[createMuPdfProvider(mupdf),createPdfJsMigrationAdapter(pdfjs)]){const opened=await provider.open(bytes);try{const data=await opened.readContents();assert.equal(data[0].title,data[2].title);assert.equal(data[0].pageNumber,3);assert.equal(data[2].pageNumber,null);}finally{await opened.loadingTask.destroy();}}
});
