import {mkdir,writeFile} from 'node:fs/promises';import test from 'node:test';import assert from 'node:assert/strict';import {spawn}from'node:child_process';import path from'node:path';import puppeteer from'puppeteer-core';import {root}from'./validate.mjs';
test('own Edit saves and restores a draft then reviews and reopens an independently edited library copy',{timeout:120000},async t=>{
 const server=spawn(process.execPath,[path.join(root,'node_modules/vite/bin/vite.js'),'--host','127.0.0.1','--port','5098','--strictPort'],{cwd:root,stdio:'ignore'});t.after(()=>server.kill());const url='http://127.0.0.1:5098';for(let i=0;i<100;i++){try{if((await fetch(url)).ok)break;}catch{}await new Promise(r=>setTimeout(r,100));}
 const browser=await puppeteer.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});t.after(()=>browser.close());const page=await browser.newPage();await page.setViewport({width:1280,height:1000});await page.evaluateOnNewDocument(()=>{localStorage.setItem('jt.welcomed','1');localStorage.setItem('jt.mic','off');});await page.goto(url);await page.waitForFunction(()=>window.__jtApp?.booted);
 await(await page.$('#home-file-input')).uploadFile(path.join(root,'test/fixtures/jett-range.pdf'));await page.waitForFunction(()=>document.body.dataset.view==='read'&&document.querySelectorAll('.pdf-page').length===3);
 const original=await page.evaluate(async()=>{const {getDocs}=await import('/src/db.js');const doc=(await getDocs()).find(d=>d.provenance?.sourceKind==='pdf');return {id:doc.id,bytes:Array.from(doc.sourceBytes),digest:doc.provenance.contentDigest};});
 await page.locator('[data-workspace="edit"]').click();await page.locator('#pdf-edit-load').click();
 await page.waitForFunction(()=>document.querySelector('#pdf-edit-paragraph').options.length>1,{timeout:30000}).catch(async e=>{throw new Error(e.message+' '+await page.$eval('#pdf-edit-status',n=>n.textContent));});
 const index=await page.$eval('#pdf-edit-paragraph',n=>[...n.options].find(o=>o.textContent.includes('Start at the orchard gate'))?.value);assert.ok(index!==undefined);
 await page.select('#pdf-edit-paragraph',index);const oldText=await page.$eval('#pdf-edit-text',n=>n.value),newText=oldText.replace('Start','Meet');await page.locator('#pdf-edit-text').fill(newText);await page.waitForFunction(()=>document.getElementById('pdf-edit-status').textContent.startsWith('Draft saved'));
 await page.reload();await page.waitForFunction(()=>window.__jtApp?.booted&&document.getElementById('pdf-edit-text').value.includes('Meet at the orchard gate'),{timeout:30000});assert.equal(await page.$eval('#pdf-edit-text',n=>n.value),newText);
 if(process.env.JETT_EDIT_EVIDENCE_DIR){
  await mkdir(process.env.JETT_EDIT_EVIDENCE_DIR,{recursive:true});
  for(const [name,width,height]of [['desktop',1280,1000],['phone',390,844]]){await page.setViewport({width,height});await new Promise(r=>setTimeout(r,600));await page.evaluate(()=>scrollTo({top:0,behavior:'instant'}));await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:path.join(process.env.JETT_EDIT_EVIDENCE_DIR,`${name}.png`)});}
  await page.setViewport({width:1280,height:1000});
 }
 await page.locator('#pdf-edit-review').click();await page.waitForFunction(()=>document.getElementById('pdf-review-dialog').open&&!document.getElementById('pdf-review-save').disabled,{timeout:30000}).catch(async e=>{throw new Error(e.message+' '+await page.$eval('#pdf-edit-status',n=>n.textContent));});
 if(process.env.JETT_EDIT_EVIDENCE_DIR)await page.screenshot({path:path.join(process.env.JETT_EDIT_EVIDENCE_DIR,'review.png')});
 await page.locator('#pdf-review-save').click();await page.waitForFunction(()=>!document.getElementById('pdf-review-dialog').open,{timeout:30000});
 const proof=await page.evaluate(async original=>{const {getDocs,getRecords}=await import('/src/db.js'),docs=await getDocs(),source=docs.find(d=>d.id===original.id),copy=docs.find(d=>d.provenance?.derivedFrom?.documentId===original.id);return {source:Array.from(source.sourceBytes),draft:source.textEditDraft,docs:docs.map(d=>({id:d.id,title:d.title,text:d.text,provenance:d.provenance})),copy:copy?{id:copy.id,bytes:Array.from(copy.sourceBytes),text:copy.text,provenance:copy.provenance,records:await getRecords(copy.id)}:null};},original);
 assert.deepEqual(proof.source,original.bytes);assert.equal(proof.draft.text,newText);assert.ok(proof.copy,JSON.stringify(proof.docs));assert.match(proof.copy.text,/Meet at the orchard gate/);assert.doesNotMatch(proof.copy.text,/Start at the orchard gate/);assert.equal(proof.copy.records.length,0);
 if(process.env.JETT_EDIT_EVIDENCE_DIR)await writeFile(path.join(process.env.JETT_EDIT_EVIDENCE_DIR,'edited.pdf'),new Uint8Array(proof.copy.bytes));
 await page.reload();await page.waitForFunction(()=>window.__jtApp?.booted);assert.ok(await page.evaluate(()=>document.getElementById('doc').textContent.includes('Meet at the orchard gate')));
});
