import test from 'node:test';
import assert from 'node:assert/strict';
import * as m from 'mupdf';
import {readFileSync} from 'node:fs';
import {inspectPdfCrop,cropPdfPages} from '../src/pdf-crop.js';
function fixture(){const doc=new m.PDFDocument(),font=new m.Font('Helvetica'),ref=doc.addSimpleFont(font);try{for(const angle of [0,90,180,270]){const obj=doc.addPage([0,0,400,500],angle,{Font:{F1:ref}},'BT /F1 16 Tf 70 330 Td (Hidden is not removed.) Tj ET');try{doc.insertPage(-1,obj);obj.put('CropBox',[30,40,370,470]);obj.put('UserUnit',2);}finally{obj.destroy();}}const b=doc.saveToBuffer();try{return new Uint8Array(b.asUint8Array());}finally{b.destroy();}}finally{ref.destroy();font.destroy();doc.destroy();}}
function snapshot(bytes){const doc=new m.PDFDocument(bytes);try{return Array.from({length:doc.countPages()},(_,i)=>{const page=doc.loadPage(i),obj=page.getObject(),crop=obj.getInheritable('CropBox'),contents=obj.get('Contents');const buffer=contents.readStream();try{return {bounds:page.getBounds(),crop:crop.asJS(),stream:Array.from(buffer.asUint8Array())};}finally{buffer.destroy();contents.destroy();crop.destroy();obj.destroy();page.destroy();}});}finally{doc.destroy();}}
test('crop all rotations in displayed points preserves streams and original bytes, PDF.js agrees',async()=>{const bytes=fixture(),before=bytes.slice(),original=snapshot(bytes),changes=[];const {getDocument}=await import('pdfjs-dist/legacy/build/pdf.mjs');const task=getDocument({data:bytes.slice(),isEvalSupported:false});const pdf=await task.promise;const expected=[];try{for(let pageIndex=0;pageIndex<4;pageIndex++){const info=await inspectPdfCrop(bytes,pageIndex),b=info.bounds,rect=[b[0]+40,b[1]+60,b[2]-80,b[3]-100];changes.push({pageIndex,rect});const page=await pdf.getPage(pageIndex+1),vp=page.getViewport({scale:1}),a=vp.convertToPdfPoint(rect[0],rect[1]),z=vp.convertToPdfPoint(rect[2],rect[3]);expected.push([Math.min(a[0],z[0]),Math.min(a[1],z[1]),Math.max(a[0],z[0]),Math.max(a[1],z[1])]);}}finally{await task.destroy();}const output=await cropPdfPages(bytes,changes),after=snapshot(output);assert.deepEqual(bytes,before);assert.equal(after.length,4);for(let i=0;i<4;i++){assert.deepEqual(after[i].stream,original[i].stream);assert.deepEqual(after[i].crop,expected[i]);assert.equal(after[i].bounds[2]-after[i].bounds[0],changes[i].rect[2]-changes[i].rect[0]);assert.equal(after[i].bounds[3]-after[i].bounds[1],changes[i].rect[3]-changes[i].rect[1]);}const outTask=getDocument({data:output.slice(),isEvalSupported:false});try{const reopened=await outTask.promise;for(let i=0;i<4;i++)assert.deepEqual((await reopened.getPage(i+1)).view,expected[i]);}finally{await outTask.destroy();}});
test('rejects missing/invalid page, expanding or empty crop and duplicates',async()=>{const bytes=fixture();for(const changes of [[],[{pageIndex:99,rect:[1,1,2,2]}],[{pageIndex:0,rect:[-1,0,100,100]}],[{pageIndex:0,rect:[1,1,1,2]}],[{pageIndex:0,rect:[0,0,Infinity,200]}],[{pageIndex:0,rect:[1,1,100,100]},{pageIndex:0,rect:[1,1,50,50]}]])await assert.rejects(cropPdfPages(bytes,changes),/CROP_/);await assert.rejects(inspectPdfCrop(bytes,-1),/CROP_/);});
test('preserves form fields and annotations while changing only one page',async()=>{const bytes=new Uint8Array(readFileSync(new URL('./fixtures/jett-fillable.pdf',import.meta.url)));const info=await inspectPdfCrop(bytes,0);const output=await cropPdfPages(bytes,[{pageIndex:0,rect:[10,10,info.bounds[2]-10,info.bounds[3]-10]}]);const doc=new m.PDFDocument(output);try{const p=doc.loadPage(0);try{const ws=p.getWidgets();assert.ok(ws.length);ws.forEach(w=>w.destroy());}finally{p.destroy();}}finally{doc.destroy();}});
test('rejects encrypted sources and detects missing serialized crop',async()=>{const bytes=fixture(),doc=new m.PDFDocument(bytes);let encrypted;try{const b=doc.saveToBuffer({encrypt:'aes-256','owner-password':'owner','user-password':''});try{encrypted=new Uint8Array(b.asUint8Array());}finally{b.destroy();}}finally{doc.destroy();}await assert.rejects(cropPdfPages(encrypted,[{pageIndex:0,rect:[10,10,200,200]}]),/CROP_DOCUMENT_RESTRICTED/);const save=m.PDFDocument.prototype.saveToBuffer;m.PDFDocument.prototype.saveToBuffer=function(){return new m.Buffer(bytes);};try{await assert.rejects(cropPdfPages(bytes,[{pageIndex:0,rect:[10,10,200,200]}]),/CROP_READBACK/);}finally{m.PDFDocument.prototype.saveToBuffer=save;}});
test('native annotation dictionaries survive, and changed content streams are rejected',async()=>{const d=new m.PDFDocument(fixture()),p=d.loadPage(0),a=p.createAnnotation('Text');let bytes;try{a.setRect([100,100,120,120]);a.setContents('Annotation must remain');a.update();const b=d.saveToBuffer();try{bytes=new Uint8Array(b.asUint8Array());}finally{b.destroy();}}finally{a.destroy();p.destroy();d.destroy();}const output=await cropPdfPages(bytes,[{pageIndex:0,rect:[40,60,600,700]}]);const reopened=new m.PDFDocument(output),page=reopened.loadPage(0),marks=page.getAnnotations();try{assert.equal(marks.length,1);assert.equal(marks[0].getContents(),'Annotation must remain');}finally{marks.forEach(a=>a.destroy());page.destroy();reopened.destroy();}const save=m.PDFDocument.prototype.saveToBuffer;m.PDFDocument.prototype.saveToBuffer=function(...args){const p=this.loadPage(0),o=p.getObject(),c=o.get('Contents');try{c.writeStream('');}finally{c.destroy();o.destroy();p.destroy();}return save.apply(this,args);};try{await assert.rejects(cropPdfPages(bytes,[{pageIndex:0,rect:[40,60,600,700]}]),/CROP_CONTENT_CHANGED/);}finally{m.PDFDocument.prototype.saveToBuffer=save;}});
test('signed and permission-restricted PDFs refuse crop without modifying source',async()=>{const d=new m.PDFDocument(fixture());let bytes;const trailer=d.getTrailer(),root=trailer.get('Root'),form=d.newDictionary(),sig=d.newDictionary(),value=d.newDictionary(),name=d.newName('Sig');try{sig.put('FT',name);value.put('ByteRange',[0,10,20,30]);sig.put('V',value);form.put('Fields',[sig]);root.put('AcroForm',form);const b=d.saveToBuffer();try{bytes=new Uint8Array(b.asUint8Array());}finally{b.destroy();}}finally{name.destroy();value.destroy();sig.destroy();form.destroy();root.destroy();trailer.destroy();d.destroy();}const original=bytes.slice();await assert.rejects(inspectPdfCrop(bytes,0),/CROP_DOCUMENT_RESTRICTED/);await assert.rejects(cropPdfPages(bytes,[{pageIndex:0,rect:[40,60,600,700]}]),/CROP_DOCUMENT_RESTRICTED/);assert.deepEqual(bytes,original);const permission=m.PDFDocument.prototype.hasPermission;m.PDFDocument.prototype.hasPermission=function(kind){return kind==='assemble'?false:permission.call(this,kind);};try{await assert.rejects(cropPdfPages(fixture(),[{pageIndex:0,rect:[40,60,600,700]}]),/CROP_PERMISSION_DENIED/);}finally{m.PDFDocument.prototype.hasPermission=permission;}});
