import {openReaderView,closeReaderView} from './reader-navigation.mjs';
import test from 'node:test';import assert from 'node:assert/strict';import {spawn} from 'node:child_process';import {mkdtemp,writeFile,rm,mkdir} from 'node:fs/promises';import {tmpdir} from 'node:os';import path from 'node:path';import * as m from 'mupdf';import puppeteer from 'puppeteer-core';import {root} from './validate.mjs';import {selectPdfQuote} from './pdf-selection-helpers.mjs';

test('page browser preserves reading geometry, bounds previews and owns mobile navigation',{timeout:120000},async t=>{
 const dir=await mkdtemp(path.join(tmpdir(),'jett-pages-'));t.after(()=>rm(dir,{recursive:true,force:true}));const file=path.join(dir,'pages-200.pdf');const pdf=new m.PDFDocument();try{for(let i=0;i<200;i++){const page=pdf.addPage([0,0,200,240],0,{},i%2?'0.1 0.4 0.3 rg 20 170 160 40 re f':'');pdf.insertPage(-1,page);page.destroy();}const buffer=pdf.saveToBuffer();await writeFile(file,buffer.asUint8Array());buffer.destroy();}finally{pdf.destroy();}
 const server=spawn(process.execPath,[path.join(root,'node_modules/vite/bin/vite.js'),'--host','127.0.0.1','--port','5086','--strictPort'],{cwd:root,stdio:'ignore'});t.after(()=>server.kill());const url='http://127.0.0.1:5086';for(let i=0;i<100;i++){try{if((await fetch(url)).ok)break;}catch{}await new Promise(r=>setTimeout(r,100));}
 const browser=await puppeteer.launch({executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});t.after(()=>browser.close());const page=await browser.newPage();await page.setViewport({width:850,height:1000});await page.evaluateOnNewDocument(()=>{localStorage.setItem('jt.welcomed','1');localStorage.setItem('jt.mic','off');});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const main=await(await fetch(url+'/src/main.js')).text(),anchor='source.blocks = blocks;\n    await engine.load(state.doc.id);';assert.equal(main.split(anchor).length-1,1);
 await page.setRequestInterception(true);page.on('request',r=>r.url()===url+'/src/main.js'?r.respond({status:200,contentType:'text/javascript',body:main.replace(anchor,'source.blocks = blocks;\n    if(window.__dockGate)await window.__dockGate();\n    await engine.load(state.doc.id);')}):r.continue());
 await page.goto(url);await page.waitForFunction(()=>window.__jtApp?.booted);await(await page.$('#home-file-input')).uploadFile(file);await page.waitForFunction(()=>document.body.dataset.view==='read'&&document.getElementById('reader-page-total').textContent==='of 200');
 await openReaderView(page,'#reader-page-number');await page.locator('#reader-page-number').fill('150');await page.keyboard.press('Enter');await page.waitForFunction(()=>document.getElementById('reader-page-number').value==='150'&&!document.getElementById('reader-page-return').disabled);await closeReaderView(page);
 await page.$eval('.pdf-page[data-page="150"]',n=>scrollBy({top:n.getBoundingClientRect().top+n.getBoundingClientRect().height*.25-document.getElementById('reader-chrome').getBoundingClientRect().bottom-12,behavior:'instant'}));
 const location=()=>page.$eval('.pdf-page[data-page="150"]',n=>(document.getElementById('reader-chrome').getBoundingClientRect().bottom+12-n.getBoundingClientRect().top)/n.getBoundingClientRect().height);
 const originalLocation=await location();
 const metrics=()=>page.evaluate(()=>({y:scrollY,width:document.querySelector('.pdf-page').getBoundingClientRect().width,chrome:document.getElementById('reader-chrome').getBoundingClientRect().height}));
 const settle=()=>page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));
 const before=await metrics();
 await page.evaluate(()=>{window.beforeDockPages=[...document.querySelectorAll('.pdf-page')];window.originalDockGetAll=IDBIndex.prototype.getAll;IDBIndex.prototype.getAll=function(...args){if(this.objectStore.name==='records'){IDBIndex.prototype.getAll=originalDockGetAll;throw Error('Injected dock history failure');}return originalDockGetAll.apply(this,args);};});
 await page.click('#reader-pages-toggle');await page.waitForFunction(()=>document.getElementById('reader-page-status').textContent.includes('Injected dock history failure'));
 assert.equal(await page.$eval('#reader-page-browser',n=>n.open),false);assert.deepEqual(await metrics(),before,'failed dock restores source geometry');assert.equal(await page.evaluate(()=>beforeDockPages.every(n=>n.isConnected)),true);assert.ok(Math.abs(await location()-originalLocation)<.002);
 await page.evaluate(()=>{window.__dockGate=()=>{delete window.__dockGate;return new Promise(resolve=>window.__dockRelease=resolve);};});
 await page.click('#reader-pages-toggle');await page.waitForFunction(()=>typeof window.__dockRelease==='function');assert.equal(await page.$eval('#reader-pages-toggle',n=>n.disabled),true);await page.$eval('#reader-pages-toggle',n=>{n.click();n.click();});await page.evaluate(()=>window.__jtApp.showView('home'));await page.evaluate(()=>window.__dockRelease());await page.evaluate(()=>window.__jtApp.showView('read'));
 await page.waitForFunction(()=>document.getElementById('reader-page-number').value==='150'&&document.getElementById('pdf-zoom-value').textContent==='250%'&&!document.getElementById('reader-pages-toggle').disabled);await settle();assert.equal(await page.$eval('#reader-page-browser',n=>n.open),false);assert.notEqual(await page.evaluate(()=>document.body.dataset.readerPagesDocked),'true');assert.ok(Math.abs(await location()-originalLocation)<.002,'route cancellation keeps original place');
await page.click('#reader-pages-toggle');await page.waitForFunction(()=>document.getElementById('reader-page-browser').open);await settle();assert.ok(await page.$eval('#reader-page-browser',n=>n.getBoundingClientRect().bottom<=innerHeight),'panel fits viewport');const docked=await metrics();assert.equal(await page.$eval('#reader-page-status',n=>n.textContent),'','successful retry clears owned error');assert.ok(Math.abs(await location()-originalLocation)<.002,'deep-page offset survives fitting');assert.ok(docked.width<before.width,JSON.stringify({before,docked,layout:await page.$eval('#reader-main',n=>({width:getComputedStyle(n).width,margin:getComputedStyle(n).marginLeft,body:document.body.dataset.readerPagesDocked,article:document.getElementById('doc').clientWidth,zoom:document.getElementById('pdf-zoom-value').textContent}))}));assert.equal(docked.chrome,before.chrome);assert.ok(await page.$eval('.pdf-page',n=>n.getBoundingClientRect().left>=document.getElementById('reader-page-browser').getBoundingClientRect().right),'panel does not cover the page');
 await page.waitForFunction(()=>document.querySelector('[data-reader-page] canvas'));assert.equal(await page.$$eval('[data-reader-page]',n=>n.length),200);assert.ok(await page.$$eval('[data-reader-page] canvas',n=>n.length)<20,'previews allocate only a bounded window');
 await page.click('#pdf-contents summary');await settle();assert.deepEqual(await metrics(),docked,'expanded Contents never enlarges the toolbar');assert.match(await page.$eval('#pdf-contents-status',n=>n.textContent),/no readable bookmarks/);await page.click('#pdf-contents summary');await settle();
 await page.$eval('#reader-page-browser-scroll',n=>{n.scrollTop=n.scrollHeight;});await page.waitForFunction(()=>document.querySelector('[data-reader-page="200"] canvas'),{timeout:30000}).catch(async error=>{throw new Error(error.message+' '+JSON.stringify(await page.evaluate(()=>{const root=document.querySelector('#reader-page-browser-scroll'),last=document.querySelector('[data-reader-page="200"]');return {scrollTop:root.scrollTop,scrollHeight:root.scrollHeight,clientHeight:root.clientHeight,root:root.getBoundingClientRect().toJSON(),last:last.getBoundingClientRect().toJSON(),previewPages:[...document.querySelectorAll('[data-reader-page] canvas')].map(n=>n.closest('[data-reader-page]').dataset.readerPage),open:document.querySelector('#reader-page-browser').open,active:document.activeElement.outerHTML,errors:document.querySelector('#reader-page-browser-status').textContent};})));});assert.ok(await page.$$eval('[data-reader-page] canvas',n=>n.length)<20);assert.equal(await page.$('[data-reader-page="1"] canvas'),null,'offscreen allocation is released');
 await page.click('[data-reader-page="200"]');await page.waitForFunction(()=>document.getElementById('reader-page-number').value==='200');assert.equal(await page.$eval('#reader-page-return',n=>n.textContent),'Return to 1');
 await page.click('#reader-page-browser-close');await page.waitForFunction(()=>!document.getElementById('reader-page-browser').open);assert.equal(await page.evaluate(()=>document.activeElement.id),'reader-pages-toggle');
 await openReaderView(page,'#reader-page-return');await page.click('#reader-page-return');await page.waitForFunction(()=>document.getElementById('reader-page-return').disabled);await closeReaderView(page);
 await openReaderView(page,'#pdf-zoom-out');await page.click('#pdf-zoom-out');await page.waitForFunction(()=>!document.getElementById('pdf-zoom-out').disabled);await closeReaderView(page);const custom=await metrics(),customZoom=await page.$eval('#pdf-zoom-value',n=>n.textContent);
 await page.click('#reader-pages-toggle');await page.waitForFunction(()=>document.getElementById('reader-page-browser').open);assert.equal((await metrics()).width,custom.width,'custom zoom is retained when docked');assert.equal(await page.$eval('#pdf-zoom-value',n=>n.textContent),customZoom);
 await page.click('#reader-page-browser-close');await page.waitForFunction(()=>!document.getElementById('reader-page-browser').open);assert.equal((await metrics()).width,custom.width);

 await page.setViewport({width:390,height:844});await openReaderView(page,'#pdf-fit-width');await page.click('#pdf-fit-width');await page.waitForFunction(()=>!document.getElementById('pdf-fit-width').disabled);await settle();const mobileBefore=await metrics();
 await page.click('#reader-pages-toggle');await page.waitForFunction(()=>document.getElementById('reader-page-browser').matches(':modal'));await settle();assert.deepEqual(await metrics(),mobileBefore);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 if(process.env.JETT_PAGE_BROWSER_EVIDENCE_DIR){await mkdir(process.env.JETT_PAGE_BROWSER_EVIDENCE_DIR,{recursive:true});await page.screenshot({path:path.join(process.env.JETT_PAGE_BROWSER_EVIDENCE_DIR,'phone.png')});}
 await page.keyboard.press('Escape');await page.waitForFunction(()=>!document.getElementById('reader-page-browser').open);assert.equal(await page.evaluate(()=>document.activeElement.id),'reader-pages-toggle');assert.deepEqual(await metrics(),mobileBefore);
 await page.click('#reader-pages-toggle');await page.$eval('#reader-page-browser-scroll',n=>{n.scrollTop=n.scrollHeight;});await page.waitForFunction(()=>document.querySelector('[data-reader-page="199"] canvas'));await page.click('[data-reader-page="199"]');await page.waitForFunction(()=>!document.getElementById('reader-page-browser').open&&document.getElementById('reader-page-number').value==='199');assert.equal(await page.evaluate(()=>document.activeElement.dataset.page),'199');assert.equal(await page.evaluate(()=>window.__jtApp.currentBlock()),-1);
 await page.click('#reader-pages-toggle');await page.evaluate(()=>window.__jtApp.addDocument('An independent text source.','Other source'));await page.waitForFunction(()=>!document.getElementById('reader-page-browser').open);assert.equal(await page.$$eval('[data-reader-page] canvas',n=>n.length),0,'source replacement releases old thumbnails');
 // Real annotation draft refuses a thumbnail jump and keeps the mobile drawer recoverable.
 await page.evaluate(()=>window.__jtApp.showView('home'));await(await page.$('#home-file-input')).uploadFile(path.join(root,'test/fixtures/jett-annotations.pdf'));await page.waitForFunction(()=>document.body.dataset.view==='read'&&document.getElementById('reader-page-total').textContent==='of 3');await page.click('[data-workspace="annotate"]');await selectPdfQuote(page,'The orchard is ready.',0,2);await page.click('[data-annotation="note"]');await page.locator('#annotation-note-text').fill('Keep this unsaved note.');
 await page.click('#reader-pages-toggle');await page.click('[data-reader-page="3"]');await page.waitForFunction(()=>document.getElementById('reader-page-browser').textContent.includes('Save or cancel your note'));assert.equal(await page.$eval('#reader-page-browser',n=>n.open),true);assert.equal(await page.$eval('#annotation-note-text',n=>n.value),'Keep this unsaved note.');await page.keyboard.press('Escape');await page.click('[data-annotation="cancel"]');
 await page.setViewport({width:1280,height:1000});await openReaderView(page,'#pdf-fit-width');await page.click('#pdf-fit-width');await page.waitForFunction(()=>!document.getElementById('pdf-fit-width').disabled);await page.click('#reader-pages-toggle');await page.waitForFunction(()=>document.querySelector('[data-reader-page="3"] canvas'));
 await page.evaluate(()=>{window.oldPageCanvas=document.querySelector('.pdf-page > .pdf-canvas');window.oldPreviews=[...document.querySelectorAll('[data-reader-page] canvas')];});
 await openReaderView(page,'#pdf-zoom-out');await page.click('#pdf-zoom-out');await page.waitForFunction(()=>!document.getElementById('pdf-zoom-out').disabled&&document.querySelector('.pdf-page > .pdf-canvas')!==window.oldPageCanvas&&document.querySelector('[data-reader-page="3"] canvas'));
 assert.equal(await page.$eval('#reader-page-browser',n=>n.open),true,'same-source zoom retains panel');assert.equal(await page.evaluate(()=>oldPreviews.every(n=>!n.isConnected&&n.width===0)),true,'zoom releases old preview allocations');
 const rotated=await page.evaluate(()=>{const source=document.querySelector('.pdf-page[data-page="3"] > .pdf-canvas'),preview=document.querySelector('[data-reader-page="3"] canvas');return {source:source.width/source.height,preview:preview.width/preview.height};});assert.ok(Math.abs(rotated.source-rotated.preview)<0.02,'rotated preview preserves physical canvas aspect');
 await page.click('[data-reader-page="2"]');await settle();
 await selectPdfQuote(page,'The orchard is ready.',0,2);await page.click('[data-annotation="note"]');await page.locator('#annotation-note-text').fill('Keep through responsive layout.');await page.click('#reader-page-browser-close');await page.waitForFunction(()=>document.getElementById('reader-page-browser-status').textContent.includes('Save or cancel your note'));assert.equal(await page.$eval('#reader-page-browser',n=>n.open),true);
 await page.setViewport({width:390,height:844});await page.waitForFunction(()=>!document.getElementById('reader-page-browser').open&&document.body.dataset.readerPagesDocked!=='true');assert.equal(await page.$eval('#annotation-note-text',n=>n.value),'Keep through responsive layout.');
 await page.click('#reader-pages-toggle');await page.waitForFunction(()=>document.getElementById('reader-page-browser').matches(':modal'));await page.keyboard.press('Escape');await page.waitForFunction(()=>!document.getElementById('reader-page-browser').open);await page.click('[data-annotation="cancel"]');await page.setViewport({width:1280,height:1000});await openReaderView(page,'#pdf-fit-width');await page.click('#pdf-fit-width');await page.waitForFunction(()=>!document.getElementById('pdf-fit-width').disabled);await page.click('#reader-pages-toggle');await page.waitForFunction(()=>document.getElementById('reader-page-browser').open);await page.click('[data-reader-page="2"]');await settle();

 if(process.env.JETT_PAGE_BROWSER_EVIDENCE_DIR)await page.screenshot({path:path.join(process.env.JETT_PAGE_BROWSER_EVIDENCE_DIR,'desktop.png')});
 assert.deepEqual(errors,[]);
});
