import test from 'node:test';import assert from 'node:assert/strict';import {spawn} from 'node:child_process';import {mkdtemp,writeFile,rm,mkdir} from 'node:fs/promises';import {tmpdir} from 'node:os';import path from 'node:path';import * as m from 'mupdf';import puppeteer from 'puppeteer-core';import {root} from './validate.mjs';
test('physical page jumps and return persist across reload in a 200-page PDF',{timeout:120000},async t=>{
 const dir=await mkdtemp(path.join(tmpdir(),'jett-navigation-'));t.after(()=>rm(dir,{recursive:true,force:true}));const file=path.join(dir,'navigation-200.pdf');const pdf=new m.PDFDocument();try{for(let i=0;i<200;i++){const page=pdf.addPage([0,0,200,240],0,{},i%10===0?'0.1 0.4 0.3 rg 20 170 160 40 re f':'');pdf.insertPage(-1,page);page.destroy();}const buffer=pdf.saveToBuffer();await writeFile(file,buffer.asUint8Array());buffer.destroy();}finally{pdf.destroy();}
 const server=spawn(process.execPath,[path.join(root,'node_modules/vite/bin/vite.js'),'--host','127.0.0.1','--port','5085','--strictPort'],{cwd:root,stdio:'ignore'});t.after(()=>server.kill());const url='http://127.0.0.1:5085';for(let i=0;i<100;i++){try{if((await fetch(url)).ok)break;}catch{}await new Promise(r=>setTimeout(r,100));}
 const browser=await puppeteer.launch({executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});t.after(()=>browser.close());const page=await browser.newPage();await page.setViewport({width:1280,height:1000});await page.evaluateOnNewDocument(()=>{localStorage.setItem('jt.welcomed','1');localStorage.setItem('jt.mic','off');});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(url);await page.waitForFunction(()=>window.__jtApp?.booted);await(await page.$('#home-file-input')).uploadFile(file);
 await page.waitForFunction(()=>document.querySelector('#reader-page-total')?.textContent==='of 200'&&!document.getElementById('reader-page-navigation').hidden,{timeout:60000});
 const id=await page.evaluate(()=>window.__jtApp.currentDoc().id);const jump=async value=>{const box=await page.$eval('#reader-page-number',n=>{const r=n.getBoundingClientRect();return {x:r.x+r.width/2,y:r.y+r.height/2};});await page.mouse.click(box.x,box.y,{count:3});await page.keyboard.type(String(value));await page.keyboard.press('Enter');};
 await jump(150);await page.waitForFunction(()=>document.getElementById('reader-page-number').value==='150'&&!document.getElementById('reader-page-return').disabled);
 assert.equal(await page.$eval('#reader-page-return',n=>n.textContent),'Return to 1');
 const y=await page.evaluate(()=>scrollY);await jump(201);await page.waitForFunction(()=>document.getElementById('reader-page-status').textContent.includes('1 to 200'));assert.ok(Math.abs(await page.evaluate(()=>scrollY)-y)<2,JSON.stringify({before:y,after:await page.evaluate(()=>scrollY),bar:await page.$eval('#reader-page-navigation',n=>n.getBoundingClientRect().toJSON()),page:await page.$eval('.pdf-page[data-page="150"]',n=>n.getBoundingClientRect().toJSON())}));
 await page.locator('[aria-label="Next page"]').click();await page.waitForFunction(()=>document.getElementById('reader-page-number').value==='151');
 await page.reload();await page.waitForFunction(()=>window.__jtApp?.booted);await page.evaluate(async id=>{const {getDoc}=await import('/src/db.js');await window.__jtApp.openDocument(await getDoc(id));window.__jtApp.showView('read');},id);
 await page.waitForFunction(()=>document.getElementById('reader-page-number').value==='151',{timeout:60000});assert.equal(await page.$eval('#reader-page-return',n=>n.textContent),'Return to 1');
 const originalWidth=await page.$eval('.pdf-page',n=>n.getBoundingClientRect().width);await page.locator('#pdf-zoom-out').click();await page.waitForFunction(width=>document.querySelector('.pdf-page').getBoundingClientRect().width<width&&!document.getElementById('pdf-zoom-out').disabled,{},originalWidth);
 const beforeFailure=await page.$eval('.pdf-page',n=>n.getBoundingClientRect().width);
 await page.evaluate(()=>{window.originalGetAll=IDBIndex.prototype.getAll;IDBIndex.prototype.getAll=function(...args){if(this.objectStore.name==='records'){IDBIndex.prototype.getAll=originalGetAll;throw new Error('Injected zoom history failure');}return originalGetAll.apply(this,args);};});
 await page.locator('#reader-page-return').click();await page.waitForFunction(()=>document.getElementById('reader-page-status').textContent.includes('Injected zoom history failure'));
 assert.equal(await page.$eval('.pdf-page',n=>n.getBoundingClientRect().width),beforeFailure);assert.equal(await page.$eval('#reader-page-return',n=>n.disabled),false);
 await page.locator('#reader-page-return').click();await page.waitForFunction(()=>document.getElementById('reader-page-number').value==='1'&&document.getElementById('reader-page-return').disabled);assert.equal(await page.$eval('[aria-label="Previous page"]',n=>n.disabled),true);
 if(process.env.JETT_PAGE_NAV_EVIDENCE_DIR){await mkdir(process.env.JETT_PAGE_NAV_EVIDENCE_DIR,{recursive:true});for(const [name,width,height] of [['desktop',1280,1000],['phone',390,844]]){await page.setViewport({width,height});await page.locator('#pdf-fit-width').click();await page.waitForFunction(()=>document.documentElement.scrollWidth===innerWidth);await page.screenshot({path:path.join(process.env.JETT_PAGE_NAV_EVIDENCE_DIR,`${name}.png`)});}}
 assert.deepEqual(errors,[]);
});
