import test from 'node:test';import assert from 'node:assert/strict';import {spawn} from 'node:child_process';import {mkdir} from 'node:fs/promises';import path from 'node:path';import puppeteer from 'puppeteer-core';import {root} from './validate.mjs';import {selectPdfQuote} from './pdf-selection-helpers.mjs';import {openReaderView} from './reader-navigation.mjs';

test('compact View preserves selection and reading place while exposing real document controls',{timeout:90000},async t=>{
 const server=spawn(process.execPath,[path.join(root,'node_modules/vite/bin/vite.js'),'--host','127.0.0.1','--port','5095','--strictPort'],{cwd:root,stdio:'ignore'});t.after(()=>server.kill());const url='http://127.0.0.1:5095';for(let i=0;i<100;i++){try{if((await fetch(url)).ok)break;}catch{}await new Promise(r=>setTimeout(r,100));}
 const browser=await puppeteer.launch({executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});t.after(()=>browser.close());const page=await browser.newPage();await page.setViewport({width:390,height:844});await page.evaluateOnNewDocument(()=>{localStorage.setItem('jt.welcomed','1');localStorage.setItem('jt.mic','off');});const main=await(await fetch(url+'/src/main.js')).text(),anchor='source.blocks = blocks;\n    await engine.load(state.doc.id);';assert.equal(main.split(anchor).length-1,1);await page.setRequestInterception(true);page.on('request',r=>r.url()===url+'/src/main.js'?r.respond({status:200,contentType:'text/javascript',body:main.replace(anchor,'source.blocks = blocks;\n    if(window.__compactFitGate)await window.__compactFitGate();\n    await engine.load(state.doc.id);')}):r.continue());await page.goto(url);await page.waitForFunction(()=>window.__jtApp?.booted);await(await page.$('#home-file-input')).uploadFile(path.join(root,'test/fixtures/jett-range.pdf'));await page.waitForFunction(()=>document.body.dataset.view==='read'&&document.querySelector('#reader-view-toggle')?.textContent.includes('/3'));await page.locator('[data-workspace="annotate"]').click();
 const settle=()=>page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));
 const geometry=()=>page.evaluate(()=>({y:scrollY,chrome:document.getElementById('reader-chrome').getBoundingClientRect().bottom,width:document.querySelector('.pdf-page').getBoundingClientRect().width}));
 await page.evaluate(()=>{window.compactOriginalNodes=['pdf-fit-width','reader-page-number','reader-document-menu','reader-more-tools'].map(id=>document.getElementById(id));});
 assert.ok((await geometry()).chrome<370,'phone chrome leaves more than half the viewport for reading');assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 assert.equal(await page.$eval('#reader-view-popover',n=>n.contains(document.getElementById('reader-page-navigation'))),true);assert.ok(await page.$eval('#reader-pages-toggle',n=>n.getClientRects().length));assert.ok(await page.$eval('#reader-search-toggle',n=>n.getClientRects().length));
 await selectPdfQuote(page,'Start at the orchard gate',0,1);const selected=await page.evaluate(()=>getSelection().toString()),before=await geometry();
 await openReaderView(page);await settle();assert.deepEqual(await geometry(),before,'opening View leaves reading geometry unchanged');assert.equal(await page.evaluate(()=>getSelection().toString()),selected,'opening preserves selected words');
 await page.keyboard.press('Escape');await settle();assert.deepEqual(await geometry(),before);assert.equal(await page.evaluate(()=>document.activeElement.id),'reader-view-toggle');assert.equal(await page.evaluate(()=>getSelection().toString()),selected);
 await page.locator('[data-annotation="underline"]').click();await page.waitForFunction(()=>window.__jtApp.entries().some(e=>e.act==='underline'));
 await selectPdfQuote(page,'Start at the orchard gate',0,1);await page.locator('[data-annotation="note"]').click();await page.locator('#annotation-note-text').fill('A draft remains here.');
 await openReaderView(page);await page.locator('#pdf-zoom-out').click();await page.waitForFunction(()=>document.getElementById('status-text').textContent.includes('Save or cancel your note'));
 assert.equal(await page.$eval('#annotation-note-text',n=>n.value),'A draft remains here.');await page.keyboard.press('Escape');await page.locator('[data-annotation="cancel"]').click();
 await openReaderView(page);const actualLabel=await page.$eval('#reader-view-toggle',n=>n.textContent);await page.locator('#reader-page-number').fill('9999');await page.keyboard.press('Enter');await page.waitForFunction(()=>document.getElementById('reader-page-number').getAttribute('aria-invalid')==='true');await settle();assert.equal(await page.$eval('#reader-view-toggle',n=>n.textContent),actualLabel,'View label reports actual page, not invalid input');await page.click('#reader-page-number');await page.locator('#reader-page-number').fill('3');assert.equal(await page.evaluate(()=>document.activeElement.id),'reader-page-number');await page.keyboard.press('Enter');await page.waitForFunction(()=>document.getElementById('reader-page-number').value==='3'&&!document.getElementById('reader-page-return').disabled);await page.keyboard.press('Escape');await page.waitForFunction(()=>document.getElementById('reader-view-toggle').textContent.includes('3/3'));assert.match(await page.$eval('#reader-view-toggle',n=>n.textContent),/3\/3/);
 await openReaderView(page);await page.locator('#reader-page-return').click();await page.waitForFunction(()=>document.getElementById('reader-page-return').disabled);await page.keyboard.press('Escape');
 await openReaderView(page);await page.locator('#pdf-zoom-out').click();await page.waitForFunction(()=>!document.getElementById('pdf-zoom-out').disabled);await page.keyboard.press('Escape');
 await page.setViewport({width:768,height:1024});await settle();assert.equal(await page.$eval('#reader-view-toggle',n=>n.hidden),false);assert.equal(await page.evaluate(()=>compactOriginalNodes.every(n=>n.isConnected&&document.getElementById('reader-view-popover').contains(n))),true);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.ok(await page.evaluate(()=>{const controls=['reader-view-toggle','reader-search-toggle','reader-pages-toggle'].map(id=>document.getElementById(id).getBoundingClientRect());return controls.every(r=>r.height>=44&&r.width>=44&&r.left>=0&&r.right<=innerWidth)&&controls.every((a,i)=>controls.slice(i+1).every(b=>a.right<=b.left||b.right<=a.left||a.bottom<=b.top||b.bottom<=a.top));}),'tablet controls have44px targets and do not overlap');await page.setViewport({width:1024,height:1000});await settle();assert.equal(await page.$eval('#reader-view-toggle',n=>n.hidden),true);assert.equal(await page.evaluate(()=>compactOriginalNodes.every(n=>n.isConnected&&!document.getElementById('reader-view-popover').contains(n))),true);
 for(const width of [390,1024,768,1280])await page.setViewport({width,height:1000});await settle();assert.equal(await page.$eval('#reader-page-navigation',n=>n.parentElement.id),'reader-toolbar');
 await page.locator('#pdf-fit-width').click();await page.waitForFunction(()=>!document.getElementById('pdf-fit-width').disabled);
 await page.$eval('.pdf-page[data-page="2"]',n=>scrollBy({top:n.getBoundingClientRect().top+n.getBoundingClientRect().height*.2-document.getElementById('reader-chrome').getBoundingClientRect().bottom-12,behavior:'instant'}));
 await page.waitForFunction(()=>{const s=window.__jtApp.readerSession(),v=s.views[s.activeId];return v.pageNumber===2&&Math.abs(v.pageOffset-.2)<.003;});const departure=await page.evaluate(()=>{const s=window.__jtApp.readerSession();return s.views[s.activeId];});
 await page.evaluate(()=>{window.__compactFitGate=()=>{delete window.__compactFitGate;return new Promise(r=>window.__releaseCompactFit=r);};});await page.setViewport({width:600,height:900});await page.waitForFunction(()=>typeof window.__releaseCompactFit==='function');await page.setViewport({width:390,height:844});
 await openReaderView(page);await page.click('#reader-page-number');await page.locator('#reader-page-number').fill('3');assert.equal(await page.evaluate(()=>document.activeElement.id),'reader-page-number');await page.keyboard.press('Enter');assert.equal(await page.$eval('#reader-page-return',n=>n.disabled),true,'navigation waits while fit is held');await page.evaluate(()=>window.__releaseCompactFit());await page.waitForFunction(()=>document.getElementById('reader-page-number').value==='3'&&!document.getElementById('reader-page-return').disabled&&document.querySelector('.pdf-page').getBoundingClientRect().width<=innerWidth,{timeout:30000}).catch(async error=>{throw new Error(error.message+' '+JSON.stringify(await page.evaluate(()=>({input:document.getElementById('reader-page-number').value,backDisabled:document.getElementById('reader-page-return').disabled,width:document.querySelector('.pdf-page').getBoundingClientRect().width,viewport:innerWidth,zoom:document.getElementById('pdf-zoom-value').textContent,status:document.getElementById('status-text').textContent,pageStatus:document.getElementById('reader-page-status').textContent,session:window.__jtApp.readerSession()}))));});await settle();
 const returned=await page.evaluate(()=>{const s=window.__jtApp.readerSession();return s.views[s.activeId].returnPlace;});assert.equal(returned.pageNumber,departure.pageNumber);assert.ok(Math.abs(returned.pageOffset-departure.pageOffset)<.003,'held resize preserves exact departure before queued navigation');await page.keyboard.press('Escape');
 await page.setViewport({width:390,height:844});await openReaderView(page);await page.locator('[data-view-link="home"]').click();await page.waitForFunction(()=>!document.getElementById('reader-view-popover').matches(':popover-open'));await page.locator('[data-view-link="read"]').click();await openReaderView(page);await page.evaluate(()=>window.__jtApp.addDocument('A different source for ownership checks.','Other'));await page.waitForFunction(()=>!document.getElementById('reader-view-popover').matches(':popover-open'));
 assert.equal(await page.evaluate(()=>compactOriginalNodes.every(n=>n.isConnected)),true,'source changes retain the original control nodes');
 if(process.env.JETT_COMPACT_EVIDENCE_DIR){await mkdir(process.env.JETT_COMPACT_EVIDENCE_DIR,{recursive:true});await page.evaluate(async()=>{const {getDocs}=await import('/src/db.js');await window.__jtApp.openDocument((await getDocs()).find(d=>d.provenance?.sourceKind==='pdf'));window.__jtApp.showView('read');});await page.locator('[data-workspace="annotate"]').click();for(const [name,width,height] of [['desktop',1280,1000],['tablet',768,1024],['phone',390,844]]){await page.setViewport({width,height});await openReaderView(page,'#pdf-fit-width');await page.locator('#pdf-fit-width').click();await page.waitForFunction(()=>!document.getElementById('pdf-fit-width').disabled);await page.keyboard.press('Escape');await page.evaluate(()=>scrollTo({top:0,behavior:'instant'}));await settle();if(width===390)assert.ok((await geometry()).chrome<370);await page.screenshot({path:path.join(process.env.JETT_COMPACT_EVIDENCE_DIR,`${name}.png`)});}await openReaderView(page);await page.screenshot({path:path.join(process.env.JETT_COMPACT_EVIDENCE_DIR,'phone-view.png')});}
});
