import test from 'node:test';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import path from 'node:path';
import puppeteer from 'puppeteer-core';
import {root} from './validate.mjs';

test('spoken range survives reading, resolves repeated endpoints, cancels and persists atomically', {timeout:60000}, async t=>{
 const server=spawn(process.execPath,[path.join(root,'node_modules/vite/bin/vite.js'),'--host','127.0.0.1','--port','4993','--strictPort'],{cwd:root,stdio:'ignore'});
 t.after(()=>server.kill('SIGTERM'));
 const url='http://127.0.0.1:4993/';let ready=false;
 for(let i=0;i<100;i++){try{if((await fetch(url)).ok){ready=true;break;}}catch{} await new Promise(r=>setTimeout(r,100));}assert.ok(ready);
 const browser=await puppeteer.launch({executablePath:process.env.CHROME_PATH??'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--no-first-run']});t.after(()=>browser.close());
 const page=await browser.newPage();
 await page.evaluateOnNewDocument(()=>{localStorage.setItem('jt.welcomed','1');localStorage.setItem('jt.mic','off');});
 await page.goto(url);await page.waitForFunction(()=>window.__jtApp?.booted);
 const speak=text=>page.evaluate(text=>window.__jtApp.voiceSegment(text),text);
 const add=text=>page.evaluate(text=>window.__jtApp.addDocument(text,'Staged fixture'),text);
 const count=()=>page.evaluate(()=>window.__jtApp.entries().filter(e=>e.kind==='act'&&!e.undone).length);
 await add('Before untouched. The deposit is protected.\n\nRepairs include the sound roof. After untouched.');
 await page.evaluate(()=>window.__jtApp.follow('Repairs include the sound roof'));
 assert.equal(await page.evaluate(()=>window.__jtApp.currentBlock()),1);
 await speak('start highlighting from the deposit');
 assert.equal(await page.evaluate(()=>window.__jtApp.currentBlock()),0,'cursor points at the saved start');
 assert.match(await page.$eval('#status-text',n=>n.textContent),/start saved/i);
 assert.equal(await count(),0,'arming is not an edit');
 assert.equal(await page.$eval('#voice-heard',n=>n.textContent),'Heard: start highlighting from the deposit');
 assert.match(await page.$eval('#voice-feedback',n=>n.textContent),/until/);
 await page.evaluate(()=>window.scrollTo(0,document.body.scrollHeight));
 assert.equal(await page.$eval('#voice-feedback',n=>{const r=n.getBoundingClientRect();return r.top>=0&&r.bottom<=innerHeight&&r.left>=0&&r.right<=innerWidth;}),true,'feedback remains visible while reading below the start');
 await page.setViewport({width:390,height:844});
 assert.equal(await page.$eval('#voice-feedback',n=>{const r=n.getBoundingClientRect();return r.top>=0&&r.bottom<=innerHeight&&r.left>=0&&r.right<=innerWidth;}),true,'feedback fits a narrow screen');
 await page.setViewport({width:1280,height:900});
 await speak('Repairs include the sound roof');
 await speak('till the sound roof');
 assert.equal(await count(),1,'separate utterances produce one range');
 assert.deepEqual(await page.evaluate(()=>window.__jtApp.entries().find(e=>e.kind==='act').resolvedSegments.map(s=>s.quotedText)),['The deposit is protected','Repairs include the sound roof']);
 await page.reload();await page.waitForFunction(()=>window.__jtApp?.booted);
 assert.equal(await count(),1,'range persists');
 await speak('undo');assert.equal(await count(),0,'one undo removes the entire range');
 await speak('start highlighting from the deposit');await speak('cancel selection');await speak('till the sound roof');assert.equal(await count(),0,'cancel prevents later endpoint');
 await speak('start highlighting from the deposit');await page.keyboard.press('Escape');await speak('till the sound roof');assert.equal(await count(),0,'Escape cancels');
 await speak('start highlighting from the deposit');
 await add('The deposit is protected. Repairs include the sound roof.');await speak('till the sound roof');assert.equal(await count(),0,'switching documents cancels');
 await speak('start highlighting from the deposit');await speak('till missing endpoint');assert.equal(await count(),0,'unknown endpoint does not guess');
 await speak('till the sound roof');assert.equal(await count(),1,'unknown endpoint can be retried');
 await add('Start phrase first finish phrase. Start phrase second finish phrase.');
 await speak('start highlighting from start phrase');assert.equal(await count(),0);
 await speak('till finish phrase');assert.equal(await count(),0,'repeated endpoints require a choice');
 await page.locator('#ask-options .range-ask:nth-child(2)').click();
 await page.locator('#ask-options .range-ask:nth-child(2)').click();
 await page.waitForFunction(()=>window.__jtApp.entries().some(e=>e.kind==='act'&&!e.undone));assert.equal(await count(),1);
 assert.equal(await page.evaluate(()=>window.__jtApp.entries().find(e=>e.kind==='act').anchor.quotedText),'Start phrase second finish phrase');
 await add('The deposit is protected. End with the sound roof.');
 await page.evaluate(()=>Promise.all([window.__jtApp.voiceSegment('start highlighting from the deposit'),window.__jtApp.voiceSegment('till the sound roof')]));
 assert.equal(await count(),1,'batched recognition preserves command order');
 await add('The deposit is held securely.\n\nUntil repairs are complete rent remains due.');
 await page.evaluate(()=>window.__jtApp.follow('The deposit is held securely'));
 await speak('The deposit is held securely');
 await page.evaluate(()=>window.__jtApp.follow('Until repairs are complete rent remains due'));
 assert.equal(await page.$eval('#marker',n=>n.classList.contains('on')),true,'ordinary until prose still follows');
 await speak('Until repairs are complete rent remains due');assert.equal(await count(),0);
 await speak('highlight this');
 assert.equal(await page.evaluate(()=>window.__jtApp.entries().find(e=>e.kind==='act').blockIndex),1,'until prose refreshes the subsequent command target');
 await add('The deposit is held until the sound roof is repaired.');
 await speak('start highlighting from the deposit');
 await page.locator('#cancel-voice-selection').click();
 await speak('till the sound roof');assert.equal(await count(),0,'visible cancel button cancels');
 await speak('start highlighting from the deposit');
 await page.evaluate(async()=>{
   const doc=structuredClone(window.__jtApp.currentDoc());
   doc.text='The deposit has changed. End with the sound roof.';
   doc.blocks=doc.blocks.map(b=>({...b,text:doc.text}));
   await window.__jtApp.openDocument(doc);
 });
 await speak('till the sound roof');assert.equal(await count(),0,'same document source replacement cancels');
 await add('Read the deposit carefully. End with the sound roof.');
 await page.evaluate(()=>window.__jtApp.follow('the deposit'));
 await speak('start highlighting here');await speak('until the sound roof');assert.equal(await count(),1,'here uses the cursor selection');
});
