import test from 'node:test';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import path from 'node:path';
import puppeteer from 'puppeteer-core';
import {root} from './validate.mjs';

test('Studio exact markup, redo and real crop preserve PDF source and native content',{timeout:120000},async t=>{
 const server=spawn(process.execPath,[path.join(root,'node_modules/vite/bin/vite.js'),'--host','127.0.0.1','--port','5191','--strictPort'],{cwd:root,stdio:'ignore'});t.after(()=>server.kill());for(let i=0;i<100;i++){try{if((await fetch('http://127.0.0.1:5191')).ok)break;}catch{}await new Promise(r=>setTimeout(r,100));}
 const browser=await puppeteer.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});t.after(async()=>{await Promise.race([browser.close(),new Promise(r=>setTimeout(()=>{browser.process()?.kill('SIGKILL');browser.disconnect();r();},3000))]);});const page=await browser.newPage();await page.setViewport({width:390,height:844});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const click=async s=>{t.diagnostic('Click '+s);await page.waitForSelector(s,{visible:true});await page.$eval(s,e=>e.scrollIntoView({block:'center',behavior:'instant'}));await page.locator(s).click();};
 await page.goto('http://127.0.0.1:5191/studio/index.html#files');await page.waitForFunction(()=>document.querySelector('#real-status')?.textContent==='Your PDF will be stored in this browser.');await click('[data-doc-action="sample"]');await page.waitForFunction(()=>document.querySelector('#real-status')?.textContent.startsWith('Opened')).catch(async e=>{throw new Error(e.message+' '+await page.$eval('main',e=>e.textContent)+' '+errors);});
 const original=await page.evaluate(async()=>{const d=(await(await import('/src/db.js')).getDocs())[0];return{id:d.id,bytes:Array.from(d.sourceBytes)};});await page.waitForSelector('.real-selectable-text [data-pdf-char-start]');await click('[data-doc-action="markup-panel"]');await page.locator('#pdf-find-query').fill('orchard gate');await click('#pdf-find-form button');await click('[data-find-result="0"]');await click('#pdf-mark-apply');await page.waitForFunction(()=>document.querySelector('#pdf-mark-status')?.textContent.startsWith('Markup saved'));
 assert.ok(await page.$('.real-selectable-text mark'));await click('#pdf-mark-undo');await page.waitForFunction(()=>document.querySelector('#pdf-mark-status')?.textContent==='Markup undone.');assert.equal(await page.$('.real-selectable-text mark'),null);await click('#pdf-mark-redo');await page.waitForFunction(()=>document.querySelector('#pdf-mark-status')?.textContent==='Markup restored.');assert.ok(await page.$('.real-selectable-text mark'));
 await page.evaluate(()=>{const span=document.querySelector('.real-selectable-text [data-pdf-char-start]');const range=document.createRange();range.selectNodeContents(span);const selection=window.getSelection();selection.removeAllRanges();selection.addRange(range);document.dispatchEvent(new Event('selectionchange'));});await page.select('#pdf-mark-style','underline');await click('#pdf-mark-apply');await page.waitForFunction(()=>document.querySelector('#pdf-mark-status')?.textContent.startsWith('Markup saved'));
 await page.screenshot({path:'/tmp/jetty-experience-review/highlighter-phone.png'});await page.reload();await page.waitForSelector('.real-selectable-text mark');await click('[data-doc-action="export-panel"]');await click('[data-doc-action="save-copy"]');await page.waitForFunction(()=>document.querySelector('#real-title')?.textContent.includes('reviewed'));
 const reviewed=await page.evaluate(async()=>{const {getDoc}=await import('/src/db.js');const d=await getDoc(location.hash.split('/')[1]);return{id:d.id,bytes:Array.from(d.sourceBytes)};});const mupdf=await import('mupdf');let d=mupdf.Document.openDocument(new Uint8Array(reviewed.bytes),'application/pdf'),p=d.loadPage(0),a=p.getAnnotations();assert.ok(a.some(x=>x.getType()==='Highlight'));assert.ok(a.some(x=>x.getType()==='Underline'));a.forEach(x=>x.destroy());p.destroy();d.destroy();
 await click('[data-doc-action="pages-panel"]');await click('[data-doc-action="crop"]');await page.locator('#real-crop-left').fill('30');await page.locator('#real-crop-top').fill('30');await page.locator('#real-crop-right').fill('30');await page.locator('#real-crop-bottom').fill('30');await page.screenshot({path:'/tmp/jetty-experience-review/crop-phone.png'});await click('[data-doc-action="apply-crop"]');await page.waitForFunction(()=>document.querySelector('#real-title')?.textContent.includes('cropped'));
 const cropped=await page.evaluate(async()=>{const {getDoc}=await import('/src/db.js');return Array.from((await getDoc(location.hash.split('/')[1])).sourceBytes);});d=mupdf.Document.openDocument(new Uint8Array(cropped),'application/pdf');p=d.loadPage(0);const bounds=p.getBounds();const old=mupdf.Document.openDocument(new Uint8Array(reviewed.bytes),'application/pdf'),oldPage=old.loadPage(0),before=oldPage.getBounds();assert.ok(Math.abs(bounds[2]-bounds[0]-(before[2]-before[0]-60))<.01);assert.ok(Math.abs(bounds[3]-bounds[1]-(before[3]-before[1]-60))<.01);a=p.getAnnotations();assert.ok(a.some(x=>x.getType()==='Highlight'));assert.ok(a.some(x=>x.getType()==='Underline'));a.forEach(x=>x.destroy());p.destroy();d.destroy();oldPage.destroy();old.destroy();assert.deepEqual(await page.evaluate(async id=>Array.from((await(await import('/src/db.js')).getDoc(id)).sourceBytes),original.id),original.bytes);assert.deepEqual(errors,[]);
});
