import test from 'node:test';import assert from 'node:assert/strict';import {spawn} from 'node:child_process';import path from 'node:path';import puppeteer from 'puppeteer-core';import {root} from './validate.mjs';
test('Jetty onboarding, accessible contextual work, and explicitly simulated tender outcome',{timeout:90000},async t=>{
 const server=spawn(process.execPath,[path.join(root,'node_modules/vite/bin/vite.js'),'--host','127.0.0.1','--port','5196','--strictPort'],{cwd:root,stdio:'ignore'});t.after(()=>server.kill());for(let i=0;i<100;i++){try{if((await fetch('http://127.0.0.1:5196')).ok)break;}catch{}await new Promise(r=>setTimeout(r,100));}
 const browser=await puppeteer.launch({executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});t.after(()=>browser.close());const page=await browser.newPage();await page.setViewport({width:390,height:844});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:5196/studio/index.html#welcome');
 await page.locator('a[href="#start"]').click();await page.locator('[data-a="onboard-next"]').click();await page.locator('#a-name').fill('Ari');await page.locator('[data-a="onboard-next"]').click();await page.locator('[data-a="onboard-finish"]').click();await page.waitForSelector('.a-document');
 await page.locator('[data-a="mark"]').click();assert.ok(await page.$('.a-quote.a-marked'));await page.locator('[data-a="select-passage"]').click();await page.waitForSelector('.a-answer');assert.equal(await page.$eval('.a-citation',e=>document.activeElement===e),true);await page.locator('[data-a="keep-answer"]').click();assert.ok(await page.$('.a-kept-answer'));await page.locator('#a-note').fill('Check the shade at 3 pm.');await page.reload();await page.waitForSelector('#a-note');assert.equal(await page.$eval('#a-note',e=>e.value),'Check the shade at 3 pm.');
 await page.locator('[data-tab="notes"]').click();await page.keyboard.press('ArrowRight');assert.equal(await page.$eval('[data-tab="jetty"]',e=>e.getAttribute('aria-selected')),'true');
 await page.locator('[data-a="share"]').click();await page.waitForSelector('.a-dialog[open]');await page.keyboard.press('Escape');await page.waitForFunction(()=>!document.querySelector('.a-dialog[open]')&&document.activeElement?.dataset.a==='share');assert.equal(await page.$eval('[data-a="share"]',e=>document.activeElement===e),true);
 await page.goto('http://127.0.0.1:5196/studio/index.html#tender');await page.locator('[data-a="add-certificate"]').click();await page.locator('a[href="#review"]').click();await page.waitForSelector('[data-a="signature"]');assert.equal(await page.$eval('[data-a="signature"]',e=>e.disabled),true);await page.locator('#a-cost').click();await page.locator('#a-signature').click();await page.locator('[data-a="signature"]').click();await page.locator('[data-a="finish-signature"]').click();await page.waitForSelector('[data-a="outcome"]');assert.match(await page.$eval('main',e=>e.textContent),/No signature, portal access, or submission occurred/);await page.$eval('[data-a="outcome"]',e=>e.scrollIntoView({block:'center'}));await page.locator('[data-a="outcome"]').click();await page.waitForFunction(()=>document.querySelector('main')?.textContent.includes('Illustrated / not submitted'),{timeout:5000});assert.match(await page.$eval('main',e=>e.textContent),/Illustrated \/ not submitted/);
 t.diagnostic('Outcome reached');for(const route of ['welcome','start','desk','canvas','services','tender','review','receipt','shelf','files']){t.diagnostic('Review route '+route);await page.goto('http://127.0.0.1:5196/studio/index.html#'+route);await page.waitForFunction(r=>document.title===`Jetty / ${r==='canvas'?'River Library':r.charAt(0).toUpperCase()+r.slice(1)}`,{timeout:5000},route);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),route);assert.equal(await page.$$eval('main h1',e=>e.length),1,route);}
 await page.locator('[data-a="theme"]').click();assert.equal(await page.$eval('.atelier',e=>e.dataset.theme),'dark');assert.deepEqual(errors,[]);
});
