import test from 'node:test';import assert from 'node:assert/strict';import * as m from 'mupdf';import {spawn} from 'node:child_process';import path from 'node:path';import puppeteer from 'puppeteer-core';import {root} from './validate.mjs';
function fixture(){const d=new m.PDFDocument(),pix=new m.Pixmap(m.ColorSpace.DeviceRGB,[0,0,4,4],false);pix.clear(90);const image=new m.Image(pix),ref=d.addImage(image),font=new m.Font('Helvetica'),fr=d.addSimpleFont(font);try{const p=d.addPage([0,0,300,400],0,{XObject:{Im:ref}},'q 80 0 0 60 30 240 cm /Im Do Q');d.insertPage(-1,p);p.destroy();const q=d.addPage([0,0,300,400],0,{Font:{F1:fr}},'BT /F1 12 Tf 30 350 Td (Keep these words.) Tj ET');d.insertPage(-1,q);q.destroy();const b=d.saveToBuffer();try{return Array.from(b.asUint8Array());}finally{b.destroy();}}finally{fr.destroy();font.destroy();ref.destroy();image.destroy();pix.destroy();d.destroy();}}
function read(bytes){const d=new m.PDFDocument(new Uint8Array(bytes));try{const p=d.loadPage(0),s=p.toStructuredText('preserve-images'),images=[];s.walk({onImageBlock:(bounds,_t,image)=>{const pix=image.toPixmap();try{images.push({bounds:[...bounds],width:image.getWidth(),pixel:Array.from(pix.getPixels().slice(0,3))});}finally{pix.destroy();}}});s.destroy();p.destroy();return images[0];}finally{d.destroy();}}
test('image panel creates native moved, resized and replaced PDFs and recovers refused inputs',{timeout:120000},async t=>{
 const server=spawn(process.execPath,[path.join(root,'node_modules/vite/bin/vite.js'),'--host','127.0.0.1','--port','4997','--strictPort'],{cwd:root,stdio:'ignore'});t.after(()=>server.kill());for(let i=0;i<100;i++){try{if((await fetch('http://127.0.0.1:4997')).ok)break;}catch{}await new Promise(r=>setTimeout(r,100));}
 const browser=await puppeteer.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});t.after(async()=>{const timer=setTimeout(()=>browser.process()?.kill('SIGKILL'),3000);try{await browser.close();}finally{clearTimeout(timer);}});const page=await browser.newPage();await page.setViewport({width:390,height:844});await page.goto('http://127.0.0.1:4997/notebooks/design/tokens.json');const original=fixture();
 await page.evaluate(async bytes=>{const m=await import('/studio/image-tools.js');const css=document.createElement('link');css.rel='stylesheet';css.href='/studio/image-tools.css';document.head.append(css);document.body.innerHTML=m.imageToolsView();location.hash='#editor/image-proof/1';window.outputs=[];window.physicalPage=0;window.source={id:'image-proof',revision:1,title:'Image proof',sourceBytes:bytes};window.panel=m.mountImageTools({host:document.body,source,getPage:()=>physicalPage,createCopy:async(bytes,title,operation)=>{if(window.failSave)throw new Error('Storage is full');outputs.push({bytes:Array.from(bytes),title,operation});}});},original);await page.waitForFunction(()=>document.querySelector('[data-image-status]').dataset.state==='ready');
 await page.screenshot({path:'/tmp/jetty-image-tools-mobile.png',fullPage:true});
 const apply=async(action,count)=>{await page.click(`[data-image-action="${action}"]`);await page.waitForFunction(n=>outputs.length===n&&!panel.pending(),{},count);};
 await page.locator('[name="image-x"]').fill('130');await apply('move',1);await page.locator('[name="image-width"]').fill('100');await page.locator('[name="image-height"]').fill('80');await apply('resize',2);
 const upload=async transparent=>page.evaluate(async transparent=>{const c=document.createElement('canvas');c.width=2;c.height=2;const ctx=c.getContext('2d');ctx.fillStyle=transparent?'rgba(220,20,40,.5)':'rgb(220,20,40)';ctx.fillRect(0,0,2,2);const blob=await new Promise(resolve=>c.toBlob(resolve,'image/png'));const dt=new DataTransfer();dt.items.add(new File([blob],'replacement.png',{type:'image/png'}));const input=document.querySelector('[name="image-file"]');input.files=dt.files;input.dispatchEvent(new Event('change',{bubbles:true}));},transparent);
 await upload(true);await page.click('[data-image-action="replace"]');await page.waitForFunction(()=>!panel.pending()&&document.querySelector('[data-image-status]').textContent.includes('transparent'));assert.equal(await page.evaluate(()=>outputs.length),2);await upload(false);await apply('replace',3);
 const proof=await page.evaluate(()=>({outputs,bytes:source.sourceBytes}));assert.deepEqual(proof.bytes,original);assert.deepEqual(read(proof.outputs[0].bytes).bounds,[130,100,210,160]);assert.deepEqual(read(proof.outputs[1].bytes).bounds,[30,100,130,180]);assert.equal(read(proof.outputs[2].bytes).width,2);assert.deepEqual(read(proof.outputs[2].bytes).pixel,[220,20,40]);
 await page.evaluate(()=>{window.failSave=true;});await page.click('[data-image-action="move"]');await page.waitForFunction(()=>!panel.pending()&&document.querySelector('[data-image-status]').textContent.includes('Storage is full'));await page.evaluate(()=>{window.failSave=false;});
 await page.evaluate(()=>{document.querySelector('[data-image-action="move"]').click();physicalPage=1;document.dispatchEvent(new Event('jetty-editor-page'));});await page.waitForFunction(()=>!panel.pending());assert.equal(await page.evaluate(()=>outputs.length),3);await page.click('[data-image-action="inspect"]');await page.waitForFunction(()=>!panel.pending()&&document.querySelector('[data-image-status]').dataset.state==='error');assert.match(await page.$eval('[data-image-status]',e=>e.textContent),/single image|mixed|text/i);assert.equal(await page.$eval('[data-image-controls]',e=>e.hidden),true);
 await page.evaluate(()=>{physicalPage=0;document.dispatchEvent(new Event('jetty-editor-page'));});await page.click('[data-image-action="inspect"]');await page.waitForFunction(()=>document.querySelector('[data-image-status]').dataset.state==='ready');await page.evaluate(()=>{document.querySelector('[data-image-action="move"]').click();location.hash='#editor/another/1';location.hash='#editor/image-proof/1';});await new Promise(r=>setTimeout(r,350));assert.equal(await page.evaluate(()=>outputs.length),3);await page.evaluate(()=>panel.dispose());assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
});
