import test from 'node:test';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import path from 'node:path';
import puppeteer from 'puppeteer-core';
import {root} from './validate.mjs';

test('Jetty local PDF import, text, ink, persistence, reviewed copy and original custody', {timeout:120000}, async t=>{
 const server=spawn(process.execPath,[path.join(root,'node_modules/vite/bin/vite.js'),'--host','127.0.0.1','--port','5197','--strictPort'],{cwd:root,stdio:'ignore'});t.after(()=>server.kill());
 for(let i=0;i<100;i++){try{if((await fetch('http://127.0.0.1:5197')).ok)break;}catch{}await new Promise(r=>setTimeout(r,100));}
 const browser=await puppeteer.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});t.after(async()=>{const timer=setTimeout(()=>browser.process()?.kill('SIGKILL'),3000);try{await browser.close();}finally{clearTimeout(timer);}});const page=await browser.newPage();await page.setViewport({width:390,height:844});const click=async selector=>{await page.waitForSelector(selector,{visible:true});await page.$eval(selector,e=>e.scrollIntoView({block:'center',behavior:'instant'}));await page.locator(selector).click();};const errors=[];page.on('pageerror',e=>errors.push(e.stack));
 await page.goto('http://127.0.0.1:5197/studio/index.html#files');t.diagnostic('Library loaded');await page.waitForFunction(()=>document.querySelector('#real-status')?.textContent==='Your PDF will be stored in this browser.');await click('[data-doc-action="sample"]');await page.waitForSelector('#real-text').catch(async e=>{throw new Error(e.message+' '+await page.$eval('main',n=>n.textContent));});t.diagnostic('PDF opened');await page.waitForFunction(()=>document.querySelector('#real-status')?.textContent.startsWith('Opened from'));page.on('framenavigated',f=>{if(f===page.mainFrame())t.diagnostic('Navigation: '+f.url());});
 const original=await page.evaluate(async()=>{const {getDocs}=await import('/src/db.js');const d=(await getDocs())[0];return{id:d.id,bytes:Array.from(d.sourceBytes),text:d.text};});
 t.diagnostic('Before text fill');await click('[data-doc-action="focus-text"]');await page.locator('#real-text').fill('Reviewed by Ari');
 await click('[data-doc-action="export-panel"]');await click('.real-more summary');await page.locator('#real-place').fill('Orchard gate');await click('[data-doc-action="next"]');await page.waitForFunction(()=>document.querySelector('#real-page-num')?.textContent==='Page 2 of 3');await click('[data-doc-action="zoom-in"]');await click('[data-a="theme"]');assert.equal(await page.$eval('#real-text',e=>e.value),'Reviewed by Ari');assert.equal(await page.$eval('#real-place',e=>e.value),'Orchard gate');assert.equal(await page.$eval('#real-page-num',e=>e.textContent),'Page 2 of 3');assert.equal(await page.$eval('.real-paper',e=>e.style.width),'125%');await click('[data-doc-action="previous"]');await page.waitForFunction(()=>document.querySelector('#real-page-num')?.textContent==='Page 1 of 3');
await click('[data-doc-action="focus-text"]');await click('#real-text-form button[type="submit"]');
 await page.waitForFunction(()=>document.getElementById('real-mark-count')?.textContent.includes('1 text annotations'),{timeout:5000}).catch(async e=>{throw new Error(e.message+' '+JSON.stringify(await page.evaluate(()=>({status:document.querySelector('#real-status').textContent,handler:typeof document.querySelector('#real-text-form').onsubmit,href:location.href})))+' '+errors.join(','));});
 await click('[data-doc-action="export-panel"]');await click('[data-doc-action="share-file"]');await page.waitForFunction(()=>document.querySelector('#real-status')?.textContent.includes('Save a reviewed copy first'));assert.match(await page.$eval('#real-status',e=>e.textContent),/Save a reviewed copy first/);t.diagnostic('Sharing gated');await page.reload();await page.waitForFunction(()=>document.getElementById('real-mark-count')?.textContent.includes('1 text annotations'));
 await page.evaluate(()=>{const put=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(value,key){if(String(key).startsWith('studio-ink:')){IDBObjectStore.prototype.put=put;throw new DOMException('Simulated quota failure','QuotaExceededError');}return put.call(this,value,key);};});await click('[data-doc-action="ink"]');const box=await page.$eval('#real-ink',el=>{const r=el.getBoundingClientRect();return{x:r.x,y:r.y,w:r.width,h:r.height};});await page.mouse.move(box.x+50,box.y+100);await page.mouse.down();await page.mouse.move(box.x+100,box.y+120,{steps:6});await page.mouse.up();await page.waitForFunction(()=>document.getElementById('real-mark-count')?.textContent.includes('1 ink strokes'));
 t.diagnostic('Ink remains visible after quota failure');await page.waitForSelector('[data-doc-action="retry-save"]:not([hidden])');assert.equal(await page.$$eval('#real-ink polyline',e=>e.length),1);await click('[data-doc-action="retry-save"]');await page.waitForSelector('[data-doc-action="retry-save"][hidden]');await click('[data-doc-action="export-panel"]');await click('[data-doc-action="save-copy"]');await page.waitForFunction(()=>document.getElementById('real-title')?.textContent.includes('reviewed'),{timeout:30000});
 const proof=await page.evaluate(async id=>{const {getDocs,getDoc}=await import('/src/db.js');const docs=await getDocs();return {source:Array.from((await getDoc(id)).sourceBytes),copies:docs.filter(d=>d.provenance?.derivedFrom?.documentId===id).map(d=>({id:d.id,bytes:Array.from(d.sourceBytes),text:d.text}))};},original.id);
 assert.deepEqual(proof.source,original.bytes);assert.equal(proof.copies.length,1);assert.match(proof.copies[0].text,/orchard gate/);assert.notDeepEqual(proof.copies[0].bytes,original.bytes);
 const mupdf=await import('mupdf');const doc=mupdf.Document.openDocument(new Uint8Array(proof.copies[0].bytes),'application/pdf');const pdfPage=doc.loadPage(0);const annotations=pdfPage.getAnnotations();assert.ok(annotations.some(a=>a.getType()==='Ink'));const color=annotations.find(a=>a.getType()==='Ink').getColor();assert.ok(color.every((c,i)=>Math.abs(c-[54/255,92/255,205/255][i])<.001));assert.ok(annotations.some(a=>a.getType()==='FreeText'&&a.getContents()==='Reviewed by Ari'));for(const a of annotations)a.destroy();pdfPage.destroy();doc.destroy();
 await page.reload();await page.waitForSelector('#real-canvas');assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.goto('http://127.0.0.1:5197/studio/index.html#files');await page.waitForSelector('#real-file-input');const input=await page.$('#real-file-input');await input.uploadFile(path.join(root,'test/fixtures/jett-annotations.pdf'));await page.waitForFunction(()=>document.querySelector('#real-title')?.textContent==='jett-annotations'&&document.querySelector('#real-page-num')?.textContent==='Page 1 of 3');assert.match(await page.$eval('#real-structured-text',e=>e.textContent),/no extracted text/);assert.deepEqual(errors,[]);
});
