import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import * as mupdf from 'mupdf';
import {beginNativePrint} from '../studio/native-print.js';
const source=new Uint8Array(readFileSync(new URL('./fixtures/jett-annotations.pdf',import.meta.url)));
function env(){const calls=[],events=[],target=new EventTarget();return {calls,events,target,bridge:{print:(...args)=>calls.push(['print',...args]),write:(...args)=>calls.push(['write',...args]),fail:(...args)=>calls.push(['fail',...args])},onStatus:e=>events.push(e)};}
function start(e,bytes=source){return beginNativePrint(bytes,'Proof.pdf',{bridge:e.bridge,onStatus:e.onStatus,eventTarget:e.target});}
const finish=c=>c.handleEvent({status:'finished',message:'Print dialog closed',terminal:true});
test('freezes source, serializes print sessions and supplies exact selected PDF pages',async()=>{const e=env(),input=source.slice(),c=start(e,input);input.fill(0);assert.deepEqual(Buffer.from(e.calls[0][1],'base64'),Buffer.from(source));assert.throws(()=>start(env()),{code:'PRINT_BUSY'});await c.handleEvent({status:'pages-requested',requestId:1,ranges:[{start:1,end:2}]});const call=e.calls.find(c=>c[0]==='write');assert.equal(call[1],1);const d=new mupdf.PDFDocument(new Uint8Array(Buffer.from(call[2],'base64')));try{assert.equal(d.countPages(),2);const p=d.loadPage(0),t=p.toStructuredText();try{assert.match(t.asText(),/orchard/);}finally{t.destroy();p.destroy();}}finally{d.destroy();}assert.equal(c.pending,true);assert.throws(()=>c.cleanup(),{code:'PRINT_PENDING'});finish(c);assert.equal(c.pending,false);c.cleanup();});
test('invalid or overlapping ranges fail request without releasing the session',async()=>{const e=env(),c=start(e);try{for(const [i,ranges]of [[{start:0,end:Infinity}],[{start:0,end:1},{start:1,end:2}],[{start:2,end:1}],[{start:99,end:99}],[]].entries())await c.handleEvent({status:'pages-requested',requestId:i+1,ranges});assert.equal(e.calls.filter(c=>c[0]==='fail').length,5);assert.equal(c.pending,true);await c.handleEvent({status:'pages-requested',requestId:'bad id?',ranges:[[0,0]]});assert.equal(e.calls.filter(c=>c[0]==='write').length,0);}finally{finish(c);}});
test('terminal or new session prevents stale extraction callbacks',async()=>{const e=env(),c=start(e),pending=c.handleEvent({status:'pages-requested',requestId:1,ranges:[[1,1]]});await Promise.resolve();finish(c);const next=env(),d=start(next);await pending;assert.equal(e.calls.filter(c=>c[0]==='write'||c[0]==='fail').length,0);assert.equal(next.calls.length,1);finish(d);});
test('event subscription, duplicate request IDs and startup failure are safe',async()=>{const e=env(),c=start(e);e.target.dispatchEvent(new CustomEvent('jetty-native-print',{detail:{status:'waiting',message:'Choose pages',terminal:false}}));assert.equal(e.events.at(-1).message,'Choose pages');await c.handleEvent({status:'pages-requested',requestId:7,ranges:[[0,0]]});await c.handleEvent({status:'pages-requested',requestId:7,ranges:[[0,0]]});assert.equal(e.calls.filter(c=>c[0]==='write').length,1);finish(c);const bad=env();bad.bridge.print=()=>{throw Error('bridge unavailable');};assert.throws(()=>start(bad),/bridge unavailable/);const after=start(env());finish(after);});
test('unsupported extraction fails native request and preserves session until terminal',async()=>{const e=env(),bytes=new Uint8Array(readFileSync(new URL('./fixtures/jett-fillable.pdf',import.meta.url))),c=start(e,bytes);try{await c.handleEvent({status:'pages-requested',requestId:'subset_1',ranges:[[0,0]]});assert.deepEqual(e.calls.at(-1),['fail','subset_1']);assert.equal(c.pending,true);assert.equal(e.events.at(-1).status,'error');}finally{finish(c);}});
test('newer page request supersedes awaited extraction and emits only its subset',async()=>{const e=env(),c=start(e);try{const first=c.handleEvent({status:'pages-requested',requestId:1,ranges:[[1,1]]});await Promise.resolve();const second=c.handleEvent({status:'pages-requested',requestId:2,ranges:[[2,2]]});await Promise.all([first,second]);assert.deepEqual(e.calls.filter(x=>x[0]==='write').map(x=>x[1]),[2]);}finally{finish(c);}});
