import test from 'node:test';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import path from 'node:path';
import puppeteer from 'puppeteer-core';
import {root} from './validate.mjs';

test('Studio page actions save derived PDFs and return to a previous version',{timeout:120000},async t=>{
 const server=spawn(process.execPath,[path.join(root,'node_modules/vite/bin/vite.js'),'--host','127.0.0.1','--port','5194','--strictPort'],{cwd:root,stdio:'ignore'});t.after(()=>server.kill());for(let i=0;i<100;i++){try{if((await fetch('http://127.0.0.1:5194')).ok)break;}catch{}await new Promise(r=>setTimeout(r,100));}
 const browser=await puppeteer.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});t.after(async()=>{await Promise.race([browser.close(),new Promise(r=>setTimeout(()=>{browser.process()?.kill('SIGKILL');browser.disconnect();r();},3000))]);});const page=await browser.newPage();await page.setViewport({width:390,height:844});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const click=async s=>{t.diagnostic('Click '+s);await page.waitForSelector(s,{visible:true});await page.$eval(s,e=>e.scrollIntoView({block:'center',behavior:'instant'}));await page.locator(s).click();};
 await page.goto('http://127.0.0.1:5194/studio/index.html#files');await page.waitForFunction(()=>document.querySelector('#real-status')?.textContent==='Your PDF will be stored in this browser.');await click('[data-doc-action="sample"]');await page.waitForFunction(()=>document.querySelector('#real-status')?.textContent.startsWith('Opened')).catch(async e=>{throw new Error(e.message+' '+await page.$eval('main',e=>e.textContent)+' '+errors);});


 const sourceId=await page.evaluate(()=>location.hash.split('/')[1]);await click('[data-doc-action="pages-panel"]');await click('[data-doc-action="organize"]');await click('[data-page-action="rotate"]');await page.waitForFunction(()=>document.querySelector('#real-title')?.textContent.includes('rotated'));const rotated=await page.evaluate(async()=>Array.from((await(await import('/src/db.js')).getDoc(location.hash.split('/')[1])).sourceBytes));const m=await import('mupdf');let pdf=new m.PDFDocument(new Uint8Array(rotated)),p=pdf.loadPage(0),o=p.getObject(),r=o.get('Rotate');assert.equal(r.asNumber(),90);r.destroy();o.destroy();p.destroy();pdf.destroy();
 await click('[data-doc-action="pages-panel"]');await click('[data-doc-action="organize"]');await page.locator('[name="page-order"]').fill('3,1,2');await page.screenshot({path:'/tmp/jetty-experience-review/organize-phone.png'});await click('[data-page-action="reorder"]');await page.waitForFunction(()=>document.querySelector('#real-title')?.textContent.includes('reordered'));await click('[data-doc-action="pages-panel"]');await click('[data-doc-action="organize"]');await page.locator('[name="page-selection"]').fill('1');await click('[data-page-action="extract"]');await page.waitForFunction(()=>document.querySelector('#real-title')?.textContent.includes('selected pages')).catch(async error=>{throw new Error(error.message+' '+await page.$eval('main',e=>e.textContent)+' '+errors);});assert.ok(await page.$eval('.real-page-label',e=>e.textContent.includes('of 1')));await click('[data-doc-action="export-panel"]');await click('.real-more summary');await click('[data-doc-action="previous-version"]');await page.waitForFunction(()=>document.querySelector('#real-title')?.textContent.includes('reordered')&&!document.querySelector('#real-title')?.textContent.includes('selected pages'));assert.deepEqual(errors,[]);
});
