import {prepareStudioControl} from './helpers/studio-controls.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {mkdir} from 'node:fs/promises';
import path from 'node:path';
import puppeteer from 'puppeteer-core';
import {root} from './validate.mjs';

test('focused editor keeps page orientation, direct text placement, tools and recovery visible',{timeout:120000},async t=>{
 const server=spawn(process.execPath,[path.join(root,'node_modules/vite/bin/vite.js'),'--host','127.0.0.1','--port','5193','--strictPort'],{cwd:root,stdio:'ignore'});t.after(()=>server.kill());
 for(let i=0;i<100;i++){try{if((await fetch('http://127.0.0.1:5193')).ok)break;}catch{}await new Promise(r=>setTimeout(r,100));}
 const browser=await puppeteer.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});t.after(async()=>{await Promise.race([browser.close(),new Promise(resolve=>setTimeout(()=>{browser.process()?.kill('SIGKILL');browser.disconnect();resolve();},3000))]);});
 const page=await browser.newPage();await page.setViewport({width:390,height:844});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const click=async s=>{await prepareStudioControl(page,s);if(['[data-doc-action="ink"]','[data-doc-action="focus-text"]'].includes(s))await page.locator('[data-doc-action="write-panel"]').click();if(s==='[data-doc-action="page-text"]')await page.locator('[data-doc-action="pages-panel"]').click();await page.waitForSelector(s,{visible:true});await page.$eval(s,e=>e.scrollIntoView({block:'center',behavior:'instant'}));await page.locator(s).click();};
 await page.goto('http://127.0.0.1:5193/studio/index.html#files');await page.waitForFunction(()=>document.querySelector('#real-status')?.textContent==='Your PDF will be stored in this browser.');await click('[data-doc-action="sample"]');await page.waitForFunction(()=>document.querySelector('#real-page-num')?.textContent==='Page 1 of 3',{timeout:15000}).catch(async e=>{throw new Error(e.message+' '+await page.$eval('main',e=>e.textContent)+' '+errors.join(','));});
 await mkdir('/tmp/jetty-experience-review',{recursive:true});await page.screenshot({path:'/tmp/jetty-experience-review/after-phone-reading.png'});
 assert.equal(await page.$$eval('.real-jelly',e=>e.length),1);assert.equal(await page.$eval('.real-context',e=>e.hidden),true);assert.ok(await page.$eval('#real-canvas',e=>e.getBoundingClientRect().top<180));assert.equal(await page.$eval('[data-doc-action="undo"]',e=>e.disabled),true);
 const source=await page.evaluate(async()=>{const {getDocs}=await import('/src/db.js');const d=(await getDocs())[0];return{id:d.id,bytes:Array.from(d.sourceBytes)};});
 await click('[data-doc-action="next"]');await page.waitForFunction(()=>document.querySelector('#real-page-input')?.value==='2');await page.reload();await page.waitForFunction(()=>document.querySelector('#real-page-input')?.value==='2');
 await click('[data-doc-action="zoom-in"]');assert.equal(await page.$eval('#real-zoom-value',e=>e.textContent),'125%');await click('[data-doc-action="focus-text"]');
 const target=await page.$eval('#real-ink',e=>{const r=e.getBoundingClientRect();return{x:r.x+90,y:r.y+95,pdfX:Math.round(90/r.width*+e.dataset.width),pdfY:Math.round(95/r.height*+e.dataset.height)};});
 await page.mouse.click(target.x,target.y);assert.equal(await page.$eval('#real-x',e=>+e.value),target.pdfX);assert.equal(await page.$eval('#real-y',e=>+e.value),target.pdfY);await page.locator('#real-text').fill('Meet at the orchard gate.');await page.screenshot({path:'/tmp/jetty-experience-review/after-phone-text.png'});await click('#real-text-form [type="submit"]');await page.waitForFunction(()=>document.querySelector('#real-ink text')?.textContent==='Meet at the orchard gate.');
 assert.equal(await page.$eval('.real-context',e=>e.hidden),true);assert.equal(await page.$eval('[data-doc-action="read"]',e=>e.getAttribute('aria-pressed')),'true');assert.equal(await page.$eval('#real-ink text',e=>+e.getAttribute('x')),target.pdfX);
 await click('[data-doc-action="write-panel"]');await click('[data-doc-action="duplicate-last"]');await page.waitForFunction(()=>document.querySelectorAll('#real-ink text').length===2&&document.querySelector('#real-save-state')?.textContent==='Saved on this device');
 assert.deepEqual(await page.$$eval('#real-ink text',nodes=>nodes.map(n=>({text:n.textContent,x:+n.getAttribute('x'),y:+n.getAttribute('y')}))),[{text:'Meet at the orchard gate.',x:target.pdfX,y:target.pdfY+14},{text:'Meet at the orchard gate.',x:target.pdfX+12,y:target.pdfY+26}]);
 await page.reload();await page.waitForFunction(()=>document.querySelectorAll('#real-ink text').length===2);await page.keyboard.down('Control');await page.keyboard.press('z');await page.keyboard.up('Control');await page.waitForFunction(()=>document.querySelectorAll('#real-ink text').length===1);
 await click('[data-doc-action="ink"]');await click('[data-doc-color="plum"]');await page.select('#real-pen-width','4');await page.screenshot({path:'/tmp/jetty-experience-review/after-phone-pen.png'});const ink=await page.$eval('#real-ink',e=>{const r=e.getBoundingClientRect();return{x:r.x+30,y:r.y+45};});await page.mouse.move(ink.x,ink.y);await page.mouse.down();await page.mouse.move(ink.x+60,ink.y+20,{steps:8});await page.mouse.up();await page.waitForFunction(()=>document.querySelector('#real-save-state')?.textContent==='Saved on this device'&&document.querySelector('#real-ink polyline'));
 assert.equal(await page.$eval('#real-ink polyline',e=>e.getAttribute('stroke-width')),'4');await click('[data-doc-action="write-panel"]');await click('[data-doc-action="duplicate-last"]');await page.waitForFunction(()=>document.querySelectorAll('#real-ink polyline').length===2);
 const strokes=await page.$$eval('#real-ink polyline',nodes=>nodes.map(n=>n.getAttribute('points').split(' ').map(pair=>pair.split(',').map(Number))));assert.equal(strokes[1][0][0],strokes[0][0][0]+12);assert.equal(strokes[1][0][1],strokes[0][0][1]+12);
 await page.keyboard.down('Control');await page.keyboard.press('z');await page.keyboard.up('Control');await page.waitForFunction(()=>document.querySelectorAll('#real-ink polyline').length===1);await page.keyboard.down('Control');await page.keyboard.press('z');await page.keyboard.up('Control');await page.waitForFunction(()=>!document.querySelector('#real-ink polyline'));
 await click('[data-doc-action="read"]');await click('[data-doc-action="fit"]');assert.equal(await page.$eval('#real-zoom-value',e=>e.textContent),'100%');await click('[data-doc-action="page-text"]');assert.match(await page.$eval('#real-structured-text',e=>e.textContent),/./);await page.keyboard.press('Escape');assert.equal(await page.$eval('.real-context',e=>e.hidden),true);
 await click('[data-a="theme"]');await page.screenshot({path:'/tmp/jetty-experience-review/after-phone-dark.png'});await page.setViewport({width:1440,height:1000});await page.screenshot({path:'/tmp/jetty-experience-review/after-desktop-dark.png'});await click('[data-a="theme"]');await page.screenshot({path:'/tmp/jetty-experience-review/after-desktop-reading.png'});
 await click('[data-doc-action="export-panel"]');await page.screenshot({path:'/tmp/jetty-experience-review/after-desktop-export.png'});await click('[data-doc-action="save-copy"]');await page.waitForFunction(()=>document.querySelector('#real-title')?.textContent.includes('reviewed'));
 const proof=await page.evaluate(async id=>{const {getDoc,getDocs}=await import('/src/db.js');return{original:Array.from((await getDoc(id)).sourceBytes),copy:Array.from((await getDocs()).find(d=>d.provenance?.derivedFrom?.documentId===id).sourceBytes)};},source.id);assert.deepEqual(proof.original,source.bytes);
 const mupdf=await import('mupdf');const doc=mupdf.Document.openDocument(new Uint8Array(proof.copy),'application/pdf');const p=doc.loadPage(1);const annotations=p.getAnnotations();assert.ok(annotations.some(a=>a.getType()==='FreeText'&&a.getContents()==='Meet at the orchard gate.'));for(const a of annotations)a.destroy();p.destroy();doc.destroy();assert.deepEqual(errors,[]);
});
