import test from 'node:test';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import path from 'node:path';
import puppeteer from 'puppeteer-core';
import {root} from './validate.mjs';

test('Studio existing paragraph edit creates a verified copy and restores saved draft',{timeout:120000},async t=>{
 const server=spawn(process.execPath,[path.join(root,'node_modules/vite/bin/vite.js'),'--host','127.0.0.1','--port','5192','--strictPort'],{cwd:root,stdio:'ignore'});t.after(()=>server.kill());for(let i=0;i<100;i++){try{if((await fetch('http://127.0.0.1:5192')).ok)break;}catch{}await new Promise(r=>setTimeout(r,100));}
 const browser=await puppeteer.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});t.after(async()=>{await Promise.race([browser.close(),new Promise(r=>setTimeout(()=>{browser.process()?.kill('SIGKILL');browser.disconnect();r();},3000))]);});const page=await browser.newPage();await page.setViewport({width:390,height:844});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const click=async s=>{t.diagnostic('Click '+s);await page.waitForSelector(s,{visible:true});await page.$eval(s,e=>e.scrollIntoView({block:'center',behavior:'instant'}));await page.locator(s).click();};
 await page.goto('http://127.0.0.1:5192/studio/index.html#files');await page.waitForFunction(()=>document.querySelector('#real-status')?.textContent==='Your PDF will be stored in this browser.');await click('[data-doc-action="sample"]');await page.waitForFunction(()=>document.querySelector('#real-status')?.textContent.startsWith('Opened')).catch(async e=>{throw new Error(e.message+' '+await page.$eval('main',e=>e.textContent)+' '+errors);});

 const source=await page.evaluate(async()=>{const d=(await(await import('/src/db.js')).getDocs())[0];return{id:d.id,bytes:Array.from(d.sourceBytes)};});
 await click('[data-doc-action="write-panel"]');await click('[data-doc-action="edit-existing"]');await page.waitForFunction(()=>document.querySelector('#pdf-edit-paragraph')?.options.length>1);
 await page.select('#pdf-edit-paragraph','0');const originalText=await page.$eval('#pdf-edit-text',e=>e.value);assert.ok(originalText.length);const replacement=originalText.replace(/Before/,'After');assert.notEqual(replacement,originalText);await page.locator('#pdf-edit-text').fill(replacement);await page.waitForFunction(()=>document.querySelector('#pdf-edit-status')?.textContent.includes('saved'));
 await page.reload();await page.waitForFunction(()=>document.querySelector('#real-status')?.textContent.startsWith('Opened'));await click('[data-doc-action="write-panel"]');await click('[data-doc-action="edit-existing"]');assert.equal(await page.$eval('#pdf-edit-text',e=>e.value),replacement);
 await page.screenshot({path:'/tmp/jetty-experience-review/paragraph-controls-phone.png'});await click('#pdf-edit-review');await page.waitForFunction(()=>document.querySelector('#real-title')?.textContent.includes('edited'));
 const result=await page.evaluate(async()=>{const {getDoc}=await import('/src/db.js');const d=await getDoc(location.hash.split('/')[1]);return {text:d.text,source:d.provenance.derivedFrom.documentId};});assert.ok(result.text.includes(replacement));assert.equal(result.source,source.id);assert.deepEqual(await page.evaluate(async id=>Array.from((await(await import('/src/db.js')).getDoc(id)).sourceBytes),source.id),source.bytes);await click('[data-doc-action=write-panel]');await click('[data-doc-action=focus-text]');await page.setViewport({width:800,height:250});await page.focus('#real-text');const panelBounds=await page.$eval('#real-text-form',e=>{const input=e.querySelector('input').getBoundingClientRect(),button=e.querySelector('button').getBoundingClientRect();return {top:input.top,bottom:button.bottom,height:innerHeight};});assert.ok(panelBounds.top>=0&&panelBounds.bottom<=panelBounds.height,JSON.stringify(panelBounds));await page.screenshot({path:'/tmp/jetty-experience-review/keyboard-short-landscape.png'});await page.setViewport({width:390,height:844});await page.goto('http://127.0.0.1:5192/studio/index.html#guide');await page.waitForSelector('#pg-query');await page.locator('#pg-query').fill('LaTeX');assert.ok(await page.$eval('#pg-count',e=>e.textContent.includes('2')));assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:'/tmp/jetty-experience-review/product-guide-phone.png'});assert.deepEqual(errors,[]);await page.screenshot({path:'/tmp/jetty-experience-review/edited-paragraph-phone.png'});
});
