import test from 'node:test';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import path from 'node:path';
import puppeteer from 'puppeteer-core';
import {root} from './validate.mjs';

test('Studio form answers recover and write real fields into a separate PDF',{timeout:120000},async t=>{
 const server=spawn(process.execPath,[path.join(root,'node_modules/vite/bin/vite.js'),'--host','127.0.0.1','--port','5193','--strictPort'],{cwd:root,stdio:'ignore'});t.after(()=>server.kill());for(let i=0;i<100;i++){try{if((await fetch('http://127.0.0.1:5193')).ok)break;}catch{}await new Promise(r=>setTimeout(r,100));}
 const browser=await puppeteer.launch({executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});t.after(async()=>{await Promise.race([browser.close(),new Promise(r=>setTimeout(()=>{browser.process()?.kill('SIGKILL');browser.disconnect();r();},3000))]);});const page=await browser.newPage();await page.setViewport({width:390,height:844});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const click=async s=>{t.diagnostic('Click '+s);await page.waitForSelector(s,{visible:true});await page.$eval(s,e=>e.scrollIntoView({block:'center',behavior:'instant'}));await page.locator(s).click();};
 await page.goto('http://127.0.0.1:5193/studio/index.html#files');await page.waitForFunction(()=>document.querySelector('#real-status')?.textContent==='Your PDF will be stored in this browser.');await (await page.$('#real-file-input')).uploadFile(path.join(root,'test/fixtures/jett-fillable.pdf'));await page.waitForFunction(()=>document.querySelector('#real-status')?.textContent.startsWith('Opened'));

 const source=await page.evaluate(async()=>{const d=(await(await import('/src/db.js')).getDocs())[0];return {id:d.id,bytes:Array.from(d.sourceBytes)};});await click('[data-doc-action="write-panel"]');await click('[data-doc-action="forms"]');await page.waitForSelector('[data-field-name="full_name"]',{visible:true});await page.locator('[data-field-name="full_name"]').fill('Orchard Reader');await page.locator('[data-field-name="notes"]').fill('Keep the original');await click('[data-field-name="consent"]');await page.waitForFunction(()=>document.querySelector('#pdf-form-status')?.textContent.startsWith('Answers saved')&&!document.querySelector('#pdf-form-preview')?.disabled);
 await page.evaluate(()=>{window.savedFormPut=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(value,...rest){if(value?.formDraft)throw new DOMException('Storage full','QuotaExceededError');return window.savedFormPut.call(this,value,...rest);};});await page.locator('[data-field-name="full_name"]').fill('Recovery reader');await page.waitForFunction(()=>document.querySelector('#pdf-form-status')?.textContent.includes('could not be saved'));await page.evaluate(()=>{location.hash='#files';});await page.waitForFunction(()=>location.hash.startsWith('#editor/')&&document.querySelector('#real-status')?.textContent.includes('Retry saving'));assert.equal(await page.$eval('[data-field-name="full_name"]',e=>e.value),'Recovery reader');await page.evaluate(()=>{IDBObjectStore.prototype.put=window.savedFormPut;});await click('#pdf-form-retry');await page.waitForFunction(()=>document.querySelector('#pdf-form-status')?.textContent.startsWith('Answers saved')&&!document.querySelector('#pdf-form-preview')?.disabled).catch(async error=>{throw new Error(error.message+' '+await page.$eval('main',e=>e.textContent)+' '+errors);});await page.locator('[data-field-name="full_name"]').fill('Orchard Reader');await page.waitForFunction(()=>document.querySelector('#pdf-form-status')?.textContent.startsWith('Answers saved')&&!document.querySelector('#pdf-form-preview')?.disabled);
 await page.reload();await page.waitForFunction(()=>document.querySelector('#real-status')?.textContent.startsWith('Opened'));await click('[data-doc-action="write-panel"]');await click('[data-doc-action="forms"]');await page.waitForSelector('[data-field-name="full_name"]',{visible:true});assert.equal(await page.$eval('[data-field-name="full_name"]',e=>e.value),'Orchard Reader');await page.screenshot({path:'/tmp/jetty-experience-review/forms-phone.png'});await click('#pdf-form-preview');await page.waitForFunction(()=>document.querySelector('#real-title')?.textContent.includes('filled'));
 const result=await page.evaluate(async()=>{const d=await(await import('/src/db.js')).getDoc(location.hash.split('/')[1]);return Array.from(d.sourceBytes);});const {inspectPdfForm}=await import('../src/pdf-forms.js');const fields=(await inspectPdfForm(new Uint8Array(result))).fields;assert.equal(fields.find(f=>f.name==='full_name').value,'Orchard Reader');assert.equal(fields.find(f=>f.name==='notes').value,'Keep the original');assert.equal(fields.find(f=>f.name==='consent').value,true);assert.deepEqual(await page.evaluate(async id=>Array.from((await(await import('/src/db.js')).getDoc(id)).sourceBytes),source.id),source.bytes);assert.deepEqual(errors,[]);
});
