import test from 'node:test';
import assert from 'node:assert/strict';
import {createServer} from 'vite';
import puppeteer from 'puppeteer-core';
import * as mupdf from 'mupdf';

test('Studio camera and recovered scan save PDF plus all source assets atomically',{timeout:150000},async t=>{
 const server=await createServer({server:{host:'127.0.0.1',port:0}});await server.listen();const base=`http://127.0.0.1:${server.httpServer.address().port}`;
 const browser=await puppeteer.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--use-fake-device-for-media-stream','--use-fake-ui-for-media-stream']});t.after(async()=>{await browser.close();server.httpServer.closeAllConnections();await server.close();});const page=await browser.newPage();await page.setViewport({width:390,height:844});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const click=async selector=>{await page.waitForSelector(selector,{visible:true});await page.$eval(selector,e=>e.scrollIntoView({block:'center',behavior:'instant'}));await page.locator(selector).click();};
 await page.goto(base+'/studio/index.html#scan');await page.waitForSelector('[data-action=start]');await click('[data-action=start]');await page.waitForFunction(()=>document.querySelector('[data-scan-status]')?.textContent==='Camera ready.');await page.evaluate(()=>{window.testScanTrack=document.querySelector('video').srcObject.getTracks()[0];});await click('[data-action=capture]');await page.waitForFunction(()=>document.querySelector('[data-scan-status]')?.textContent.startsWith('Page captured'));await click('[data-action=stop]');assert.equal(await page.evaluate(()=>window.testScanTrack.readyState),'ended');
 const extra=await page.evaluate(async()=>{const c=document.createElement('canvas');c.width=300;c.height=450;const x=c.getContext('2d');x.fillStyle='white';x.fillRect(0,0,c.width,c.height);x.fillStyle='black';x.font='24px sans-serif';x.fillText('Keep the source',20,70);const b=await new Promise(r=>c.toBlob(r,'image/png')),bytes=Array.from(new Uint8Array(await b.arrayBuffer())),dt=new DataTransfer();dt.items.add(new File([b],'source-page.png',{type:'image/png'}));const input=document.querySelector('[data-files]');input.files=dt.files;input.dispatchEvent(new Event('change',{bubbles:true}));return bytes;});await page.waitForFunction(()=>document.querySelectorAll('[data-scan-page]').length===2);await page.waitForFunction(()=>!document.querySelector('[data-action=remove]').disabled);await click('[data-action=remove]');await page.waitForFunction(()=>document.querySelectorAll('[data-scan-page]').length===1);await page.reload();await page.waitForFunction(()=>document.querySelector('[data-scan-status]')?.textContent.includes('Recovered'));
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:'/tmp/jetty-experience-review/scanner-phone.png'});
 await page.evaluate(()=>{window.scanPut=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(value,...args){if(value?.scanSourceAssets)throw new DOMException('Storage full','QuotaExceededError');return window.scanPut.call(this,value,...args);};});await click('[data-action=save]');await page.waitForFunction(()=>document.querySelector('[data-scan-status]')?.textContent.startsWith('Changes not saved'));assert.equal(await page.evaluate(async()=> (await(await import('/src/db.js')).getDocs()).length),0);await page.evaluate(()=>{IDBObjectStore.prototype.put=window.scanPut;});await click('[data-action=save]');await page.waitForFunction(()=>location.hash.startsWith('#editor/')&&document.querySelector('#real-status')?.textContent.startsWith('Opened'));
 const saved=await page.evaluate(async()=>{const d=await(await import('/src/db.js')).getDoc(location.hash.split('/')[1]);return {id:d.id,bytes:Array.from(d.sourceBytes),assets:d.scanSourceAssets.map(a=>({...a,bytes:Array.from(a.bytes)})),ocr:d.scan.ocr};});assert.equal(saved.assets.length,2);assert.deepEqual(saved.assets.find(a=>a.status==='removed').bytes,extra);assert.equal(saved.ocr.status,'unsupported');for(const asset of saved.assets){const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new Uint8Array(asset.bytes))),x=>x.toString(16).padStart(2,'0')).join('');assert.equal(hash,asset.sha256);}const pdf=new mupdf.PDFDocument(new Uint8Array(saved.bytes));assert.equal(pdf.countPages(),1);pdf.destroy();
 // Re-exporting a recovered checkpoint reuses its document; changing it creates a separate copy.
 const scanRoute=await page.evaluate(()=> '#scan/'+localStorage.getItem('jetty-active-scan'));
 await page.goto(base+'/studio/index.html'+scanRoute);await page.waitForSelector('[data-action=save]');await click('[data-action=save]');await page.waitForFunction(()=>location.hash.startsWith('#editor/')&&document.querySelector('#real-status')?.textContent.startsWith('Opened'));
 assert.equal(await page.evaluate(()=>location.hash.split('/')[1]),saved.id);assert.equal(await page.evaluate(async()=> (await(await import('/src/db.js')).getDocs()).length),1);
 await page.goto(base+'/studio/index.html'+scanRoute);await page.waitForSelector('[data-action=rotate]');await click('[data-action=rotate]');await page.waitForFunction(()=>!document.querySelector('[data-action=save]').disabled);await click('[data-action=save]');await page.waitForFunction(()=>location.hash.startsWith('#editor/')&&document.querySelector('#real-status')?.textContent.startsWith('Opened'));
 const changedId=await page.evaluate(()=>location.hash.split('/')[1]);assert.notEqual(changedId,saved.id);assert.equal(await page.evaluate(async()=> (await(await import('/src/db.js')).getDocs()).length),2);
 await page.goto(base+'/studio/index.html');await page.waitForFunction(id=>location.hash.includes(id)&&document.querySelector('#real-status')?.textContent.startsWith('Opened'),{},changedId);await page.goto(base+'/studio/index.html#scan/new');await page.waitForFunction(()=>location.hash.startsWith('#scan/')&&location.hash!=='#scan/new'&&document.querySelector('[data-scan-status]'));assert.notEqual(await page.evaluate(()=>location.hash),scanRoute);assert.equal(await page.$$eval('[data-scan-page]',e=>e.length),0);assert.equal(await page.evaluate(async()=> (await(await import('/src/db.js')).getDocs()).length),2);const distinct=await page.evaluate(async id=>{const db=await import('/src/db.js'),d=await db.getDoc(id),{saveScanResult}=await import('/studio/scan-custody.js');const suffix=new TextEncoder().encode('\n% independent output bytes\n'),bytes=new Uint8Array(d.sourceBytes.length+suffix.length);bytes.set(d.sourceBytes);bytes.set(suffix,d.sourceBytes.length);const result={pdfBytes:bytes,title:d.title,sessionId:d.scan.sessionId,sourceRevision:d.scan.sourceRevision,sourceAssets:d.scanSourceAssets,ocr:d.scan.ocr};const first=await saveScanResult(result),second=await saveScanResult(result),kept=await db.getDoc(first.documentId);return {first:first.documentId,second:second.documentId,equal:kept.sourceBytes.length===bytes.length&&kept.sourceBytes.every((v,i)=>v===bytes[i])};},saved.id);assert.notEqual(distinct.first,saved.id);assert.equal(distinct.first,distinct.second);assert.equal(distinct.equal,true);assert.deepEqual(errors,[]);
});
