import test from 'node:test';
import assert from 'node:assert/strict';
import { createServer } from 'vite';
import puppeteer from 'puppeteer-core';
import { root } from './validate.mjs';
test('PDF attachment review returns an independent copy to its draft', {timeout:90000}, async t=>{
 const server=await createServer({root,server:{host:'127.0.0.1',port:0}});await server.listen();t.after(()=>server.close());
 const browser=await puppeteer.launch({executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});
 t.after(async()=>{const timer=setTimeout(()=>browser.process()?.kill('SIGKILL'),3000);try{await browser.close();}finally{clearTimeout(timer);}});
 const page=await browser.newPage();await page.goto(`http://127.0.0.1:${server.httpServer.address().port}/workspace/index.html`);
 await page.type('textarea','Please review the attached PDF.');
 await (await page.$('#file')).uploadFile(`${root}/test/fixtures/jett-fillable.pdf`);
 await page.waitForFunction(()=>document.querySelector('#attachment')?.textContent.includes('Review PDF'));
 await page.evaluate(()=>[...document.querySelectorAll('button')].find(b=>b.textContent==='Review PDF').click());
 await page.waitForFunction(()=>[...document.querySelectorAll('button')].some(b=>b.textContent==='Attach reviewed copy to draft'&&!b.disabled),{timeout:60000});
 await page.select('#reader-workspace','fill');
 await page.waitForSelector('[data-field-name="full_name"]');
 await page.waitForSelector('[data-field-name="full_name"]',{visible:true});
 await page.click('[data-field-name="full_name"]',{clickCount:3});
 await page.type('[data-field-name="full_name"]','Synthetic reviewer');
 await page.evaluate(()=>[...document.querySelectorAll('button')].find(b=>b.textContent==='Attach reviewed copy to draft').click());
 await page.waitForFunction(()=>document.querySelector('.reviewed-copy')||[...document.querySelectorAll('aside[aria-label="Attachment review"] button')].some(b=>!b.disabled),{timeout:30000});
 assert.ok(await page.$('.reviewed-copy'),await page.$eval('body',n=>n.querySelector('aside[aria-label="Attachment review"]')?.textContent||'No returned copy')); 
 assert.equal(await page.$eval('textarea',e=>e.value),'Please review the attached PDF.');
 assert.match(await page.$eval('.reviewed-copy',e=>e.textContent),/Original attachment retained/);
 const result=await page.evaluate(async()=>{const {attachmentStore}=await import('/workspace/attachments.js');const id=new URL(location.href).searchParams.get('review');const session=await attachmentStore(`handoff:${id}`);const a=await attachmentStore('Inbox'),b=await attachmentStore(`result:${session.resultId}`);return {original:a.name,result:b.name,bytes:b.size,fields:(await (await import('/src/pdf-forms.js')).inspectPdfForm(new Uint8Array(await b.arrayBuffer()))).fields.map(f=>({name:f.name,value:f.value}))};});
 assert.equal(result.original,'jett-fillable.pdf');assert.equal(result.result,'jett-fillable-reviewed.pdf');assert.ok(result.bytes>100);assert.equal(result.fields.find(f=>f.name==='full_name').value,'Synthetic reviewer');
 await page.goto(`http://127.0.0.1:${server.httpServer.address().port}/workspace/index.html`);await page.waitForSelector('.reviewed-copy');
});
