import { readdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { defineConfig } from "vite";
import pkg from "./package.json" with { type: "json" };

const root = import.meta.dirname;
const outDir = path.join(root, "dist");

async function listFiles(dir, prefix = "") {
  const entries = await readdir(dir, { withFileTypes: true });
  const files = [];
  for (const entry of entries) {
    const relative = path.posix.join(prefix, entry.name);
    if (entry.isDirectory()) files.push(...(await listFiles(path.join(dir, entry.name), relative)));
    else files.push(relative);
  }
  return files;
}

function serviceWorkerSource(files) {
  const precache = files
    .filter((file) =>
      file !== "sw.js"
      && !/^assets\/mupdf(?:-wasm)?-/.test(file),
    )
    .sort()
    .map((file) => `./${file}`);

  return `// Generated by vite.config.js from the completed jt build.
const VERSION = ${JSON.stringify(pkg.version)};
const CACHE_PREFIX = "jt-shell-";
const CACHE_NAME = CACHE_PREFIX + VERSION;
const PRECACHE = ${JSON.stringify(precache, null, 2)};
const SHELL_URL = new URL("./index.html", self.registration.scope).pathname;
const HASHED_ASSET = /\\/assets\\/[^/]+-[A-Za-z0-9_-]{6,}\\.[^/]+$/;

self.addEventListener("install", (event) => {
  event.waitUntil(caches.open(CACHE_NAME).then((cache) => cache.addAll(PRECACHE)));
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys()
      .then((names) => Promise.all(
        names
          .filter((name) => name.startsWith(CACHE_PREFIX) && name !== CACHE_NAME)
          .map((name) => caches.delete(name))
      ))
      .then(() => self.clients.claim())
  );
});

async function networkFirstNavigation(request) {
  try {
    return await fetch(request);
  } catch {
    const requested = new URL(request.url);
    const notebookShell = new URL("./notebooks/index.html", self.registration.scope).pathname;
    const workspaceShell = new URL("./workspace/index.html", self.registration.scope).pathname;
    const fallback = requested.pathname === workspaceShell || requested.pathname === workspaceShell.replace("index.html", "") ? workspaceShell : requested.pathname === notebookShell || requested.pathname === notebookShell.replace("index.html", "") ? notebookShell : SHELL_URL;
    return (await caches.match(fallback)) || Response.error();
  }
}

async function cacheFirstAsset(request) {
  const cached = await caches.match(request);
  if (cached) return cached;
  const response = await fetch(request);
  if (response.ok) {
    const cache = await caches.open(CACHE_NAME);
    await cache.put(request, response.clone());
  }
  return response;
}

self.addEventListener("fetch", (event) => {
  if (event.request.method !== "GET") return;
  const url = new URL(event.request.url);
  if (url.origin !== self.location.origin) return;

  if (event.request.mode === "navigate") {
    event.respondWith(networkFirstNavigation(event.request));
    return;
  }
  if (HASHED_ASSET.test(url.pathname)) {
    event.respondWith(cacheFirstAsset(event.request));
  }
});
`;
}

function emitVersionedServiceWorker() {
  return {
    name: "jt-versioned-service-worker",
    apply: "build",
    async closeBundle() {
      const files = await listFiles(outDir);
      await writeFile(path.join(outDir, "sw.js"), serviceWorkerSource(files));
    },
  };
}

export default defineConfig({
  plugins: [emitVersionedServiceWorker()],
  build: { rollupOptions: { input: { workspace: path.join(root,"workspace/index.html"), main: path.join(root,"index.html"), notebooks: path.join(root,"notebooks/index.html") } } },
});
