import {createScanSession} from './session.js';
import {IndexedDBScanStore} from './store.js';
import {ScanCamera} from './camera.js';
import {analyseFrame,CaptureGate} from './raster.js';
import {detectDocument} from './detection.js';
import {createWorkerProcessor} from './worker.js';

const css=`
.jt-scanner{--paper:#fff;--ink:#183449;--blue:#175fa8;--wash:#edf3f7;--line:#aec0cc;color:var(--ink);background:var(--wash);font:16px/1.5 system-ui,sans-serif;padding:20px;max-width:1080px;margin:auto;border-radius:18px}
.jt-scanner *{box-sizing:border-box}.jt-scanner h2{font-size:28px;margin:0}.jt-scanner p{max-width:65ch;margin:8px 0 16px}.jt-scanner button,.jt-scanner input{font:inherit}.jt-scanner button{min-height:44px;padding:9px 16px;border:1px solid var(--line);border-radius:8px;background:white;color:var(--ink);cursor:pointer}.jt-scanner button:disabled{opacity:.5;cursor:default}.jt-scanner button:focus-visible,.jt-scanner input:focus-visible{outline:3px solid var(--blue);outline-offset:3px}.jt-scanner [data-action=save]{background:var(--blue);color:white;border-color:var(--blue)}
.jt-scanner .scan-layout{display:grid;grid-template-columns:minmax(0,1.2fr) minmax(280px,1fr);gap:24px}.jt-scanner .scan-stage{position:relative;min-height:240px;background:#d2dfe7;border-radius:12px;display:grid;place-items:center;overflow:hidden}.jt-scanner video{width:100%;max-height:440px;display:block}.jt-scanner .scan-tools{display:flex;gap:8px;flex-wrap:wrap;margin:12px 0}.jt-scanner label{display:block}.jt-scanner input[type=text]{width:100%;padding:10px;border:1px solid var(--line);border-radius:6px}.jt-scanner input[type=number]{width:76px;min-height:40px}.jt-scanner input[type=checkbox]{width:20px;height:20px;vertical-align:middle}.jt-scanner .scan-review{position:relative;background:white;min-height:160px;display:grid;place-items:center}.jt-scanner .scan-review img{max-width:100%;max-height:350px;display:block}.jt-scanner .scan-review svg{position:absolute;width:100%;height:100%;inset:0;pointer-events:none}.jt-scanner ol{display:flex;gap:8px;padding:0;list-style:none;overflow:auto}.jt-scanner [aria-pressed=true]{border:2px solid var(--blue);background:#dfeeff}.jt-scanner fieldset{border:1px solid var(--line);border-radius:8px;margin:12px 0}.jt-scanner .scan-corner{display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin:8px 0}.jt-scanner [data-scan-status]{min-height:48px;padding:12px 0;font-weight:600}.jt-scanner [hidden]{display:none!important}@media(max-width:700px){.jt-scanner{padding:14px;border-radius:0}.jt-scanner .scan-layout{grid-template-columns:1fr}.jt-scanner h2{font-size:24px}}`;
const guidance={ 'position-document':'Place one page on a darker surface, with all edges visible.', 'more-light':'Add more light.', 'hold-steady':'Hold steady, or capture manually.', 'reduce-glare':'Tilt the page to reduce glare.', 'captured':'Page captured. Review it below.', 'turn-page-or-capture-manually':'Turn the page or capture the next page manually.'};

/** Host owns library persistence. Resolving onSave must mean PDF + source custody committed. */
export async function mountScanner({root,onSave,store=new IndexedDBScanStore(),id,processor,ocr,mediaDevices}={}){
 if(!root||typeof onSave!=='function')throw new Error('SCAN_UI_CONFIG');
 const ownedProcessor=processor?null:createWorkerProcessor();processor??=ownedProcessor;
 const session=await createScanSession({store,id,processor,ocr});let selected=session.pages[0]?.id,busy=false,destroyed=false,url=null,timer=null,lastQuad=null;
 const abort=new AbortController(),el=document.createElement('section');el.className='jt-scanner';el.setAttribute('aria-label','Document scanner');
 el.innerHTML=`<style>${css}</style><h2>Scan a document</h2><p>Capture the page, check its edges, then save. Your original images stay intact.</p><div class="scan-layout"><div><div class="scan-stage"><video aria-label="Camera preview"></video></div><div class="scan-tools"><button data-action="start">Start camera</button><button data-action="stop">Stop camera</button><button data-action="capture">Capture page</button></div><label><input type="checkbox" data-auto> Capture automatically when steady</label><p data-guidance>Camera access starts only when you choose Start camera.</p><label>Add page images <input data-files type="file" accept="image/png,image/jpeg" multiple></label><p>PNG or JPEG. For other formats, use your device’s document scanner or convert a copy.</p></div><div><label>Document name <input data-title type="text" value="Scan" maxlength="200"></label><ol aria-label="Scanned pages" data-pages></ol><div class="scan-review"><img data-preview alt="Selected source page"><svg viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true"><polygon data-quad fill="none" stroke="#175fa8" stroke-width="1" stroke-dasharray="3 2"/></svg></div><p data-page-info>No pages yet.</p><div class="scan-tools"><button data-action="rotate">Rotate right</button><button data-action="earlier">Move earlier</button><button data-action="remove">Remove page</button><button data-action="retake">Retake selected</button></div><details><summary>Adjust edges precisely</summary><p>Coordinates are percentages of the original image. Read clockwise from top left.</p><fieldset data-edges><legend>Page corners</legend></fieldset><button data-action="edges">Apply edges</button></details><label><input data-enhance type="checkbox"> Gentle contrast enhancement</label></div></div><div data-scan-status role="status" aria-live="polite"></div><div class="scan-tools"><button data-action="save">Save to library</button><button data-action="cancel">Cancel processing</button></div>`;
 root.append(el);const $=s=>el.querySelector(s),camera=new ScanCamera({video:$('video'),mediaDevices}),gate=new CaptureGate();
 $('style').textContent+=' .jt-scanner .scan-review{width:fit-content;max-width:100%;min-height:0;margin-inline:auto}';
 const status=text=>{if(!destroyed)$('[data-scan-status]').textContent=text;};
 const button=name=>$(`[data-action="${name}"]`);
 const edges=$('[data-edges]');['Top left','Top right','Bottom right','Bottom left'].forEach((name,i)=>{const row=document.createElement('div');row.className='scan-corner';const label=document.createElement('span');label.textContent=name;row.append(label);['x','y'].forEach(axis=>{const l=document.createElement('label');l.textContent=axis.toUpperCase()+' ';const n=document.createElement('input');Object.assign(n,{type:'number',min:'0',max:'100',step:'.1'});n.dataset.corner=i;n.dataset.axis=axis;n.setAttribute('aria-label',`${name} ${axis} percent`);l.append(n);row.append(l);});edges.append(row);});
 function controls(){for(const b of el.querySelectorAll('button'))b.disabled=busy;button('cancel').disabled=!busy;button('capture').disabled=busy||!camera.stream;button('stop').disabled=!camera.stream;button('save').disabled=busy||!session.pages.length;for(const name of ['rotate','earlier','remove','retake','edges'])button(name).disabled=busy||!selected;for(const input of el.querySelectorAll('input'))input.disabled=busy;}
 function render(){
  if(destroyed)return;const pages=session.pages;if(!pages.some(p=>p.id===selected))selected=pages[0]?.id;
  $('[data-pages]').replaceChildren();pages.forEach((p,i)=>{const li=document.createElement('li'),b=document.createElement('button');b.textContent=`Page ${i+1}`;b.dataset.scanPage=p.id;b.setAttribute('aria-pressed',String(p.id===selected));b.onclick=()=>{selected=p.id;render();};li.append(b);$('[data-pages]').append(li);});
  if(url){URL.revokeObjectURL(url);url=null;}
  const page=pages.find(p=>p.id===selected);$('[data-preview]').hidden=!page;
  if(page){const source=session.source(page.id);url=URL.createObjectURL(new Blob([source.bytes],{type:source.mime}));$('[data-preview]').src=url;$('[data-quad]').setAttribute('points',page.quad.map(([x,y])=>`${x*100},${y*100}`).join(' '));for(const input of edges.querySelectorAll('input'))input.value=(page.quad[Number(input.dataset.corner)][input.dataset.axis==='x'?0:1]*100).toFixed(1);$('[data-enhance]').checked=page.enhance;$('[data-page-info]').textContent=`Page ${pages.indexOf(page)+1} of ${pages.length}. Rotation ${page.rotation}°. Preview shows the original; edges and rotation apply to the saved PDF.`;}else{$('[data-preview]').removeAttribute('src');$('[data-quad]').setAttribute('points','');$('[data-page-info]').textContent='No pages yet.';}
  controls();
 }
 async function run(fn){if(busy||destroyed)return;busy=true;controls();try{await fn();}catch(e){const cameraMessage=({NotAllowedError:'Camera access was not allowed. Choose Start camera to try again, or add page images instead.',NotFoundError:'No camera is available. Add page images to continue.',NotReadableError:'The camera is busy or unavailable. Close other camera apps, then try again.'})[e.name]||({SCAN_CAMERA_UNSUPPORTED:'Camera capture is unavailable here. Add page images to continue.',SCAN_CAMERA_CANCELLED:'Camera paused. Choose Start camera when you are ready.',SCAN_PREVIEW_NOT_READY:'Start the camera before capturing a page.'})[e.message];const conflict=e.message==='SCAN_CHECKPOINT_CONFLICT';status(cameraMessage||(conflict?'Another tab changed this scan. Close and reopen before editing.':'Changes not saved. Your previous checkpoint is intact. Check storage, image format or page edges, then retry.'));}finally{busy=false;render();}}
 function stop(){clearInterval(timer);timer=null;camera.stop();gate.reset();lastQuad=null;controls();}
 async function capture(retake=false){const shot=await camera.capture();const pageId=retake?selected:await session.addPage(shot.bytes);if(retake)await session.retakePage(pageId,shot.bytes);if(lastQuad)await session.editPage(pageId,{quad:lastQuad});selected=pageId;status('Page captured and checkpoint saved. Review before saving to library.');}
 button('start').onclick=()=>run(async()=>{await camera.start();clearInterval(timer);timer=setInterval(()=>{if(busy||destroyed||document.hidden)return;try{const frame=camera.frame(),detected=detectDocument(frame);lastQuad=detected.quad;const state=gate.update({timestamp:performance.now(),quad:lastQuad,...analyseFrame(frame)});$('[data-guidance]').textContent=guidance[state.guidance]??'Check the page.';if(state.capture&&$('[data-auto]').checked)void run(()=>capture());}catch{$('[data-guidance]').textContent='Automatic edges unavailable. Capture manually and adjust edges.';}},250);status('Camera ready.');});
 button('stop').onclick=()=>{stop();status('Camera stopped. Captured pages are kept.');};button('capture').onclick=()=>run(()=>capture());button('retake').onclick=()=>run(async()=>{if(!camera.stream)throw Error('SCAN_PREVIEW_NOT_READY');await capture(true);});
 $('[data-auto]').onchange=()=>gate.reset();
 $('[data-files]').onchange=()=>{const files=Array.from($('[data-files]').files);void run(async()=>{for(const file of files){if(file.size>25000000)throw Error('SCAN_IMAGE_LIMIT');selected=await session.addPage(new Uint8Array(await file.arrayBuffer()));}status(`${files.length} page images added. Review before saving.`);$('[data-files]').value='';});};
 button('rotate').onclick=()=>run(async()=>{const p=session.pages.find(p=>p.id===selected);await session.editPage(selected,{rotation:(p.rotation+90)%360});status('Rotation updated. Original retained.');});
 button('earlier').onclick=()=>run(async()=>{await session.movePage(selected,Math.max(0,session.pages.findIndex(p=>p.id===selected)-1));status('Page order updated.');});
 button('remove').onclick=()=>run(async()=>{await session.removePage(selected);status('Page removed from PDF. Original retained in checkpoint.');});
 button('edges').onclick=()=>run(async()=>{const quad=[0,1,2,3].map(i=>['x','y'].map(axis=>Number(edges.querySelector(`[data-corner="${i}"][data-axis="${axis}"]`).value)/100));await session.editPage(selected,{quad});status('Page edges updated.');});
 $('[data-enhance]').onchange=()=>run(async()=>{await session.editPage(selected,{enhance:$('[data-enhance]').checked});status('Enhancement preference saved.');});
 button('save').onclick=()=>run(async()=>{stop();status('Processing pages. Originals are retained.');const result=await session.finish({title:$('[data-title]').value});if(destroyed)return;const receipt=await onSave(result);if(!receipt?.documentId)throw Error('SCAN_SAVE_ACK_REQUIRED');status('Saved to library. Original images retained.');});
 button('cancel').onclick=()=>{session.cancel();status('Cancelling processing. Captured pages remain available.');};
 document.addEventListener('jetty-native-background',()=>{stop();status('Camera paused while app was hidden. Choose Start camera to resume.');},{signal:abort.signal});
 document.addEventListener('visibilitychange',()=>{if(document.hidden){stop();status('Camera paused while app was hidden. Choose Start camera to resume.');}},{signal:abort.signal});
 render();status(session.pages.length?'Recovered your saved scan checkpoint.':'Add a page to begin.');
 return {id:session.id,destroy(){destroyed=true;session.cancel();ownedProcessor?.close();stop();abort.abort();if(url)URL.revokeObjectURL(url);el.remove();}};
}
