import {esc} from './screens.js';
import './product-guide.css';
// Internal, evidence-scoped inventory. Update status when a real journey is verified.
export const guideCapabilities = Object.freeze([
 ['PDF review','exposed','Open a PDF, write text or ink, save a reviewed copy, reopen and export. Originals stay separate.','studio/real-documents.js · src/pdf-freehand.js','#files'],
 ['Source-linked notes','exposed','Editable notes refer to a physical PDF page and source digest. Concurrent conflicts keep your words for resolution.','notebooks/source-notes.js · notebooks/storage.js','#files'],
 ['Contextual editor','exposed','Read, Highlight, Write, Pages and Notes keep tools near the page. Panels retain the document; Export names the file being delivered.','studio/real-documents.js · studio/runtime-activity.js','#files'],
 ['Existing PDF paragraphs','exposed','Select a supported paragraph, keep an editable draft, and review a verified replacement copy in Studio. The original remains unchanged.','src/pdf-text-editor.js · src/pdf-edit-workspace.js','../index.html'],
 ['Exact text markup & search','exposed','Find source words, select text, and apply highlight, underline or strikeout. Studio saves native PDF annotations into a separate reviewed copy.','src/pdf-selection.js · src/pdf-annotations.js · src/text-markup.js','../index.html'],
 ['Page crop','exposed','Keep an area of the page and save a cropped copy. Verified CropBox changes retain hidden content and preserve the original. Crop is not redaction.','src/pdf-crop.js','#files'],
 ['Page organisation & forms','engine','Rotate, reorder, extract and merge prepared copies; fill supported form fields through the original reader. Restrictions remain explicit.','src/pdf-review.js · src/pdf-forms.js','../index.html'],
 ['Print handoff','engine','The original reader opens exact PDF bytes in the browser viewer. The operating system owns printing; a physical printer result is separate evidence.','src/pdf-review.js','../index.html'],
 ['Spoken mathematics','engine','A local rule translator keeps recognizer words, LaTeX and unparsed words. This is existing code, not a general AI mathematics service.','src/math.js · src/registry/verbs/math-keep.js','../index.html'],
 ['Contextual Jetty','preview','Explore source citations and keeping an answer beside a page. River Library uses composed example answers, not a live AI connection.','studio/experience.js','#canvas'],
 ['Tender preparation','preview','A fictional packet demonstrates preparation, review and an outcome. No portal access, certificate signing or submission occurs.','studio/experience.js','#tender'],
 ['Widgets & two capsules','preview','Widget specimens and optional dual-capsule exploration. The live editor capsule reflects actual local operations; neither is native ActivityKit.','studio/widgets.js · studio/runtime-activity.js','#widgets'],
 ['Advanced AI voice → LaTeX','planned','Explicit capture → preview → correction → insert into a chosen destination. User confirmation, uncertainty and undo belong to the journey.','src/voice-capture.js · src/math.js','#guide'],
 ['Additional input adapters','planned','Face, gaze, hand, motion and proximity should dispatch the same semantic actions. No silent sensor collection; denied permissions retain another path.','studio/real-documents.js · src/command-journal.js','#guide'],
 ['Image editing & certificate signing','planned','Editing existing PDF images and creating certificate signatures need their own audited implementation and permissions. Handwritten ink is not a certificate signature.','docs/superpowers/plans/2026-09-13-pdf-capability-contract.md','#guide'],
]);
const labels={exposed:'Working surface',engine:'Engine / original reader',preview:'Design preview',planned:'Intended'};
const card=([name,state,description,source,url])=>`<article class="pg-item" data-guide-state="${state}" data-guide-search="${esc([name,labels[state],description,source].join(' ').toLowerCase())}"><div><span class="pg-state pg-${state}">${labels[state]}</span><h3>${esc(name)}</h3><p>${esc(description)}</p><details><summary>Implementation pointer</summary><code>${esc(source)}</code></details></div>${url==='#guide'?'':`<a href="${url}">Explore ${esc(name)} <span aria-hidden="true">↗</span></a>`}</article>`;
export function guideView(){return `<div class="product-guide"><header class="pg-heading"><span class="pg-eyebrow">A closer look / Product guide</span><h1>Know the work.<br>Know what holds it.</h1><p>A map for people shaping Jetty. Follow the experience, inspect its parts, and see where the proof ends.</p><nav aria-label="Guide sections"><a href="#guide-inventory" data-guide-jump>Capabilities</a><a href="#guide-access" data-guide-jump>Accessible inputs</a><a href="#guide-parts" data-guide-jump>How it connects</a><a href="#guide-contribute" data-guide-jump>Start contributing</a></nav></header>
<section class="pg-intent"><span>01 / The product</span><p>Your document is the starting point. Read, mark, think beside it, and take a result with you. Keep the source, your decisions and the way back together.</p><div><a href="#files">Open real documents ↗</a><a href="#welcome">First visit ↗</a><a href="#journeys">Journey collection ↗</a><a href="#system">Design system ↗</a><a href="#widgets">Widgets ↗</a><a href="#references">Reference library ↗</a></div></section>
<section id="guide-inventory" tabindex="-1"><div class="pg-section-heading"><h2>What is here.</h2><p>Working surface means reachable in Studio. Engine means existing code or another reader surface; it does not promise integrated platform parity.</p></div><div class="pg-search"><label>Find a capability<input type="search" id="pg-query" placeholder="Try crop, keyboard, notes, LaTeX…"></label><label>Show<select id="pg-filter"><option value="all">Everything</option>${Object.entries(labels).map(([id,label])=>`<option value="${id}">${label}</option>`).join('')}</select></label></div><p id="pg-count" role="status" aria-live="polite">${guideCapabilities.length} capabilities</p><div class="pg-inventory">${guideCapabilities.map(card).join('')}</div><p id="pg-empty" hidden>No matches. Try another word or choose Everything.</p><small class="pg-scope">Working-surface status describes browser reachability. Inspect the current acceptance receipt for exact source revisions and separate Android evidence; no device or release parity is implied.</small></section>
<section id="guide-access" tabindex="-1"><div class="pg-section-heading"><h2>Many ways into the same work.</h2><p>Accessibility belongs to the actions, source model and save states. A different input method should not mean a different application.</p></div><div class="pg-access-grid"><article><h3>Available alternatives</h3><dl><dt>Keyboard</dt><dd>Tab through named controls; Escape closes the editor panel and returns to Read. Ctrl/⌘ Z undoes marks outside text fields. Text placement has numeric precision controls.</dd><dt>Touch & pointer</dt><dd>Read leaves the page scrollable. Pen captures strokes; Text targets a page location. Page and zoom controls avoid drag-only navigation.</dd><dt>Structured reading</dt><dd>Page text exposes the exact physical page’s extracted text beside the canvas. Image-only pages explain the absence of text. Source notes are editable text linked to a page.</dd><dt>State & recovery</dt><dd>Selected modes use aria-pressed; save/error messages use status regions; source conflicts preserve drafts. These semantics require actual screen-reader and touch verification.</dd></dl></article><article><h3>Adapters still to establish</h3><p>Voice cursor exists in the original reader and notebooks. Provider availability and microphone accuracy vary; the guide never starts capture.</p><p>Head, gaze, face, hand, gyro, double-tap and proximity inputs remain intended adapters. Define intentional activation, cancellation and a permission-denied alternative before acquisition.</p><p>Manual place labels work without a location sensor. Shared or institutional views must not inherit private document locations by default.</p><a href="../notebooks/index.html">Explore notebook input tools ↗</a></article></div>
<details class="pg-expand"><summary>Advanced AI voice-to-LaTeX: intended interaction</summary><ol class="pg-flow"><li><strong>Capture explicitly.</strong> Show microphone ownership and Stop; offer typed input.</li><li><strong>Preview both forms.</strong> Keep the recognized words beside rendered mathematics and editable LaTeX.</li><li><strong>Correct uncertainty.</strong> Surface unparsed terms; never silently invent missing mathematics.</li><li><strong>Choose the destination.</strong> Insert only after review, with source context and undo.</li></ol><p>Existing foundation: <code>createVoiceCapture()</code> in <code>src/voice-capture.js</code>, <code>translateSpokenMath()</code> and <code>makeSpokenMathDocument()</code> in <code>src/math.js</code>, and the durable <code>math-keep</code> verb. Today’s translator is rule-based. Advanced AI correction and general destination insertion are not demonstrated by these APIs.</p></details>
<details class="pg-expand"><summary>Material, motion and platform accessibility</summary><p>Apple’s Liquid Glass is a native material with system adaptations for reduced transparency, contrast and motion. Our CSS surfaces are an interpretation, not native Liquid Glass or ActivityKit integration. <a href="https://developer.apple.com/videos/play/wwdc2025/219/" target="_blank" rel="noopener">Apple: Meet Liquid Glass</a> · <a href="https://developer.apple.com/design/human-interface-guidelines/materials" target="_blank" rel="noopener">Materials</a></p><p>Android’s relevant foundation is Material components with semantic roles, actions, state descriptions and custom-action alternatives. It is not an identical glass API. <a href="https://developer.android.com/develop/ui/compose/accessibility/semantics" target="_blank" rel="noopener">Android: Compose semantics</a></p><p>Keep control contrast over every background; prefer opaque surfaces when transparency is reduced. Respect reduced motion and text scaling. Verify TalkBack and VoiceOver separately from DOM checks; no universal-accessibility claim follows from a checklist.</p></details></section>
<section id="guide-parts" tabindex="-1"><div class="pg-section-heading"><h2>The parts, connected.</h2></div><ol class="pg-relations"><li><strong>Document identity</strong><span>Original bytes + digest</span><code>src/db.js · src/ingest.js</code></li><li><strong>Intent & controls</strong><span>Named action + exact target</span><code>real-documents.js · registry/verbs</code></li><li><strong>Editable work</strong><span>PDF marks / linked notebook notes</span><code>attachments.js · notebooks/storage.js</code></li><li><strong>Verified result</strong><span>New PDF + return to source</span><code>pdf-freehand.js · pdf-crop.js</code></li></ol><p class="pg-scope">The command journal describes input and outcomes; it is not a universal multimodal intent engine. The activity capsule reports operations; it does not own storage. PDF annotations and notebook notes keep distinct data models.</p></section>
<section id="guide-contribute" tabindex="-1"><div class="pg-section-heading"><h2>Make one journey better.</h2></div><div class="pg-access-grid"><article><h3>Start with the source</h3><ol><li>Read <code>AGENTS.md</code> and <code>CLAUDE.md</code>. Confirm branch, artifact and writer ownership.</li><li>Read <code>docs/product-guide.md</code>, the editor experience contract and PDF capability contract.</li><li>Walk the actual journey. Record the trigger, current outcome and desired outcome.</li><li>Reuse the owning engine and store. Keep originals and interrupted drafts.</li></ol></article><article><h3>Bring evidence back</h3><ol><li>Exercise keyboard, touch, scaled text and reduced motion.</li><li>Test save failure, cancellation, reload and stale-source conflicts.</li><li>Inspect exported bytes independently; a painted preview is insufficient.</li><li>Run focused checks and required repository tests. State browser, emulator, device, push and deployment separately.</li></ol></article></div><p class="pg-scope">Known gaps stay visible: unified redo/history, PDF image editing, broader OCR exposure, native input adapters, full screen-reader journeys, provider integrations and portable source-plus-notebook backups. Consult the live capability contract as these change.</p></section></div>`;}
export function setupGuide(root=document){const container=root.querySelector('.product-guide');if(!container)return;const query=container.querySelector('#pg-query'),filter=container.querySelector('#pg-filter');const update=()=>{const q=query.value.trim().toLowerCase(),state=filter.value;let count=0;for(const item of container.querySelectorAll('.pg-item')){item.hidden=!(item.dataset.guideSearch.includes(q)&&(state==='all'||state===item.dataset.guideState));if(!item.hidden)count++;}container.querySelector('#pg-count').textContent=`${count} ${count===1?'capability':'capabilities'}`;container.querySelector('#pg-empty').hidden=count!==0;};query.oninput=update;filter.onchange=update;container.querySelectorAll('[data-guide-jump]').forEach(link=>link.onclick=e=>{e.preventDefault();const target=container.querySelector(link.getAttribute('href'));target?.scrollIntoView({block:'start',behavior:'instant'});target?.focus({preventScroll:true});});}
