import assert from 'node:assert/strict';
import { readFile, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import puppeteer from 'puppeteer-core';
const directory = process.env.BENTO_EVIDENCE_DIR || new URL('../../runtime/bento-integration-evidence', import.meta.url).pathname;
const original = await readFile(`${directory}/original.pdf`);
const browser = await puppeteer.launch({executablePath:process.env.CHROME_PATH || '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--no-first-run']});
try {
 const page=await browser.newPage();await page.setViewport({width:1440,height:1000});
 const errors=[];page.on('pageerror',error=>errors.push(error.message));
 await page.evaluateOnNewDocument(()=>{localStorage.setItem('jt.welcomed','1');localStorage.setItem('jt.mic','off');});
 await page.goto('http://127.0.0.1:5174/');await page.waitForFunction(()=>window.__jtApp?.booted);
 await (await page.$('#home-file-input')).uploadFile(`${directory}/original.pdf`);
 await page.waitForSelector('#bento-original:not([hidden])');
 const before=await page.evaluate(async()=>{const db=await import('/src/db.js');return (await db.getDocs()).map(d=>({id:d.id,pages:d.provenance?.pageCount,bytes:Array.from(d.sourceBytes||[])}));});
 const source=before.find(d=>d.pages===2);assert.ok(source);assert.deepEqual(Buffer.from(source.bytes),original);
 await page.select('#reader-workspace','organize');
 await page.locator('#reader-workspace-bento').click();
 const target=await browser.waitForTarget(t=>t.url().includes('5181/pdf-multi-tool.html#jett='),{timeout:30000});
 console.log('Source imported and Bento opened');
 const bento=await target.page();await bento.setViewport({width:1440,height:1000});bento.on('pageerror',error=>errors.push(error.message));
 await bento.waitForFunction(()=>document.querySelectorAll('button[title="Duplicate this page"]').length===2,{timeout:60000});
 console.log('Two source pages rendered in Bento');
 await bento.screenshot({path:`${directory}/bento-original-two-pages.png`,fullPage:true});
 await bento.click('button[title="Duplicate this page"]');
 await bento.waitForFunction(()=>document.querySelectorAll('button[title="Duplicate this page"]').length===3);
 await bento.screenshot({path:`${directory}/bento-duplicated-three-pages.png`,fullPage:true});
 await bento.click('#export-pdf-btn');
 await bento.waitForFunction(()=>document.body.innerText.includes('PDF export ready.'),{timeout:30000});
 await page.bringToFront();
 await page.click('#bento-save');
 await page.waitForFunction(()=>document.getElementById('bento-status').textContent.includes('as a new document'),{timeout:60000});
 await page.screenshot({path:`${directory}/jett-return-saved.png`,fullPage:true});
 await page.reload();await page.waitForFunction(()=>window.__jtApp?.booted);
 const docs=await page.evaluate(async()=>{const db=await import('/src/db.js');return (await db.getDocs()).map(d=>({id:d.id,title:d.title,provenance:d.provenance,bytes:Array.from(d.sourceBytes||[])}));});
 const returned=docs.find(d=>d.provenance?.derivedFrom?.documentId===source.id);assert.ok(returned);assert.equal(returned.provenance.pageCount,3);
 const tabs=await page.evaluate(()=>window.__jtApp.readerSession().tabs);
 assert.ok(tabs.includes(source.id)&&tabs.includes(returned.id),'source and returned PDF retain separate Reader tabs after reload');
 assert.deepEqual(Buffer.from(docs.find(d=>d.id===source.id).bytes),original);
 assert.equal(docs.filter(d=>d.provenance?.derivedFrom?.documentId===source.id).length,1);
 await writeFile(`${directory}/returned.pdf`,Buffer.from(returned.bytes));
 await page.goto('http://127.0.0.1:5174/#/home');
 await page.waitForFunction(()=>Array.from(document.querySelectorAll('#home-doc-list .home-doc')).some(row=>row.textContent.includes('3 pages')));
 const rows=await page.$$('#home-doc-list .home-doc');
 for (const row of rows) { if ((await row.evaluate(el=>el.textContent)).includes('3 pages')) { await (await row.$('button')).click(); break; } }
 await page.waitForFunction(()=>document.querySelector('.pdf-page canvas')?.width > 0);
 const rendered = await page.evaluate(()=>({pages:document.querySelectorAll('.pdf-page').length,canvasWidth:document.querySelector('.pdf-page canvas').width,canvasHeight:document.querySelector('.pdf-page canvas').height}));
 assert.equal(rendered.pages,3); assert.ok(rendered.canvasHeight>0);
 await page.screenshot({path:`${directory}/jett-return-reopened.png`,fullPage:true});
 await writeFile(`${directory}/journey-proof.json`,JSON.stringify({result:'PASS_LOCAL',sourceId:source.id,resultId:returned.id,originalPages:2,resultPages:returned.provenance.pageCount,originalSHA256:createHash('sha256').update(original).digest('hex'),resultSHA256:createHash('sha256').update(Buffer.from(returned.bytes)).digest('hex'),sourcePreserved:true,reloadPreserved:true,rendered,provenance:returned.provenance,errors},null,2));
 console.log('PASS JETT original -> Bento duplicate -> export -> JETT durable three-page result; source intact after reload');
} finally {await browser.close();}
