/**
 * Generates test/fixtures/sample.docx hermetically. A .docx is a zip of XML
 * parts; jszip (already in the tree via mammoth) builds it.
 *
 * Run: npx tsx scripts/make-fixture-docx.ts
 */

import { writeFile, mkdir } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import JSZip from "jszip";

const here = dirname(fileURLToPath(import.meta.url));
const out = resolve(here, "../test/fixtures/sample.docx");

const contentTypes = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
  <Default Extension="xml" ContentType="application/xml"/>
  <Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>
</Types>`;

const rels = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/>
</Relationships>`;

const document = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
  <w:body>
    <w:p><w:pPr><w:pStyle w:val="Heading1"/></w:pPr><w:r><w:t>Fixture document</w:t></w:r></w:p>
    <w:p><w:r><w:t>A paragraph inside the docx fixture.</w:t></w:r></w:p>
    <w:p><w:r><w:t>A second paragraph, to prove ordering.</w:t></w:r></w:p>
  </w:body>
</w:document>`;

const zip = new JSZip();
zip.file("[Content_Types].xml", contentTypes);
zip.file("_rels/.rels", rels);
zip.file("word/document.xml", document);

const bytes = await zip.generateAsync({
  type: "uint8array",
  compression: "DEFLATE",
  // fixed date so the generated bytes are stable run-to-run
  ...( {} as object ),
});
await mkdir(dirname(out), { recursive: true });
await writeFile(out, bytes);
console.log(`wrote ${out} (${bytes.byteLength} bytes)`);
