/**
 * Generates test/fixtures/sample.pdf hermetically (no network, no system
 * tools) so the PDF connector test runs against a real, reproducible PDF.
 *
 * Run: npx tsx scripts/make-fixture-pdf.ts
 */

import { writeFile, mkdir } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { PDFDocument, StandardFonts } from "pdf-lib";

const here = dirname(fileURLToPath(import.meta.url));
const out = resolve(here, "../test/fixtures/sample.pdf");

const doc = await PDFDocument.create();
doc.setTitle("jt fixture: two page sample");
// Fixed dates so the generated bytes are stable run-to-run.
doc.setCreationDate(new Date("2026-01-01T00:00:00Z"));
doc.setModificationDate(new Date("2026-01-01T00:00:00Z"));
doc.setProducer("jt-connectors fixture script");
doc.setCreator("jt-connectors fixture script");

const font = await doc.embedFont(StandardFonts.Helvetica);

const page1 = doc.addPage([612, 792]);
page1.drawText("The first page of the jt fixture.", { x: 72, y: 700, size: 14, font });
page1.drawText("It exists so the PDF connector test is hermetic.", { x: 72, y: 670, size: 12, font });

const page2 = doc.addPage([612, 792]);
page2.drawText("The second page carries different text.", { x: 72, y: 700, size: 14, font });
page2.drawText("Page numbers must survive into the result.", { x: 72, y: 670, size: 12, font });

const bytes = await doc.save();
await mkdir(dirname(out), { recursive: true });
await writeFile(out, bytes);
console.log(`wrote ${out} (${bytes.byteLength} bytes)`);
