// Runs only against an explicitly supplied local/test server and synthetic PDF.
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { basename } from 'node:path';
import { createServerClient } from '../src/server.js';
const [baseUrl,fixture]=process.argv.slice(2);
if (!baseUrl || !fixture || !process.env.JETT_SERVER_TOKEN) throw new Error('Provide server origin, synthetic PDF path and JETT_SERVER_TOKEN.');
const endpoint=new URL(baseUrl);
if (!['localhost','127.0.0.1','[::1]'].includes(endpoint.hostname)) throw new Error('This proof only runs against a loopback test server.');
const client=createServerClient({baseUrl,token:process.env.JETT_SERVER_TOKEN,authority:{actor_id:'actor-1',tenant_scope:'tenant-1',project_id:'project-1'}});
const bytes=await readFile(fixture);
const attached=await client.uploadAndAttach(new File([bytes],basename(fixture),{type:'application/pdf'}));
assert.deepEqual(Buffer.from(await client.downloadOriginal(attached.objectId)),bytes,'server download must equal the original');
const before=await client.readWork(attached.context);
assert.equal(before.items.length,0,'use isolated empty server storage for this proof');
const requestId=crypto.randomUUID();
const applied=await client.submit(attached.context,'Highlight the first paragraph.',{requestId});
assert.equal(applied.outcome,'action_applied');
const work=await client.readWork(attached.context);
assert.equal(work.items.length,1);
assert.ok(work.items[0].geometry.length);
await assert.rejects(client.submit({...attached.context,scene_version:attached.context.scene_version+1},'Highlight the first paragraph.',{requestId}),/changed instruction/);
const retry=await client.retry(requestId);
assert.equal(retry.operation_id,applied.operation_id);
assert.equal((await client.readWork(attached.context)).items.length,1);
const reattached=await client.attach(attached.objectId);
const recovered=await client.readWork(reattached.context);
assert.equal(recovered.items.length,1);
const undone=await client.undo(reattached.context,recovered);
assert.equal(undone.outcome,'action_undone');
assert.equal((await client.readWork(reattached.context)).items.length,0);
assert.deepEqual(await readFile(fixture),bytes);
console.log(JSON.stringify({result:'PASS_LOCAL',uploadDigestVerified:true,serverDownloadByteExact:true,applied:1,duplicateRetryAdded:0,reattached:1,remainingAfterUndo:0,originalUnchanged:true}));
