import './style.css';
import '../src/pwa.js';
import {journeys,references,components} from './catalog.js';
import {views,filterJourneys,loadPreferences,parseRoute} from './state.js';
import {escapeHtml as e,statusBadge,feedback} from './ui.js';
const sourceFiles=import.meta.glob(['../workspace/*.{js,css}','../notebooks/*.{js,css}','../src/*.{js,css}','../test/*.test.mjs','./*.{js,css}','../notebooks/design/tokens.json'],{query:'?raw',import:'default'});
const root=document.querySelector('#app'),dialog=document.querySelector('#dialog');
let prefs=loadPreferences(localStorage),query='',domain='All',status='All',savedOnly=false,step=0,previewState='ready',previewMode='simulation';
const specimenNotes={};
const icons={Overview:'◈',Journeys:'↗',Components:'▦',Foundations:'Aa',References:'▧',Readiness:'◎'};
let route=parseRoute(location.hash,journeys.map(j=>j.id));
function toast(message){const n=document.querySelector('#toast');n.textContent=message;n.hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>n.hidden=true,3500);}
function persist(){try{localStorage.setItem('jjty-playground-v1',JSON.stringify(prefs));return true;}catch{toast('Could not save your preferences. Export your inventory to keep a copy.');return false;}}
function navigate(view,id=''){location.hash=view+(id?'/'+id:'');}
addEventListener('hashchange',()=>{route=parseRoute(location.hash,journeys.map(j=>j.id));step=0;previewState='ready';previewMode='simulation';render();document.querySelector('h1')?.focus();});
function modal(title,body){const trigger=document.activeElement;dialog.innerHTML=`<div class="detail-header"><h2>${e(title)}</h2><button class="button" id="close-dialog" aria-label="Close dialog">✕</button></div>${body}`;dialog.showModal();dialog.querySelector('#close-dialog').onclick=()=>dialog.close();dialog.addEventListener('close',()=>trigger?.isConnected&&trigger.focus(),{once:true});}
function saveFavorite(id){const at=prefs.favorites.indexOf(id);if(at<0)prefs.favorites.push(id);else prefs.favorites.splice(at,1);persist();render();}
function referenceCard(r){return `<article class="reference-card"><div class="reference-meta"><span class="domain">${e(r.app)}</span><span class="rating">${r.rating}/5</span></div><h3><a href="${e(r.url)}" target="_blank" rel="noopener noreferrer">${e(r.title)} ↗</a></h3><p>${e(r.reason)}</p><span class="muted">${e(r.domain)} · Editorial fit rating</span></article>`;}
function mini(j){return `<div class="card-preview" aria-hidden="true"><div class="mini-window"><div class="mini-sidebar"><i></i><i></i><i></i></div><div class="mini-content"><b>${e(j.steps[0]||j.title)}</b><div class="mini-line"></div><div class="mini-line" style="width:65%"></div><div class="mini-pill">${e(j.steps[1]||'Continue')}</div></div></div><span class="preview-label">${j.steps.length} steps</span></div>`;}
function card(j){return `<article class="journey-card"><div class="card-top"><span class="domain">${e(j.domain)}</span><button class="favorite ${prefs.favorites.includes(j.id)?'active':''}" data-favorite="${e(j.id)}" aria-label="${prefs.favorites.includes(j.id)?'Unsave':'Save'} ${e(j.title)}" aria-pressed="${prefs.favorites.includes(j.id)}">${prefs.favorites.includes(j.id)?'★':'☆'}</button></div><a href="#Journeys/${e(j.id)}" class="journey-open">${mini(j)}<div class="card-body"><h3>${e(j.title)}</h3><p>${e(j.summary)}</p></div></a><div class="card-footer">${statusBadge(j.status)}<span>${j.referenceIds.length} references</span></div></article>`;}
function render(){document.documentElement.dataset.theme=prefs.theme;root.innerHTML=`<div class="app-shell"><aside class="sidebar"><a class="brand" href="#Overview"><span class="brand-mark">j</span><span>JJTY<small>Product playground</small></span></a><nav aria-label="Primary">${views.map(v=>`<a class="nav-link ${route.view===v?'active':''}" href="#${v}" ${route.view===v?'aria-current="page"':''}><span>${icons[v]}</span>${v}</a>`).join('')}</nav><div class="sidebar-foot"><span class="local-dot"></span> Local working edition<p>Explore the product.<br>Inspect the evidence.</p><a href="/workspace/index.html#Inbox" target="_blank" rel="noopener">Open workspace ↗</a></div></aside><main class="main"><header class="topbar"><label class="global-search"><span aria-hidden="true">⌕</span><input id="global-search" type="search" placeholder="Find a journey, action or domain" aria-label="Search journeys" value="${e(query)}"><kbd>/</kbd></label><div class="top-actions"><button class="button subtle" id="theme" aria-label="Switch to ${prefs.theme==='dark'?'light':'dark'} theme">${prefs.theme==='dark'?'☀':'☾'}</button><button class="button" id="export">Export inventory ↓</button></div></header><div class="content" id="content"></div></main></div>`;
 root.querySelector('#theme').onclick=()=>{prefs.theme=prefs.theme==='dark'?'light':'dark';persist();render();};
 root.querySelector('#export').onclick=exportInventory;
 root.querySelector('#global-search').oninput=event=>{query=event.target.value;if(route.view!=='Journeys'||route.id){route={view:'Journeys',id:''};history.replaceState(null,'','#Journeys');}root.querySelectorAll('.nav-link').forEach(a=>{const active=a.hash==='#Journeys';a.classList.toggle('active',active);if(active)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});renderContent();};
 renderContent();
}
function renderContent(){const content=document.querySelector('#content');if(route.id){detail(content);return;}({Overview:overview,Journeys:journeyList,Components:componentList,Foundations:foundations,References:referenceList,Readiness:readiness}[route.view]||overview)(content);bindCommon();}
function bindCommon(){root.querySelectorAll('[data-favorite]').forEach(b=>b.onclick=()=>saveFavorite(b.dataset.favorite));root.querySelectorAll('[data-code]').forEach(b=>b.onclick=()=>showCode(b.dataset.code));}
function heading(title,text){return `<div class="detail-header"><div><p class="eyebrow">${e(route.view)}</p><h1 tabindex="-1">${title}</h1><p class="muted">${text}</p></div></div>`;}
function overview(c){c.innerHTML=`<section class="hero"><div class="hero-copy"><p class="eyebrow">The system behind the product</p><h1 tabindex="-1">Every journey.<br>One workspace.</h1><p>Explore what JJTY does, how it feels, and what makes it work. From the first captured thought to the final shared document.</p><div class="hero-actions"><a class="button primary" href="#Journeys">Explore journeys ↗</a><a class="button" href="#Components">Open the design system</a></div></div><div class="hero-preview">${mini(journeys[0])}<div class="hero-preview-caption"><span class="local-dot"></span> References → journeys → working code</div></div></section><div class="section-title"><h2>Start with the whole journey</h2><a href="#Journeys">View all ${journeys.length} journeys ↗</a></div><div class="card-grid">${journeys.slice(0,6).map(card).join('')}</div><div class="section-title"><h2>A system you can inspect</h2></div><div class="component-grid"><a class="panel" href="#References"><span class="domain">Reference library</span><h3>${references.length} selected patterns</h3><p>Mobbin links, editorial ratings, and the specific lesson behind each selection.</p></a><a class="panel" href="#Readiness"><span class="domain">Evidence, not assumptions</span><h3>See what is actually ready</h3><p>Implementation coverage and unresolved release gates remain visible.</p></a><a class="panel" href="#Foundations"><span class="domain">Foundations</span><h3>One shared visual language</h3><p>Color, type, spacing, focus, feedback, and motion working together.</p></a></div>`;}
function journeyList(c){const domains=[...new Set(journeys.map(j=>j.domain))];const items=filterJourneys(journeys,{query,domain,status,favorites:savedOnly?prefs.favorites:null});c.innerHTML=`${heading('Explore the journeys','Follow a user’s intent through every step, state, reference and implementation boundary.')}<div class="toolbar"><div class="chips"><button class="chip ${!savedOnly?'active':''}" id="all-journeys">All journeys</button><button class="chip ${savedOnly?'active':''}" id="saved-journeys">Saved (${prefs.favorites.length})</button></div><label>Domain <select id="domain"><option>All</option>${domains.map(d=>`<option ${d===domain?'selected':''}>${e(d)}</option>`).join('')}</select></label><label>Status <select id="status"><option>All</option>${['implemented','partial','planned'].map(s=>`<option ${status===s?'selected':''}>${s}</option>`).join('')}</select></label><span class="muted">${items.length} journeys</span></div>${items.length?`<div class="card-grid">${items.map(card).join('')}</div>`:`<div class="empty-state"><h2>No matching journeys</h2><p>Try another phrase or clear your filters.</p><button class="button primary" id="clear-filters">Clear filters</button></div>`}`;c.querySelector('#domain').onchange=ev=>{domain=ev.target.value;renderContent();};c.querySelector('#status').onchange=ev=>{status=ev.target.value;renderContent();};c.querySelector('#all-journeys').onclick=()=>{savedOnly=false;renderContent();};c.querySelector('#saved-journeys').onclick=()=>{savedOnly=true;renderContent();};c.querySelector('#clear-filters')?.addEventListener('click',()=>{query='';domain=status='All';savedOnly=false;render();});}
function editorUrl(j){if(j.status==='planned')return null;if(['notebook','handwriting'].includes(j.id))return '/notebooks/index.html';if(j.id==='accounts')return '/workspace/index.html#Connections';if(j.id==='settings')return '/workspace/index.html#Settings';if(['email-pdf-reply','inbox','compose','help'].includes(j.id))return '/workspace/index.html#Inbox';return '/#/home';}
function detail(c){const j=journeys.find(x=>x.id===route.id);if(!j)return;const refs=references.filter(r=>j.referenceIds.includes(r.id));c.innerHTML=`<a class="breadcrumb" href="#Journeys">← All journeys</a><div class="detail-header"><div><p class="eyebrow">${e(j.domain)}</p><h1 tabindex="-1">${e(j.title)}</h1><p class="muted">${e(j.summary)}</p></div>${statusBadge(j.status)}</div><div class="detail-grid"><div class="detail-main"><div class="panel"><div class="section-title"><h2>Journey canvas</h2><div class="chips"><button id="simulate-mode" class="chip ${previewMode==='simulation'?'active':''}">State explorer</button><button id="live-mode" class="chip ${previewMode==='live'?'active':''}" ${editorUrl(j)?'':'disabled title="No working editor for this planned journey"'}>Working app ↗</button></div></div><ol class="step-list">${j.steps.map((s,i)=>`<li><button class="step-item ${step===i?'current':''}" data-step="${i}" aria-current="${step===i?'step':'false'}"><span>${i+1}</span>${e(s)}</button></li>`).join('')}</ol><div id="preview-area">${previewMode==='live'?`<div class="notice"><strong>Existing implementation</strong><p>This editor uses real browser storage. Use synthetic files for experiments. The journey’s remaining gaps are listed alongside it.</p><a href="${editorUrl(j)}" target="_blank" rel="noopener">Open full editor ↗</a></div><iframe id="preview-frame" title="JJTY working editor" src="${editorUrl(j)}"></iframe>`:simulation(j)}</div></div><div class="section-title"><h2>Selected references</h2><span class="muted">Ratings are JJTY fit, out of 5</span></div><div class="reference-grid">${refs.length?refs.map(referenceCard).join(''):'<div class="panel"><p>Reference selection remains open for this journey.</p></div>'}</div></div><aside class="inspector"><section class="panel"><h2>Implementation</h2>${statusBadge(j.status)}<p>${e(j.gap||'Review the linked implementation and tests before release.')}</p><h3>Source</h3>${j.code.map(p=>`<button class="code-link" data-code="${e(p)}">${e(p)} ↗</button>`).join('')}<h3>Verification sources</h3>${j.tests.length?j.tests.map(p=>`<button class="code-link" data-code="${e(p)}">${e(p)} ↗</button>`).join(''):'<p class="muted">No mapped automated test yet.</p>'}<p class="muted">A linked test is not proof that it passed.</p></section><section class="panel"><h2>Your review notes</h2><label for="review-note">What should change?</label><textarea id="review-note" rows="6" placeholder="Keep decisions next to the journey…">${e(prefs.notes[j.id]||'')}</textarea><p class="muted" id="note-status">Stored only in this browser.</p><button class="button" data-favorite="${e(j.id)}">${prefs.favorites.includes(j.id)?'★ Saved':'☆ Save journey'}</button></section></aside></div>`;
 c.querySelectorAll('[data-step]').forEach(b=>b.onclick=()=>{step=Number(b.dataset.step);renderContent();});c.querySelector('#simulate-mode').onclick=()=>{previewMode='simulation';renderContent();};c.querySelector('#live-mode').onclick=()=>{previewMode='live';renderContent();};c.querySelector('#review-note').oninput=ev=>{prefs.notes[j.id]=ev.target.value;document.querySelector('#note-status').textContent=persist()?'Saved in this browser.':'Not saved. Copy this note before leaving.';};bindSimulation(c,j);bindCommon();}
function simulation(j){return `<p class="muted">Interactive state specimen · synthetic content · does not perform delivery or change documents</p><div class="state-picker" aria-label="Preview state">${[...new Set(['ready',...j.states,'empty','loading','saved','offline','error','permission'])].map(s=>`<button class="state-button ${s===previewState?'selected':''}" data-state="${s}" aria-pressed="${s===previewState}">${s}</button>`).join('')}</div><div class="preview-stage"><div class="device-frame"><div class="device-toolbar"><span>JJTY</span><span>Step ${step+1} of ${j.steps.length}</span></div><div class="device-content"><span class="domain">${e(j.domain)}</span><h2>${e(j.steps[step])}</h2>${feedback(previewState,j.title)}${previewState==='ready'||previewState==='saved'?`<label>Working note<textarea id="specimen-note" rows="4" placeholder="Try the interaction…">${e(specimenNotes[j.id]??'Review the document and keep the original.')}</textarea></label>`:''}${previewState==='permission'?'<button class="button" id="use-text">Continue with text</button>':''}${previewState==='error'?'<button class="button primary" id="retry-state">Retry save</button>':''}</div><div class="device-footer"><button class="button" id="previous-step" ${step===0?'disabled':''}>Back</button><button class="button primary" id="next-step">${step===j.steps.length-1?'Restart journey':'Continue'}</button></div></div></div>`;}
function bindSimulation(c,j){c.querySelector('#specimen-note')?.addEventListener('input',ev=>{specimenNotes[j.id]=ev.target.value;});c.querySelectorAll('[data-state]').forEach(b=>b.onclick=()=>{previewState=b.dataset.state;renderContent();});c.querySelector('#previous-step')?.addEventListener('click',()=>{step=Math.max(0,step-1);renderContent();});c.querySelector('#next-step')?.addEventListener('click',()=>{step=(step+1)%j.steps.length;previewState='ready';renderContent();});c.querySelector('#retry-state')?.addEventListener('click',()=>{previewState='saved';renderContent();});c.querySelector('#use-text')?.addEventListener('click',()=>{previewState='ready';renderContent();});}
function componentList(c){c.innerHTML=`${heading('Components, with behavior','Shared playground primitives, alongside the production components they document.')}<section class="panel"><h2>Feedback specimen</h2><p class="muted">This exact renderer powers the journey state explorer.</p><div class="state-picker">${['empty','loading','saved','offline','error','permission'].map(s=>`<button class="state-button" data-feedback="${s}">${s}</button>`).join('')}</div><div id="feedback-demo">${feedback('saved')}</div><button class="code-link" data-code="playground/ui.js">View shared renderer ↗</button></section><div class="section-title"><h2>Component inventory</h2><span class="muted">${components.length} components</span></div><div class="component-grid">${components.map(x=>`<article class="panel"><span class="domain">${e(x.category)}</span><h3>${e(x.name)}</h3><p>${e(x.description)}</p>${statusBadge(x.status)}<button class="code-link" data-code="${e(x.source)}">View source ↗</button></article>`).join('')}</div>`;c.querySelectorAll('[data-feedback]').forEach(b=>b.onclick=()=>{c.querySelector('#feedback-demo').innerHTML=feedback(b.dataset.feedback);});}
function foundations(c){const colors=[['Action','#2457e8'],['Ink','#111318'],['Canvas','#f5f6f8'],['Surface','#ffffff'],['Success','#167343'],['Error','#b73535']];c.innerHTML=`${heading('The foundations','A restrained system that gives the content room and makes the next action clear.')}<div class="section-title"><h2>Color roles</h2></div><div class="token-grid">${colors.map(([name,value])=>`<button class="token-swatch" data-color="${value}" style="--swatch:${value}"><span></span><strong>${name}</strong><code>${value}</code></button>`).join('')}</div><div class="component-grid" style="margin-top:28px"><section class="panel"><h2>Typography</h2><p style="font-size:32px;font-weight:650;letter-spacing:-1px">Read. Make. Return.</p><p>System fonts keep the interface familiar and fast. Body text remains comfortable; supporting labels stay secondary.</p><p><strong>14px</strong> body · <strong>23px</strong> section heading · <strong>44px</strong> minimum touch control</p></section><section class="panel"><h2>Spacing</h2><div class="spacing-demo">${[4,8,12,16,24,32].map(n=>`<div><span style="display:inline-block;width:${n*3}px;height:12px;background:var(--accent,#2458e6)"></span> ${n}px</div>`).join('')}</div></section><section class="panel"><h2>Interaction rules</h2><ul><li>Explain save, send and offline states separately.</li><li>Keep an obvious way back.</li><li>Keep destructive actions reversible where possible.</li><li>Retain originals during editing and export.</li><li>Use visible keyboard focus and respect reduced motion.</li></ul></section></div><section class="panel" style="margin-top:24px"><h2>Implementation boundary</h2><p>These tokens style this playground. Existing reader and notebook editors retain their current styles. Their migration to a single product-wide token system is tracked as unfinished work.</p><button class="code-link" data-code="playground/style.css">Inspect the live stylesheet ↗</button></section>`;c.querySelectorAll('[data-color]').forEach(b=>b.onclick=()=>{modal('Color token',`<p>Select and copy this value:</p><input aria-label="Color value" readonly value="${b.dataset.color}">`);dialog.querySelector('input').select();});}
function referenceList(c){c.innerHTML=`${heading('The reference library','Selected Mobbin patterns. Adopt the useful interaction, not the entire app.')}<div class="toolbar"><label>Filter references <input type="search" id="reference-search" placeholder="App, domain or pattern"></label><span class="muted">${references.length} curated references</span></div><div class="reference-grid" id="reference-results">${references.map(referenceCard).join('')}</div><p class="muted">Ratings reflect editorial fit for JJTY. Recorded screenshots are design evidence, not a claim about current service availability or accessibility conformance. Links open Mobbin; source images are not republished here.</p>`;c.querySelector('#reference-search').oninput=ev=>{const q=ev.target.value.toLowerCase();const list=references.filter(r=>`${r.app} ${r.title} ${r.domain}`.toLowerCase().includes(q));c.querySelector('#reference-results').innerHTML=list.length?list.map(referenceCard).join(''):'<div class="empty-state">No matching references. Try a different term.</div>';};}
function readiness(c){c.innerHTML=`${heading('Readiness is evidence','Keep design completeness, implementation and release verification separate.')}<div class="notice"><strong>Product release is not verified</strong><p>The playground runs locally. This does not establish native app completeness, provider delivery, physical-device behavior, deployment or store approval.</p></div><div class="panel" style="overflow:auto"><table><thead><tr><th>Journey</th><th>Implementation</th><th>Remaining gate</th></tr></thead><tbody>${journeys.map(j=>`<tr><td><a href="#Journeys/${e(j.id)}">${e(j.title)}</a></td><td>${statusBadge(j.status)}</td><td>${e(j.gap||'Fresh acceptance verification required.')}</td></tr>`).join('')}</tbody></table></div><div class="section-title"><h2>Release gates</h2></div><div class="component-grid">${[['Runtime','Complete real account import, delivery receipts, cross-device recovery and storage boundaries.'],['Native devices','Verify exact signed Android and iOS artifacts on physical devices, including permissions, process death and upgrade.'],['Store submission','Verify app identity, signing custody, privacy disclosures, support links, screenshots, review access and distribution approval.']].map(([a,b])=>`<section class="panel"><span class="status planned">Unverified</span><h3>${a}</h3><p>${b}</p></section>`).join('')}</div>`;}
async function showCode(path){const normalized=path.replace(/^\.\//,'');const key=normalized.startsWith('playground/')?'./'+normalized.slice(11):'../'+normalized;const loader=sourceFiles[key];if(!loader){modal('Source reference',`<p>The catalog points to <code>${e(path)}</code>. This file is not bundled in the source inspector.</p>`);return;}modal(path,'<p role="status">Loading source…</p>');try{const code=await loader();if(dialog.open){dialog.innerHTML=`<div class="detail-header"><h2>${e(path)}</h2><button class="button" id="close-dialog" aria-label="Close dialog">✕</button></div><pre tabindex="0"><code>${e(code)}</code></pre>`;dialog.querySelector('#close-dialog').onclick=()=>dialog.close();}}catch{dialog.innerHTML='<p>Could not load source. Close and retry.</p><button class="button" onclick="this.closest(\'dialog\').close()">Close</button>';}}
function exportInventory(){const value={title:'JJTY product playground',exportedAt:new Date().toISOString(),evidence:'Catalog statuses are source-audit classifications, not fresh device or release verification.',journeys,references,components,review:{favorites:prefs.favorites,notes:prefs.notes}};const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='jjty-product-inventory.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Inventory exported with your review notes.');}
addEventListener('keydown',ev=>{if(ev.key==='/'&&!['INPUT','TEXTAREA'].includes(document.activeElement?.tagName)&&!dialog.open){ev.preventDefault();document.querySelector('#global-search').focus();}});
render();
