import './style.css';
import '../src/pwa.js';

const tools = [
  ['documents','Documents','Read and mark PDFs','/studio/index.html#desk','M4 3h10l4 4v14H4z M14 3v5h4 M7 12h8 M7 16h6'],
  ['notebooks','Write','Notes beside your sources','/notebooks/index.html','M4 4h16v16H4z M8 4v16 M12 8h5 M12 12h5'],
  ['scan','Scan','Paper into a document','/studio/index.html#scan','M3 8V3h5 M16 3h5v5 M21 16v5h-5 M8 21H3v-5 M7 8h10v8H7z'],
  ['tenders','Tenders','Prepare and review a bid','/workspace/index.html#Tenders','M5 4h14v17H5z M9 4V2h6v2 M8 9h2 M12 9h4 M8 14h2 M12 14h4'],
  ['reader','Reader','Voice, sharing and recovery','/reader/index.html','M3 4h7l2 2 2-2h7v16h-7l-2 2-2-2H3z M12 6v16'],
];
const descriptions = Object.fromEntries(tools.map(([id,,description])=>[id,description]));
const frames = new Map();
const body = document.querySelector('#webx');
const icon = path=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true">${path?`<path d="${path}"/>`:''}</svg>`;
body.innerHTML=`<header class="bench-header"><a class="bench-brand" href="#documents" aria-label="WebX documents">${icon('M3 7h18 M3 12h12 M3 17h18')}<span>WebX</span></a><span class="bench-purpose">Your document workbench</span><button id="workbench-help" type="button">About this workspace</button></header><nav class="bench-switcher" aria-label="Workspace apps">${tools.map(([id,label,,url,path])=>`<a href="#${id}" data-tool="${id}">${icon(path)}<span>${label}</span></a>`).join('')}<a href="/playground/index.html" target="_blank" rel="noopener" class="bench-experiments">Experiments</a></nav><main class="bench-work"><div class="bench-context"><h1 id="active-title"></h1><span id="active-description"></span><a id="standalone" target="_blank" rel="noopener">Open separately</a></div><p id="loading" role="status">Opening your workspace…</p><div id="panels"></div></main><dialog id="bench-help"><h2>A place for document work</h2><p>Keep PDFs, source-linked notes and scans together in this browser. Switching tools keeps the work you have open.</p><p>Documents, notes and tender preparation save locally. Use each tool’s export or backup before clearing browser data. Sharing, AI review and government submission have separate connection and review steps.</p><p>Scan and tender workflows are experimental. Check every exported document. Government signing, payment and submission stay with you.</p><button id="close-help">Back to work</button></dialog>`;
const panels=document.querySelector('#panels'),loading=document.querySelector('#loading'),dialog=document.querySelector('#bench-help');
let active;
function classify(url){if(url.origin!==location.origin)return null;if(/^\/studio\//.test(url.pathname))return url.hash.startsWith('#scan')?'scan':'documents';if(/^\/notebooks\//.test(url.pathname))return 'notebooks';if(/^\/workspace\//.test(url.pathname)&&url.hash==='#Tenders')return 'tenders';if(/^\/reader\//.test(url.pathname)||(url.pathname==='/'&&url.hash.startsWith('#/')))return 'reader';return null;}
function pause(frame){try{frame.contentWindow.dispatchEvent(new Event('webx:pause'));frame.contentDocument.dispatchEvent(new Event('jetty-native-background'));frame.contentWindow.__jtApp?.position?.flush();}catch{}}
function remember(id){try{localStorage.setItem('webx-active-tool-v1',id);}catch{}}
function setReady(frame){if(frame.dataset.tool===active){loading.hidden=true;frame.hidden=false;}}
function instrument(frame){try{const win=frame.contentWindow,doc=frame.contentDocument;if(win.location.origin!==location.origin)return;const current=new URL(win.location.href),kind=classify(current);if(kind&&kind!==frame.dataset.tool){const destination=current.pathname+current.search+current.hash;pause(frame);frame.src=frame.dataset.lastUrl||tools.find(t=>t[0]===frame.dataset.tool)[3];open(kind,destination);return;}frame.dataset.lastUrl=current.href;doc.documentElement.dataset.webx='embedded';doc.addEventListener('click',event=>{const link=event.target.closest('a[href]');if(!link||link.target==='_blank'||event.ctrlKey||event.metaKey||event.shiftKey||event.altKey)return;const url=new URL(link.href),kind=classify(url);if(kind&&kind!==frame.dataset.tool){event.preventDefault();open(kind,url.pathname+url.search+url.hash);}});win.addEventListener('hashchange',()=>{const url=new URL(win.location.href),kind=classify(url);if(kind&&kind!==frame.dataset.tool)open(kind,url.pathname+url.search+url.hash);else frame.dataset.lastUrl=url.href;});const started=Date.now();const ready=()=>{if(!frame.isConnected)return;const populated=frame.dataset.tool==='reader'?win.__jtApp?.booted:doc.querySelector('#app,#workspace')?.textContent.trim().length>120 || doc.querySelector('.atelier')?.textContent.trim().length>120;if(populated)setReady(frame);else if(Date.now()-started<30000)setTimeout(ready,100);else if(frame.dataset.tool===active)loading.textContent='Still opening. You can open this tool separately to retry.';};ready();}catch{loading.textContent='This tool could not open. Use Open separately to retry.';}}
function open(id,href){const tool=tools.find(t=>t[0]===id)||tools[0];id=tool[0];if(active&&active!==id)pause(frames.get(active));active=id;remember(id);document.querySelector('#active-title').textContent=tool[1];document.querySelector('#active-description').textContent=descriptions[id]+(['scan','tenders'].includes(id)?' · Experimental':'');document.querySelector('#standalone').href=href||tool[3];document.querySelectorAll('[data-tool]').forEach(a=>{if(a.dataset.tool===id)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});for(const frame of frames.values())frame.hidden=frame.dataset.tool!==id;let frame=frames.get(id);if(!frame){frame=document.createElement('iframe');frame.title=tool[1]+' workspace';frame.dataset.tool=id;frame.allow='camera; microphone; clipboard-write';frame.src=href||tool[3];frame.dataset.lastUrl=frame.src;frame.addEventListener('load',()=>instrument(frame));frames.set(id,frame);panels.append(frame);loading.hidden=false;}else if(href&&new URL(href,location.origin).href!==frame.contentWindow.location.href){frame.src=href;loading.hidden=false;}else loading.hidden=true;history.replaceState(null,'','#'+id);}
document.querySelectorAll('[data-tool]').forEach(a=>a.addEventListener('click',event=>{event.preventDefault();open(a.dataset.tool);}));
document.querySelector('#workbench-help').onclick=()=>dialog.showModal();document.querySelector('#close-help').onclick=()=>dialog.close();dialog.addEventListener('close',()=>document.querySelector('#workbench-help').focus());
addEventListener('hashchange',()=>{const id=location.hash.slice(1);if(tools.some(t=>t[0]===id)&&id!==active)open(id);});
addEventListener('pagehide',()=>{for(const frame of frames.values())pause(frame);});document.addEventListener('visibilitychange',()=>{if(document.hidden)for(const frame of frames.values())pause(frame);});
let initial=location.hash.slice(1);if(location.search.includes('workspaceSession')||initial.startsWith('/'))open('reader','/reader/'+location.search+location.hash);else{if(!tools.some(t=>t[0]===initial))try{initial=localStorage.getItem('webx-active-tool-v1');}catch{}open(initial);}
